'use client'

import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, CircleDollarSign, Link2, RefreshCw, Search, TriangleAlert } from 'lucide-react'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { PageHeader, MetricCard, EmptyState, StatusBadge } from '@/components/workspace/primitives'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SelectMenu } from '@/components/ui/select-menu'
import { createClient } from '@/lib/supabase/client'
import { money, relativeDate } from '@/lib/metrics'
import { cn } from '@/lib/utils'
import { userError } from '@/lib/user-error'
import type { PaymentDraft } from '@/lib/types'

type RecStatus='unmatched'|'matched'|'needs_review'

type FormState={status:RecStatus;reference:string;actualFee:string;actualRecipient:string;note:string}
const blank:FormState={status:'unmatched',reference:'',actualFee:'',actualRecipient:'',note:''}

export default function ReconciliationPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const ru=lang==='ru'
  const settled=useMemo(()=>ws.payments.filter(p=>p.status==='paid'||p.status==='received'),[ws.payments])
  const [query,setQuery]=useState('');const [selectedId,setSelectedId]=useState<string|null>(null);const [form,setForm]=useState<FormState>(blank);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return settled.filter(p=>!q||`${p.supplier_name} ${p.invoice_number} ${p.reconciliation_reference}`.toLowerCase().includes(q))},[settled,query])
  const selected=settled.find(p=>p.id===selectedId)||null
  useEffect(()=>{if(!selected&&filtered.length)setSelectedId(filtered[0].id)},[filtered,selected])
  useEffect(()=>{if(!selected){setForm(blank);return}setForm({status:selected.reconciliation_status==='matched'?'matched':selected.reconciliation_status==='needs_review'?'needs_review':'unmatched',reference:selected.reconciliation_reference||'',actualFee:selected.actual_fee==null?'':String(selected.actual_fee),actualRecipient:selected.actual_recipient_amount==null?'':String(selected.actual_recipient_amount),note:selected.reconciliation_note||''})},[selected?.id,selected?.updated_at])
  const unmatched=settled.filter(p=>p.reconciliation_status==='unmatched').length;const matched=settled.filter(p=>p.reconciliation_status==='matched').length;const review=settled.filter(p=>p.reconciliation_status==='needs_review').length
  const actualFeeRows=settled.filter(p=>p.reconciliation_status==='matched'&&p.actual_fee!=null)

  async function save(){if(!selected||saving)return;setSaving(true);setError('');const fee=form.actualFee.trim()===''?null:Number(form.actualFee);const recipient=form.actualRecipient.trim()===''?null:Number(form.actualRecipient);try{const {error}=await createClient().rpc('flowpay_reconcile_payment',{p_payment_id:selected.id,p_status:form.status,p_reference:form.reference.trim(),p_actual_fee:fee,p_actual_recipient_amount:recipient,p_note:form.note.trim()});if(error)throw error;await ws.refresh()}catch{setError(userError(lang,'save'))}finally{setSaving(false)}}

  return <div className="fp-enter"><PageHeader eyebrow={ru?'После оплаты':'After settlement'} title={ru?'Сверка платежей':'Payment reconciliation'} subtitle={ru?'Сопоставьте завершённые платежи с банковским подтверждением. Здесь фиксируются фактическая комиссия, сумма получателя и reference — без догадок и приблизительных значений.':'Match settled payments with bank evidence. Record the actual fee, recipient amount and reference without estimates.'}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={ru?'Нужно сверить':'To reconcile'} value={String(unmatched)} meta={ru?'оплаченных платежей':'settled payments'} icon={<RefreshCw size={16}/>}/><MetricCard label={ru?'Сверено':'Matched'} value={String(matched)} meta={ru?'подтверждено reference':'confirmed with evidence'} icon={<CheckCircle2 size={16}/>}/><MetricCard label={ru?'Нужна проверка':'Needs review'} value={String(review)} meta={ru?'есть расхождение':'possible discrepancy'} icon={<TriangleAlert size={16}/>}/><MetricCard label={ru?'Факт. комиссии':'Actual fees'} value={String(actualFeeRows.length)} meta={ru?'платежей с фактической комиссией':'payments with an actual fee recorded'} icon={<CircleDollarSign size={16}/>}/></div>
    <Card className="mt-4 overflow-hidden"><div className="border-b border-[var(--fp-border)] p-4"><label className="flex h-11 items-center gap-2 rounded-[10px] border border-[var(--fp-border)] bg-white px-3"><Search size={15} className="text-[var(--fp-subtle)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ru?'Найти платёж, счёт или reference…':'Find a payment, invoice or reference…'} className="w-full bg-transparent text-[14px] outline-none placeholder:text-[var(--fp-subtle)]"/></label></div><div className="grid min-h-[560px] lg:grid-cols-[minmax(0,1fr)_430px]">
      <div className="border-b border-[var(--fp-border)] lg:border-b-0 lg:border-r"><div className="hidden grid-cols-[1.4fr_.8fr_.75fr_.65fr] gap-3 border-b border-[var(--fp-border)] bg-[#fafbf8] px-4 py-2.5 text-[11px] font-semibold uppercase tracking-[.08em] text-[var(--fp-subtle)] sm:grid"><span>{ru?'Поставщик':'Supplier'}</span><span>{ru?'Сумма':'Amount'}</span><span>{ru?'Оплата':'Paid'}</span><span>{ru?'Сверка':'Match'}</span></div>{filtered.length?<div className="divide-y divide-[var(--fp-border)]">{filtered.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} className={cn('grid w-full gap-2 px-4 py-3.5 text-left transition hover:bg-[#fafbf8] sm:grid-cols-[1.4fr_.8fr_.75fr_.65fr] sm:items-center',selectedId===p.id&&'bg-[#f3f8f4]')}><span className="min-w-0"><strong className="block truncate text-[13px]">{p.supplier_name}</strong><small className="block truncate text-[11px] text-[var(--fp-muted)]">{p.invoice_number||p.reference||'—'}</small></span><strong className="text-[13px]">{money(p.amount,p.currency,lang)}</strong><span className="text-[12px] text-[var(--fp-muted)]">{relativeDate(p.received_at||p.paid_at,lang)}</span><span><StatusBadge status={p.reconciliation_status}/></span></button>)}</div>:<div className="p-5"><EmptyState title={ru?'Платежей для сверки пока нет':'Nothing to reconcile yet'} description={ru?'Как только платёж получит статус «Оплачен» или «Получен», он появится здесь.':'Payments appear here after they are marked Paid or Received.'}/></div>}</div>
      <div className="p-5 sm:p-6">{selected?<><div className="flex items-start justify-between gap-3"><div><span className="text-[11px] font-semibold uppercase tracking-[.1em] text-[var(--fp-subtle)]">{ru?'Платёж':'Payment'}</span><h2 className="mt-1 text-[18px] font-semibold tracking-[-.025em]">{selected.supplier_name}</h2><p className="mt-1 text-[13px] text-[var(--fp-muted)]">{money(selected.amount,selected.currency,lang)} · {selected.invoice_number||(ru?'Без счёта':'No invoice')}</p></div><StatusBadge status={selected.status}/></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label={ru?'Статус сверки':'Reconciliation status'}><SelectMenu value={form.status} onChange={v=>setForm(f=>({...f,status:v as RecStatus}))} options={[{value:'unmatched',label:ru?'Не сверено':'Unmatched'},{value:'matched',label:ru?'Сверено':'Matched'},{value:'needs_review',label:ru?'Нужна проверка':'Needs review'}]}/></Field><Field label={ru?'Банковский reference':'Bank reference'}><Input value={form.reference} onChange={e=>setForm(f=>({...f,reference:e.target.value}))} placeholder="TRX / UETR / reference"/></Field><Field label={ru?`Фактическая комиссия, ${selected.currency}`:`Actual fee, ${selected.currency}`}><Input type="number" min="0" step="0.01" value={form.actualFee} onChange={e=>setForm(f=>({...f,actualFee:e.target.value}))} placeholder="0.00"/></Field><Field label={ru?`Фактически получено, ${selected.recipient_currency||selected.currency}`:`Actually received, ${selected.recipient_currency||selected.currency}`}><Input type="number" min="0" step="0.01" value={form.actualRecipient} onChange={e=>setForm(f=>({...f,actualRecipient:e.target.value}))} placeholder="0.00"/></Field></div><Field label={ru?'Комментарий':'Note'} className="mt-3"><textarea value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))} rows={4} className="w-full resize-none rounded-[11px] border border-[var(--fp-border)] bg-white px-3 py-2.5 text-[14px] outline-none focus:border-[#8fb59b] focus:ring-4 focus:ring-[#eaf4ed]" placeholder={ru?'Например: комиссия отличается от расчётной на 4 EUR':'Example: bank fee differs from estimate by 4 EUR'}/></Field>
        {form.status==='matched'&&!form.reference.trim()&&<div className="mt-3 rounded-[10px] border border-[#eadab9] bg-[#fffaf0] p-3 text-[12px] leading-5 text-[#825f20]">{ru?'Для статуса «Сверено» нужен банковский reference. Так запись можно подтвердить, а не просто отметить галочкой.':'A bank reference is required for Matched so the record is evidence-backed.'}</div>}{error&&<div className="mt-3 rounded-[10px] bg-[var(--fp-red-soft)] p-3 text-[13px] text-[var(--fp-red)]">{error}</div>}<Button className="mt-4 w-full" disabled={saving||(form.status==='matched'&&form.reference.trim().length<2)} onClick={save}><Link2 size={14}/>{saving?(ru?'Сохранение…':'Saving…'):(ru?'Сохранить сверку':'Save reconciliation')}</Button>
        {selected.reconciled_at&&<p className="mt-3 text-center text-[11px] text-[var(--fp-subtle)]">{ru?'Последняя сверка':'Last matched'} · {relativeDate(selected.reconciled_at,lang)}</p>}</>:<EmptyState compact title={ru?'Выберите платёж':'Select a payment'}/>}</div>
    </div></Card>
  </div>
}

function Field({label,children,className}:{label:string;children:React.ReactNode;className?:string}){return <label className={cn('block space-y-1.5 text-[13px] font-medium text-[var(--fp-muted)]',className)}><span>{label}</span>{children}</label>}
