-- FlowPay 1.5 — legal acceptance ledger
-- Run once after the existing FlowPay schema/upgrades.
-- This migration does not alter payment, invoice, counterparty or provider data.

begin;

create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null check (document_type in ('privacy','terms')),
  document_version text not null check (document_version ~ '^\\d{4}-\\d{2}-\\d{2}$'),
  action text not null check (action in ('acknowledged','accepted')),
  locale text not null default 'en' check (length(locale) between 2 and 12),
  source text not null default 'registration' check (source in ('registration','reacceptance')),
  accepted_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(user_id,document_type,document_version)
);

alter table public.legal_acceptances enable row level security;

drop policy if exists "legal acceptance own read" on public.legal_acceptances;
create policy "legal acceptance own read" on public.legal_acceptances
for select to authenticated
using ((select auth.uid()) = user_id);

-- Browser clients may inspect their own receipt but can never create, rewrite,
-- or delete acceptance evidence directly.
revoke all on public.legal_acceptances from anon, authenticated;
grant select on public.legal_acceptances to authenticated;

create index if not exists legal_acceptances_user_time_idx
  on public.legal_acceptances(user_id,accepted_at desc);

create or replace function public.flowpay_record_signup_legal_acceptances()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  privacy_version text := nullif(trim(coalesce(new.raw_user_meta_data->>'privacy_version','')), '');
  terms_version text := nullif(trim(coalesce(new.raw_user_meta_data->>'terms_version','')), '');
  legal_locale text := left(trim(coalesce(new.raw_user_meta_data->>'legal_locale','en')),12);
  signup_at timestamptz := coalesce(new.created_at,clock_timestamp());
begin
  -- Only explicit flags produced by the registration review flow are recorded.
  -- accepted_at is server-derived from auth.users.created_at, not client time.
  if lower(coalesce(new.raw_user_meta_data->>'privacy_acknowledged','false')) = 'true'
     and privacy_version ~ '^\\d{4}-\\d{2}-\\d{2}$' then
    insert into public.legal_acceptances(user_id,document_type,document_version,action,locale,source,accepted_at)
    values(new.id,'privacy',privacy_version,'acknowledged',coalesce(nullif(legal_locale,''),'en'),'registration',signup_at)
    on conflict(user_id,document_type,document_version) do nothing;
  end if;

  if lower(coalesce(new.raw_user_meta_data->>'terms_accepted','false')) = 'true'
     and terms_version ~ '^\\d{4}-\\d{2}-\\d{2}$' then
    insert into public.legal_acceptances(user_id,document_type,document_version,action,locale,source,accepted_at)
    values(new.id,'terms',terms_version,'accepted',coalesce(nullif(legal_locale,''),'en'),'registration',signup_at)
    on conflict(user_id,document_type,document_version) do nothing;
  end if;

  return new;
end;
$$;

revoke all on function public.flowpay_record_signup_legal_acceptances() from public, anon, authenticated;

drop trigger if exists flowpay_record_signup_legal_acceptances on auth.users;
create trigger flowpay_record_signup_legal_acceptances
after insert on auth.users
for each row execute function public.flowpay_record_signup_legal_acceptances();

commit;
