-- FlowPay 1.2 launch-readiness migration.
-- Adds onboarding state, idempotent payment creation, distributed API rate limiting
-- and server-only operational event storage. No demo/provider data is inserted.

alter table public.company_profiles add column if not exists onboarding_completed_at timestamptz;
alter table public.company_profiles add column if not exists timezone text not null default '';

alter table public.payment_drafts add column if not exists idempotency_key text;
create unique index if not exists payment_drafts_user_idempotency_uidx
  on public.payment_drafts(user_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.flowpay_rate_limit_events (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  bucket text not null,
  created_at timestamptz not null default now()
);
create index if not exists flowpay_rate_limit_events_lookup_idx
  on public.flowpay_rate_limit_events(bucket, key_hash, created_at desc);
alter table public.flowpay_rate_limit_events enable row level security;
-- Intentionally no client policies. Service role/RPC only.

create or replace function public.flowpay_check_rate_limit(
  p_key_hash text,
  p_bucket text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  cutoff timestamptz := now() - make_interval(secs => greatest(1, p_window_seconds));
  used integer;
begin
  if p_limit < 1 or p_limit > 10000 then
    raise exception 'INVALID_RATE_LIMIT' using errcode='22023';
  end if;
  delete from public.flowpay_rate_limit_events where created_at < now() - interval '24 hours';
  select count(*)::integer into used
  from public.flowpay_rate_limit_events
  where key_hash = p_key_hash and bucket = p_bucket and created_at >= cutoff;

  if used >= p_limit then
    return query select false, 0;
    return;
  end if;

  insert into public.flowpay_rate_limit_events(key_hash,bucket) values(p_key_hash,p_bucket);
  return query select true, greatest(0, p_limit - used - 1);
end;
$$;
revoke all on function public.flowpay_check_rate_limit(text,text,integer,integer) from public;
grant execute on function public.flowpay_check_rate_limit(text,text,integer,integer) to service_role;
-- Service-role callers bypass grants; do not expose this RPC to anon/authenticated.

create table if not exists public.system_event_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  level text not null check (level in ('info','warning','error')),
  source text not null,
  code text not null,
  message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists system_event_logs_created_idx on public.system_event_logs(created_at desc);
create index if not exists system_event_logs_level_created_idx on public.system_event_logs(level,created_at desc);
alter table public.system_event_logs enable row level security;
-- Intentionally no client policies. Service role only.

create or replace function public.flowpay_complete_onboarding(
  p_name text,
  p_country text,
  p_currency text,
  p_timezone text default ''
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED' using errcode='42501'; end if;
  if length(trim(p_name)) < 2 then raise exception 'COMPANY_NAME_REQUIRED' using errcode='22023'; end if;
  if length(trim(p_country)) <> 2 then raise exception 'COUNTRY_REQUIRED' using errcode='22023'; end if;
  if length(trim(p_currency)) <> 3 then raise exception 'CURRENCY_REQUIRED' using errcode='22023'; end if;

  insert into public.company_profiles(user_id,name,country,preferred_currency,timezone,onboarding_completed_at)
  values(auth.uid(),trim(p_name),upper(trim(p_country)),upper(trim(p_currency)),trim(p_timezone),now())
  on conflict(user_id) do update set
    name=excluded.name,
    country=excluded.country,
    preferred_currency=excluded.preferred_currency,
    timezone=excluded.timezone,
    onboarding_completed_at=coalesce(public.company_profiles.onboarding_completed_at,now());
end;
$$;
revoke all on function public.flowpay_complete_onboarding(text,text,text,text) from public;
grant execute on function public.flowpay_complete_onboarding(text,text,text,text) to authenticated;

-- Create/update a payment in one server/RLS-aware operation with optional idempotency.
create or replace function public.flowpay_upsert_payment(
  p_payment_id uuid,
  p_idempotency_key text,
  p_counterparty_id uuid,
  p_supplier_name text,
  p_invoice_number text,
  p_amount numeric,
  p_currency text,
  p_due_date date,
  p_route_provider_code text,
  p_estimated_fee numeric,
  p_notes text,
  p_route_from_country text,
  p_route_to_country text,
  p_recipient_currency text,
  p_recipient_amount numeric,
  p_reference text,
  p_route_snapshot jsonb,
  p_payment_method text,
  p_charge_type text
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  result_id uuid;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED' using errcode='42501'; end if;
  if length(trim(p_supplier_name)) < 1 then raise exception 'SUPPLIER_REQUIRED' using errcode='22023'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'INVALID_AMOUNT' using errcode='22023'; end if;
  if p_payment_method not in ('bank_transfer','swift','local') then raise exception 'INVALID_PAYMENT_METHOD' using errcode='22023'; end if;
  if p_charge_type not in ('shared','sender','recipient') then raise exception 'INVALID_CHARGE_TYPE' using errcode='22023'; end if;
  if p_counterparty_id is not null and not exists(select 1 from public.counterparties where id=p_counterparty_id and user_id=auth.uid()) then
    raise exception 'COUNTERPARTY_NOT_FOUND' using errcode='42501';
  end if;

  if p_payment_id is null and nullif(trim(coalesce(p_idempotency_key,'')),'') is not null then
    select id into result_id from public.payment_drafts
      where user_id=auth.uid() and idempotency_key=trim(p_idempotency_key)
      limit 1;
    if result_id is not null then return result_id; end if;
  end if;

  if p_payment_id is null then
    insert into public.payment_drafts(
      user_id,idempotency_key,counterparty_id,supplier_name,invoice_number,amount,currency,due_date,
      route_provider_code,estimated_fee,notes,route_from_country,route_to_country,recipient_currency,
      recipient_amount,reference,route_snapshot,payment_method,charge_type,status
    ) values(
      auth.uid(),nullif(trim(coalesce(p_idempotency_key,'')),''),p_counterparty_id,trim(p_supplier_name),coalesce(p_invoice_number,''),p_amount,upper(p_currency),p_due_date,
      p_route_provider_code,p_estimated_fee,coalesce(p_notes,''),p_route_from_country,p_route_to_country,p_recipient_currency,
      p_recipient_amount,coalesce(p_reference,''),p_route_snapshot,p_payment_method,p_charge_type,'draft'
    ) returning id into result_id;
  else
    update public.payment_drafts set
      counterparty_id=p_counterparty_id,
      supplier_name=trim(p_supplier_name),
      invoice_number=coalesce(p_invoice_number,''),
      amount=p_amount,
      currency=upper(p_currency),
      due_date=p_due_date,
      route_provider_code=p_route_provider_code,
      estimated_fee=p_estimated_fee,
      notes=coalesce(p_notes,''),
      route_from_country=p_route_from_country,
      route_to_country=p_route_to_country,
      recipient_currency=p_recipient_currency,
      recipient_amount=p_recipient_amount,
      reference=coalesce(p_reference,''),
      route_snapshot=p_route_snapshot,
      payment_method=p_payment_method,
      charge_type=p_charge_type
    where id=p_payment_id and user_id=auth.uid() and status in ('draft','ready')
    returning id into result_id;
    if result_id is null then raise exception 'PAYMENT_NOT_EDITABLE' using errcode='22023'; end if;
  end if;
  return result_id;
end;
$$;
revoke all on function public.flowpay_upsert_payment(uuid,text,uuid,text,text,numeric,text,date,text,numeric,text,text,text,text,numeric,text,jsonb,text,text) from public;
grant execute on function public.flowpay_upsert_payment(uuid,text,uuid,text,text,numeric,text,date,text,numeric,text,text,text,text,numeric,text,jsonb,text,text) to authenticated;

create or replace function public.flowpay_upsert_counterparty(
  p_counterparty_id uuid,
  p_name text,
  p_country text,
  p_currency text,
  p_bank_country text,
  p_bank_name text,
  p_account_number text,
  p_account_holder text,
  p_bic text,
  p_email text,
  p_tax_id text
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare result_id uuid;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED' using errcode='42501'; end if;
  if length(trim(p_name)) < 1 then raise exception 'NAME_REQUIRED' using errcode='22023'; end if;
  if length(trim(p_country)) <> 2 or length(trim(p_bank_country)) <> 2 then raise exception 'COUNTRY_REQUIRED' using errcode='22023'; end if;
  if length(trim(p_currency)) <> 3 then raise exception 'CURRENCY_REQUIRED' using errcode='22023'; end if;
  if p_counterparty_id is null then
    insert into public.counterparties(user_id,name,country,currency,bank_country,bank_name,account_number,account_holder,bic,email,tax_id,verification_status)
    values(auth.uid(),trim(p_name),upper(p_country),upper(p_currency),upper(p_bank_country),trim(coalesce(p_bank_name,'')),trim(coalesce(p_account_number,'')),trim(coalesce(p_account_holder,'')),upper(trim(coalesce(p_bic,''))),lower(trim(coalesce(p_email,''))),trim(coalesce(p_tax_id,'')),'unverified')
    returning id into result_id;
  else
    update public.counterparties set name=trim(p_name),country=upper(p_country),currency=upper(p_currency),bank_country=upper(p_bank_country),bank_name=trim(coalesce(p_bank_name,'')),account_number=trim(coalesce(p_account_number,'')),account_holder=trim(coalesce(p_account_holder,'')),bic=upper(trim(coalesce(p_bic,''))),email=lower(trim(coalesce(p_email,''))),tax_id=trim(coalesce(p_tax_id,''))
    where id=p_counterparty_id and user_id=auth.uid()
    returning id into result_id;
    if result_id is null then raise exception 'COUNTERPARTY_NOT_FOUND' using errcode='42501'; end if;
  end if;
  return result_id;
end;
$$;
revoke all on function public.flowpay_upsert_counterparty(uuid,text,text,text,text,text,text,text,text,text,text) from public;
grant execute on function public.flowpay_upsert_counterparty(uuid,text,text,text,text,text,text,text,text,text,text) to authenticated;

create or replace function public.flowpay_upsert_invoice(
  p_invoice_id uuid,
  p_counterparty_id uuid,
  p_invoice_number text,
  p_supplier_name text,
  p_issue_date date,
  p_due_date date,
  p_amount numeric,
  p_currency text,
  p_reference text,
  p_notes text
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare result_id uuid;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED' using errcode='42501'; end if;
  if length(trim(p_supplier_name)) < 1 or p_amount is null or p_amount <= 0 then raise exception 'INVALID_INVOICE' using errcode='22023'; end if;
  if p_counterparty_id is not null and not exists(select 1 from public.counterparties where id=p_counterparty_id and user_id=auth.uid()) then raise exception 'COUNTERPARTY_NOT_FOUND' using errcode='42501'; end if;
  if p_invoice_id is null then
    insert into public.invoices(user_id,counterparty_id,invoice_number,supplier_name,issue_date,due_date,amount,currency,reference,notes,status)
    values(auth.uid(),p_counterparty_id,coalesce(p_invoice_number,''),trim(p_supplier_name),p_issue_date,p_due_date,p_amount,upper(p_currency),coalesce(p_reference,''),coalesce(p_notes,''),'open')
    returning id into result_id;
  else
    update public.invoices set counterparty_id=p_counterparty_id,invoice_number=coalesce(p_invoice_number,''),supplier_name=trim(p_supplier_name),issue_date=p_issue_date,due_date=p_due_date,amount=p_amount,currency=upper(p_currency),reference=coalesce(p_reference,''),notes=coalesce(p_notes,'')
    where id=p_invoice_id and user_id=auth.uid() and status in ('open','scheduled')
    returning id into result_id;
    if result_id is null then raise exception 'INVOICE_NOT_EDITABLE' using errcode='22023'; end if;
  end if;
  return result_id;
end;
$$;
revoke all on function public.flowpay_upsert_invoice(uuid,uuid,text,text,date,date,numeric,text,text,text) from public;
grant execute on function public.flowpay_upsert_invoice(uuid,uuid,text,text,date,date,numeric,text,text,text) to authenticated;

-- Expanded launch lifecycle: explicit cancellation/failure states and strict transitions.
alter table public.payment_drafts drop constraint if exists payment_drafts_status_check;
alter table public.payment_drafts add constraint payment_drafts_status_check
  check (status in ('draft','ready','paid','received','cancelled','failed')) not valid;

create or replace function public.flowpay_set_payment_status(p_payment_id uuid, p_status text)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_payment public.payment_drafts%rowtype;
  now_at timestamptz := now();
begin
  if p_status not in ('ready','paid','received','cancelled','failed') then raise exception 'INVALID_PAYMENT_STATUS' using errcode='22023'; end if;
  select * into current_payment from public.payment_drafts where id=p_payment_id and user_id=auth.uid() for update;
  if not found then raise exception 'PAYMENT_NOT_FOUND' using errcode='42501'; end if;

  if current_payment.status='draft' and p_status not in ('ready','cancelled') then raise exception 'INVALID_PAYMENT_TRANSITION' using errcode='22023'; end if;
  if current_payment.status='ready' and p_status not in ('paid','failed','cancelled') then raise exception 'INVALID_PAYMENT_TRANSITION' using errcode='22023'; end if;
  if current_payment.status='failed' and p_status not in ('ready','cancelled') then raise exception 'INVALID_PAYMENT_TRANSITION' using errcode='22023'; end if;
  if current_payment.status='paid' and p_status<>'received' then raise exception 'INVALID_PAYMENT_TRANSITION' using errcode='22023'; end if;
  if current_payment.status in ('received','cancelled') then raise exception 'INVALID_PAYMENT_TRANSITION' using errcode='22023'; end if;

  update public.payment_drafts set
    status=p_status,
    paid_at=case when p_status in ('paid','received') then coalesce(paid_at,now_at) when p_status in ('cancelled','failed') then null else paid_at end,
    received_at=case when p_status='received' then coalesce(received_at,now_at) when p_status in ('cancelled','failed') then null else received_at end
  where id=current_payment.id and user_id=auth.uid();

  if p_status in ('paid','received') then
    update public.invoices set status='paid' where payment_draft_id=current_payment.id and user_id=auth.uid() and status<>'cancelled';
  elsif p_status='cancelled' then
    update public.invoices set payment_draft_id=null,status=case when status='scheduled' then 'open' else status end
    where payment_draft_id=current_payment.id and user_id=auth.uid() and status not in ('paid','cancelled');
  end if;
end;
$$;
revoke all on function public.flowpay_set_payment_status(uuid,text) from public;
grant execute on function public.flowpay_set_payment_status(uuid,text) to authenticated;
