'use client'

import Link from 'next/link'
import { useMemo } from 'react'
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, CircleDollarSign, Clock3, Plus, ReceiptText, Route as RouteIcon, Settings2, ShieldCheck, Users } from 'lucide-react'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { workspaceDictionaries } from '@/lib/workspace-i18n'
import { workspaceCopy } from '@/lib/workspace-copy'
import { useFxMap } from '@/hooks/use-fx-map'
import { healthScore, isSettled, money, monthLabel, normalize, relativeDate, speedLabel } from '@/lib/metrics'
import { Card } from '@/components/ui/card'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { EmptyState, MetricCard, PageHeader, SectionTitle, StatusBadge } from '@/components/workspace/primitives'
import { VolumeAreaChart } from '@/components/workspace/LazyCharts'
import { buttonVariants } from '@/components/ui/button'
import { clamp, cn } from '@/lib/utils'
import { bankDetailsState } from '@/lib/payment-validation'

export default function DashboardPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const t=workspaceDictionaries[lang];const copy=workspaceCopy[lang];const base=ws.profile?.preferred_currency||null
  const currencies=useMemo(()=>Array.from(new Set([...ws.payments.map(p=>p.currency),...ws.calculations.map(c=>c.currency),...ws.counterparties.map(c=>c.currency)])),[ws.payments,ws.calculations,ws.counterparties]);const fx=useFxMap(base,currencies)
  const now=new Date();const monthStart=new Date(now.getFullYear(),now.getMonth(),1);const today=new Date();today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()+7)
  const settled=ws.payments.filter(isSettled);const monthPayments=settled.filter(p=>new Date(p.received_at||p.paid_at||p.updated_at)>=monthStart)
  const volume=base?monthPayments.reduce((s,p)=>s+(normalize(Number(p.amount),p.currency,base,fx.rates)||0),0):null
  const monthCalcs=ws.calculations.filter(c=>new Date(c.created_at)>=monthStart);const savings=base?monthCalcs.reduce((s,c)=>s+(normalize(Number(c.estimated_saving),c.currency,base,fx.rates)||0),0):null
  const avgFeePct=ws.calculations.length?ws.calculations.reduce((s,c)=>s+(Number(c.best_fee)/Math.max(1,Number(c.amount))*100),0)/ws.calculations.length:null;const score=healthScore(ws.payments,avgFeePct)
  const lastCalc=ws.calculations[0]||null;const lastRoutes=Array.isArray(lastCalc?.routes_snapshot)?lastCalc!.routes_snapshot.slice(0,3):[]

  const chart=useMemo(()=>{const months=Array.from({length:6},(_,i)=>new Date(now.getFullYear(),now.getMonth()-5+i,1));return months.map(d=>{const next=new Date(d.getFullYear(),d.getMonth()+1,1);const rows=settled.filter(p=>{const pd=new Date(p.received_at||p.paid_at||p.updated_at);return pd>=d&&pd<next});const value=base?rows.reduce((sum,p)=>sum+(normalize(Number(p.amount),p.currency,base,fx.rates)||0),0):rows.length;return{label:monthLabel(d,lang),value}})},[settled,base,fx.rates,lang])
  const upcoming=useMemo(()=>ws.payments.filter(p=>['draft','ready'].includes(p.status)&&p.due_date).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date))).slice(0,5),[ws.payments])
  const topCounterparties=useMemo(()=>{const agg=new Map<string,{name:string;country:string;value:number;count:number}>();for(const p of settled){if(!p.counterparty_id)continue;const cp=ws.counterparties.find(c=>c.id===p.counterparty_id);const v=base?normalize(Number(p.amount),p.currency,base,fx.rates):0;if(base&&v==null)continue;const cur=agg.get(p.counterparty_id)||{name:cp?.name||p.supplier_name,country:cp?.country||'',value:0,count:0};cur.value+=v||0;cur.count++;agg.set(p.counterparty_id,cur)}return [...agg.values()].sort((a,b)=>base?b.value-a.value:b.count-a.count).slice(0,5)},[settled,ws.counterparties,base,fx.rates])
  const recent=useMemo(()=>ws.payments.slice(0,6),[ws.payments]);const baseRates=useMemo(()=>currencies.filter(c=>c!==base&&fx.rates[c]).slice(0,4),[currencies,base,fx.rates])
  const overdue=ws.payments.filter(p=>['draft','ready'].includes(p.status)&&p.due_date&&new Date(`${p.due_date}T00:00:00`)<today)
  const dueSoon=ws.payments.filter(p=>['draft','ready'].includes(p.status)&&p.due_date&&new Date(`${p.due_date}T00:00:00`)>=today&&new Date(`${p.due_date}T00:00:00`)<=week)
  const needsBankDetails=ws.counterparties.filter(c=>bankDetailsState(c.bank_country,c.account_number,c.bic)!=='details_ready')
  const overdueInvoices=ws.invoices.filter(i=>['open','scheduled'].includes(i.status)&&i.due_date&&new Date(`${i.due_date}T00:00:00`)<today)
  const readiness=[Boolean(ws.profile?.name),Boolean(base),ws.counterparties.length>0,ws.payments.length>0].filter(Boolean).length
  const emptyAccount=ws.payments.length===0&&ws.calculations.length===0&&ws.counterparties.length===0
  const company=ws.profile?.name?.trim()

  return <div className="fp-enter">
    <PageHeader title={t.overview.title} eyebrow={company||undefined} subtitle={t.overview.subtitle} actions={<><Link href="/routes" className={cn(buttonVariants({variant:'secondary',size:'md'}))}><RouteIcon size={15}/>{lang==='ru'?'Сравнить маршрут':'Compare route'}</Link><Link href="/payments?new=1" className={cn(buttonVariants({size:'md'}))}><Plus size={15}/>{t.common.newPayment}</Link></>}/>

    {emptyAccount?<GettingStarted lang={lang} hasProfile={Boolean(ws.profile?.name)} hasBase={Boolean(base)}/>:<>
    {!base&&<Card className="mb-5 overflow-hidden border-[#cfe0d3] bg-[linear-gradient(110deg,#f1f8f3_0%,#fbfdfb_70%)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[var(--fp-green)] shadow-sm"><Settings2 size={18}/></span><div><strong className="text-[15px]">{lang==='ru'?'Завершите настройку отчётности':'Finish reporting setup'}</strong><p className="mt-1 max-w-2xl text-[14px] leading-5 text-[var(--fp-muted)]">{lang==='ru'?'Выберите базовую валюту компании, чтобы FlowPay показывал общий объём, экономию и аналитику в одном формате.':'Choose your company reporting currency to unlock normalized volume, savings and analytics.'}</p></div></div><Link href="/settings" className={cn(buttonVariants({size:'sm'}),'shrink-0')}>{lang==='ru'?'Настроить':'Set up'}<ArrowRight size={14}/></Link></div></Card>}

    <div className="fp-kpi-grid">
      <MetricCard accent label={t.overview.volume} value={base?money(volume,base,lang,true):String(monthPayments.length)} meta={base?`${t.common.thisMonth}${fx.missing.length?` · ${lang==='ru'?'не все валюты включены':'some currencies excluded'}`:''}`:(lang==='ru'?'завершено в этом месяце':'settled this month')} icon={<CircleDollarSign size={17}/>}/>
      <MetricCard label={t.overview.savings} value={base?money(savings,base,lang,true):String(monthCalcs.length)} meta={base?(monthCalcs.length?`${monthCalcs.length} ${lang==='ru'?'сравнений маршрутов':'route comparisons'}`:t.common.noData):(lang==='ru'?'сравнений маршрутов в этом месяце':'route comparisons this month')} icon={<RouteIcon size={17}/>}/>
      <MetricCard label={t.overview.counterparties} value={String(ws.counterparties.length)} meta={ws.counterparties.length?`${ws.counterparties.filter(c=>bankDetailsState(c.bank_country,c.account_number,c.bic)==='details_ready').length} ${lang==='ru'?'с готовыми реквизитами':'ready for payment'}`:(lang==='ru'?'Добавьте первого получателя':'Add your first beneficiary')} icon={<Users size={17}/>}/>
      <MetricCard label={t.overview.efficiency} value={score==null?'—':`${score}/100`} meta={score==null?t.overview.noPayments:score>=85?copy.common.excellent:score>=70?copy.common.good:copy.common.attention} icon={<Activity size={17}/>}/>
    </div>

    <div className="mt-5 grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
      <Card className="p-5 sm:p-6"><SectionTitle title={base?t.analytics.volumeTime:(lang==='ru'?'Завершённые платежи':'Settled payments')} action={t.common.viewAll} href="/analytics" subtitle={base?(lang==='ru'?'Объём за последние шесть месяцев':'Volume over the last six months'):(lang==='ru'?'Количество завершённых платежей за последние шесть месяцев':'Number of settled payments over the last six months')}/><div className="mt-5 flex items-end justify-between"><div><span className="text-[14px] font-medium text-[var(--fp-muted)]">{t.common.thisMonth}</span><strong className="mt-1 block text-[28px] font-semibold tracking-[-.05em]">{base?money(volume,base,lang,true):String(monthPayments.length)}</strong></div><span className="rounded-lg bg-[#f3f6f2] px-2.5 py-1.5 text-[14px] font-medium text-[var(--fp-muted)]">{base||(lang==='ru'?'платежей':'payments')}</span></div>{settled.length?<VolumeAreaChart data={chart} height={250} className="mt-3" valueFormatter={value=>base?money(value,base,lang,true):`${Math.round(value)} ${lang==='ru'?'плат.':'payments'}`}/>:<div className="mt-5"><EmptyState title={t.overview.noPayments} description={lang==='ru'?'После первого завершённого платежа здесь появится динамика операций.':'Your payment trend will appear after the first settled payment.'}/></div>}</Card>

      <Card className="p-5 sm:p-6"><SectionTitle title={lang==='ru'?'Требует внимания':'Needs attention'} subtitle={lang==='ru'?'Задачи, которые могут повлиять на ближайшие платежи':'Items that may affect upcoming payments'}/><div className="mt-4 space-y-1">{overdue.length>0&&<AttentionRow href="/payments" icon={<AlertTriangle size={16}/>} tone="danger" title={lang==='ru'?`${overdue.length} просроченных платежей`:`${overdue.length} overdue payments`} sub={lang==='ru'?'Проверьте сроки и статус оплаты':'Review due dates and payment status'}/>} {dueSoon.length>0&&<AttentionRow href="/payments" icon={<Clock3 size={16}/>} tone="warning" title={lang==='ru'?`${dueSoon.length} платежей на ближайшие 7 дней`:`${dueSoon.length} payments due in 7 days`} sub={lang==='ru'?'Убедитесь, что всё готово к отправке':'Make sure they are ready to send'}/>} {overdueInvoices.length>0&&<AttentionRow href="/invoices" icon={<ReceiptText size={16}/>} tone="warning" title={lang==='ru'?`${overdueInvoices.length} просроченных счетов`:`${overdueInvoices.length} overdue invoices`} sub={lang==='ru'?'Создайте платежи или обновите статус':'Create payments or update their status'}/>} {needsBankDetails.length>0&&<AttentionRow href="/counterparties" icon={<ShieldCheck size={16}/>} tone="neutral" title={lang==='ru'?`${needsBankDetails.length} контрагентов требуют реквизитов`:`${needsBankDetails.length} counterparties need payment details`} sub={lang==='ru'?'Заполните или проверьте банковские реквизиты перед оплатой':'Complete or check bank details before sending'}/>} {!overdue.length&&!dueSoon.length&&!overdueInvoices.length&&!needsBankDetails.length&&<div className="flex min-h-52 flex-col items-center justify-center text-center"><span className="grid size-11 place-items-center rounded-full bg-[var(--fp-green-soft)] text-[var(--fp-green)]"><CheckCircle2 size={20}/></span><strong className="mt-3 text-[14px]">{lang==='ru'?'Всё под контролем':'Everything is on track'}</strong><p className="mt-1 max-w-xs text-[14px] leading-5 text-[var(--fp-muted)]">{lang==='ru'?'Срочных задач по текущим платежам и контрагентам нет.':'There are no urgent payment or counterparty actions right now.'}</p></div>}</div></Card>
    </div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_.95fr]">
      <Card className="min-h-[330px] p-5 sm:p-6"><SectionTitle title={t.overview.routes} action={t.common.viewAll} href="/routes" subtitle={lang==='ru'?'Последнее рассчитанное направление':'Your latest route comparison'}/>{lastCalc?<div className="mt-5"><div className="flex items-center gap-3 text-[14px] font-semibold"><CountryFlag code={lastCalc.from_country}/><span>{lastCalc.from_country}</span><ArrowRight size={15} className="text-[var(--fp-subtle)]"/><CountryFlag code={lastCalc.to_country}/><span>{lastCalc.to_country}</span><span className="ml-auto rounded-lg bg-[var(--fp-green-soft)] px-2.5 py-1 text-[14px] font-semibold text-[var(--fp-green)]">{lastCalc.currency}</span></div><div className="mt-5 grid grid-cols-3 gap-3"><RouteStat label={t.routes.sending} value={money(lastCalc.amount,lastCalc.currency,lang)}/><RouteStat label={lang==='ru'?'Лучшая комиссия':'Best fee'} value={money(lastCalc.best_fee,lastCalc.currency,lang)}/><RouteStat label={lang==='ru'?'Срок':'Delivery'} value={speedLabel(lastCalc.best_speed_minutes,lang)}/></div><div className="relative mt-5 h-[112px] overflow-hidden rounded-[14px] border border-[var(--fp-border)] bg-[linear-gradient(180deg,#fafbf8,#f5f8f5)]"><div className="absolute inset-x-12 top-1/2 border-t border-dashed border-[#a8c7b0]"/><span className="absolute left-7 top-1/2 grid size-10 -translate-y-1/2 place-items-center rounded-full border border-[#acd0b5] bg-white text-[14px] font-bold text-[var(--fp-green)] shadow-sm">{lastCalc.from_country}</span><span className="absolute right-7 top-1/2 grid size-10 -translate-y-1/2 place-items-center rounded-full border border-[#acd0b5] bg-white text-[14px] font-bold text-[var(--fp-green)] shadow-sm">{lastCalc.to_country}</span><span className="absolute left-[48%] top-[calc(50%-5px)] size-2.5 rounded-full bg-[var(--fp-green)] shadow-[0_0_0_6px_rgba(24,122,69,.10)] animate-[fp-pulse_1.8s_ease-in-out_infinite]"/></div></div>:<div className="mt-5"><EmptyState title={t.overview.noRoutes} description={lang==='ru'?'Сравните направление один раз — FlowPay сохранит результат и будет показывать его здесь.':'Compare a corridor once and FlowPay will keep the latest result here.'}/><div className="mt-3 flex justify-center"><Link href="/routes" className={cn(buttonVariants({variant:'secondary',size:'sm'}))}>{lang==='ru'?'Сравнить маршрут':'Compare a route'}<ArrowRight size={14}/></Link></div></div>}</Card>

      <Card className="p-5 sm:p-6"><SectionTitle title={t.overview.compare} action={t.common.viewAll} href="/routes" subtitle={lang==='ru'?'Лучшие варианты из последнего расчёта':'Top options from your latest comparison'}/>{lastRoutes.length?<div className="mt-5 space-y-2.5">{lastRoutes.map((r,i)=><div key={r.id} className={cn('grid grid-cols-[34px_1fr_auto] items-center gap-3 rounded-[13px] border p-3.5',i===0?'border-[#c8dfce] bg-[#f4f9f5]':'border-[var(--fp-border)] bg-[#fbfcfa]')}><span className={i===0?'grid size-8 place-items-center rounded-full bg-[var(--fp-green)] text-[14px] font-bold text-white':'grid size-8 place-items-center rounded-full bg-[#eef1ed] text-[14px] font-bold text-[var(--fp-muted)]'}>{i+1}</span><div className="min-w-0"><div className="flex items-center gap-2"><strong className="block truncate text-[14px]">{r.providerName}</strong>{i===0&&<span className="rounded-md bg-white px-1.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-[var(--fp-green)]">{t.routes.best}</span>}</div><span className="mt-1 block text-[14px] text-[var(--fp-muted)]">{speedLabel(r.speedMinutes,lang)} · FlowScore {r.score}</span></div><div className="text-right"><strong className={cn('block text-[14px]',i===0&&'text-[var(--fp-green)]')}>{lastCalc?.currency?money(r.fee,lastCalc.currency,lang):'—'}</strong><span className="mt-1 block text-[14px] text-[var(--fp-muted)]">{lang==='ru'?'комиссия':'fee'}</span></div></div>)}</div>:<div className="mt-5"><EmptyState compact title={t.routes.noRoutes}/></div>}</Card>
    </div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[.78fr_.78fr_1.44fr]">
      <Card className="p-5 sm:p-6"><SectionTitle title={t.overview.upcoming} action={t.common.viewAll} href="/payments"/>{upcoming.length?<div className="mt-4 space-y-1">{upcoming.map(p=><Link key={p.id} href={`/payments?selected=${p.id}`} className="flex items-center gap-3 rounded-[11px] px-2 py-3 transition hover:bg-[#f7f9f6]"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#eef2ed] text-[14px] font-bold">{p.supplier_name.slice(0,1).toUpperCase()}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[14px]">{p.supplier_name}</strong><small className="mt-0.5 block text-[14px] text-[var(--fp-muted)]">{money(p.amount,p.currency,lang)}</small></span><span className="text-right text-[14px] text-[var(--fp-muted)]">{relativeDate(p.due_date,lang)}</span></Link>)}</div>:<div className="mt-4"><EmptyState compact title={lang==='ru'?'Нет ближайших платежей':'No upcoming payments'} description={lang==='ru'?'Создайте платёж и укажите срок оплаты — он появится здесь.':'Create a payment with a due date and it will appear here.'}/></div>}</Card>
      <Card className="p-5 sm:p-6"><SectionTitle title={t.overview.topCounterparties} action={t.common.viewAll} href="/counterparties"/>{topCounterparties.length?<div className="mt-4 space-y-1">{topCounterparties.map((cp,i)=><div key={`${cp.name}-${i}`} className="flex items-center gap-3 rounded-[11px] px-2 py-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#f0f1ee] text-[14px] font-bold text-[var(--fp-muted)]">{i+1}</span><span className="min-w-0 flex-1"><strong className="flex items-center gap-2 truncate text-[14px]"><CountryFlag code={cp.country}/>{cp.name}</strong><small className="mt-0.5 block text-[14px] text-[var(--fp-muted)]">{cp.count} {copy.common.payments.toLowerCase()}</small></span><strong className="text-[14px]">{base?money(cp.value,base,lang,true):`${cp.count}×`}</strong></div>)}</div>:<div className="mt-4"><EmptyState compact title={lang==='ru'?'История контрагентов пока пуста':'No counterparty history yet'} description={lang==='ru'?'После завершённых платежей здесь появятся основные получатели.':'Your top beneficiaries will appear after settled payments.'}/></div>}</Card>
      <Card className="p-5 sm:p-6"><SectionTitle title={t.overview.activity} action={t.common.viewAll} href="/payments"/>{recent.length?<div className="mt-4 divide-y divide-[var(--fp-border)]">{recent.map(p=><Link href={`/payments?selected=${p.id}`} key={p.id} className="flex items-center gap-3 py-3.5"><span className="grid size-9 place-items-center rounded-[11px] bg-[#f2f5f1] text-[var(--fp-green)]"><CircleDollarSign size={16}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-[14px]">{p.supplier_name}</strong><p className="mt-0.5 text-[14px] text-[var(--fp-muted)]">{money(p.amount,p.currency,lang)} · {relativeDate(p.updated_at,lang)}</p></span><StatusBadge status={p.status}/></Link>)}</div>:<div className="mt-4"><EmptyState compact title={t.overview.noPayments}/></div>}</Card>
    </div>

    <div className="mt-4 grid gap-4 lg:grid-cols-3">
      {base?<Card className="p-5 sm:p-6"><SectionTitle title={lang==='ru'?'Рыночные курсы':'Market rates'} subtitle={lang==='ru'?`Относительно ${base}`:`Against ${base}`}/><div className="mt-5 space-y-3.5">{baseRates.length?baseRates.map(code=><div key={code} className="flex items-center justify-between"><span className="text-[14px] font-medium">{code} → {base}</span><span className="font-mono text-[14px] text-[var(--fp-muted)]">{fx.rates[code].toFixed(4)}</span></div>):<p className="py-5 text-center text-[14px] text-[var(--fp-muted)]">{fx.loading?t.common.loading:t.common.noData}</p>}</div>{fx.date&&<p className="mt-5 border-t border-[var(--fp-border)] pt-3 text-[14px] text-[var(--fp-subtle)]">{lang==='ru'?'Справочный курс':'Reference rate'} · {fx.date}</p>}</Card>:<Card className="p-5 sm:p-6"><SectionTitle title={lang==='ru'?'Статусы платежей':'Payment pipeline'} subtitle={lang==='ru'?'Текущая загрузка по этапам':'Current workload by stage'}/><div className="mt-5 grid grid-cols-2 gap-3"><PipelineStat label={lang==='ru'?'Черновики':'Drafts'} value={ws.payments.filter(p=>p.status==='draft').length}/><PipelineStat label={lang==='ru'?'Готовы':'Ready'} value={ws.payments.filter(p=>p.status==='ready').length}/><PipelineStat label={lang==='ru'?'Оплачены':'Paid'} value={ws.payments.filter(p=>p.status==='paid').length}/><PipelineStat label={lang==='ru'?'Получены':'Received'} value={ws.payments.filter(p=>p.status==='received').length}/></div></Card>}
      <Card className="p-5 sm:p-6"><SectionTitle title={t.overview.health}/>{score==null?<div className="mt-4"><EmptyState compact title={t.overview.noPayments}/></div>:<div className="mt-5 flex items-center gap-5"><div className="relative grid size-28 place-items-center rounded-full" style={{background:`conic-gradient(var(--fp-green) ${clamp(score)}%, #e8ede8 0)`}}><div className="grid size-20 place-items-center rounded-full bg-white"><div className="text-center"><strong className="block text-[27px] tracking-[-.05em]">{score}</strong><span className="text-[14px] text-[var(--fp-muted)]">/100</span></div></div></div><div className="text-[14px] leading-5 text-[var(--fp-muted)]"><strong className="block text-[14px] text-[var(--fp-green)]">{score>=85?copy.common.excellent:score>=70?copy.common.good:copy.common.attention}</strong><p className="mt-1">{lang==='ru'?'Оценка учитывает статусы платежей, сроки исполнения и стоимость рассчитанных маршрутов.':'The score reflects payment statuses, delivery timelines and route costs.'}</p></div></div>}</Card>
      <Card className="p-5 sm:p-6"><SectionTitle title={lang==='ru'?'Готовность аккаунта':'Account readiness'} subtitle={lang==='ru'?'Основные шаги для ежедневной работы':'Core steps for daily operations'}/><div className="mt-5 space-y-3"><ReadinessRow done={Boolean(ws.profile?.name)} label={lang==='ru'?'Профиль компании':'Company profile'} href="/settings"/><ReadinessRow done={Boolean(base)} label={lang==='ru'?'Валюта отчётности':'Reporting currency'} href="/settings"/><ReadinessRow done={ws.counterparties.length>0} label={lang==='ru'?'Контрагенты':'Counterparties'} href="/counterparties"/><ReadinessRow done={ws.payments.length>0} label={lang==='ru'?'Первый платёж':'First payment'} href="/payments"/></div><div className="mt-5 flex items-center justify-between border-t border-[var(--fp-border)] pt-4"><span className="text-[14px] text-[var(--fp-muted)]">{lang==='ru'?'Выполнено':'Completed'}</span><strong className="text-[14px] text-[var(--fp-green)]">{readiness}/4</strong></div></Card>
    </div>
    </>}
  </div>
}

function GettingStarted({lang,hasProfile,hasBase}:{lang:string;hasProfile:boolean;hasBase:boolean}){
  const ru=lang==='ru'
  const steps=[
    {done:hasProfile&&hasBase,title:ru?'Настройте компанию':'Set up your company',sub:ru?'Укажите название, страну и валюту отчётности.':'Add company details and your reporting currency.',href:'/settings',icon:<Settings2 size={18}/>},
    {done:false,title:ru?'Добавьте контрагента':'Add a counterparty',sub:ru?'Сохраните получателя и его платёжные реквизиты.':'Save a beneficiary and payment details.',href:'/counterparties',icon:<Users size={18}/>},
    {done:false,title:ru?'Сравните и создайте платёж':'Compare and create a payment',sub:ru?'Проверьте доступные варианты, затем сохраните платёж.':'Compare available options, then create a payment.',href:'/routes',icon:<RouteIcon size={18}/>},
  ]
  return <div className="mt-5 grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
    <Card className="overflow-hidden border-[#cfe0d3] bg-[linear-gradient(135deg,#ffffff_0%,#f5faf6_70%,#edf6ef_100%)] p-6 sm:p-8">
      <span className="inline-flex items-center gap-2 rounded-full border border-[#d7e6da] bg-white/80 px-3 py-1.5 text-[12px] font-semibold text-[var(--fp-green)]"><ShieldCheck size={14}/>{ru?'Быстрый старт':'Quick start'}</span>
      <h2 className="mt-5 max-w-2xl text-[26px] font-semibold leading-[1.12] tracking-[-.045em] sm:text-[30px]">{ru?'Подготовьте FlowPay к первому международному платежу':'Prepare FlowPay for your first international payment'}</h2>
      <p className="mt-3 max-w-2xl text-[14px] leading-6 text-[var(--fp-muted)]">{ru?'Начните с основных настроек. После первых операций обзор автоматически наполнится объёмами, сроками, экономией и динамикой.':'Complete the essentials first. Once activity starts, this overview will automatically show volume, timing, savings and trends.'}</p>
      <div className="mt-7 grid gap-3 lg:grid-cols-3">{steps.map((step,index)=><Link key={step.title} href={step.href} className="group rounded-[15px] border border-[#dfe7df] bg-white/90 p-4 shadow-[0_1px_2px_rgba(17,35,22,.02)] transition hover:-translate-y-0.5 hover:border-[#c8dbcde6] hover:shadow-[0_12px_30px_rgba(24,65,38,.07)]"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-[12px] bg-[var(--fp-green-soft)] text-[var(--fp-green)]">{step.done?<CheckCircle2 size={18}/>:step.icon}</span><span className="text-[12px] font-semibold text-[var(--fp-subtle)]">0{index+1}</span></div><strong className="mt-4 block text-[15px]">{step.title}</strong><p className="mt-1.5 text-[14px] leading-5 text-[var(--fp-muted)]">{step.sub}</p><span className="mt-4 inline-flex items-center gap-1.5 text-[14px] font-semibold text-[var(--fp-green)]">{step.done?(ru?'Проверить':'Review'):(ru?'Продолжить':'Continue')}<ArrowRight size={13} className="transition group-hover:translate-x-0.5"/></span></Link>)}</div>
    </Card>
    <Card className="p-6 sm:p-7"><SectionTitle title={ru?'Что появится в обзоре':'What will appear here'} subtitle={ru?'Только фактические данные ваших операций':'Only your actual account activity'}/><div className="mt-5 space-y-4"><Benefit icon={<CircleDollarSign size={16}/>} title={ru?'Объём и экономия':'Volume and savings'} text={ru?'Сводка по завершённым платежам и сравнениям маршрутов.':'Summary of settled payments and route comparisons.'}/><Benefit icon={<Clock3 size={16}/>} title={ru?'Сроки и контроль':'Timing and control'} text={ru?'Ближайшие, просроченные и завершённые платежи.':'Upcoming, overdue and completed payments.'}/><Benefit icon={<Activity size={16}/>} title={ru?'Динамика':'Performance trends'} text={ru?'Графики объёма, комиссий и эффективности по периодам.':'Charts for volume, fees and efficiency over time.'}/></div></Card>
  </div>
}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-[11px] bg-[#f0f5f0] text-[var(--fp-green)]">{icon}</span><div><strong className="block text-[14px]">{title}</strong><p className="mt-1 text-[14px] leading-5 text-[var(--fp-muted)]">{text}</p></div></div>}

function AttentionRow({href,icon,tone,title,sub}:{href:string;icon:React.ReactNode;tone:'danger'|'warning'|'neutral';title:string;sub:string}){const cls=tone==='danger'?'bg-[var(--fp-red-soft)] text-[var(--fp-red)]':tone==='warning'?'bg-[var(--fp-amber-soft)] text-[var(--fp-amber)]':'bg-[#f1f5f1] text-[var(--fp-green)]';return <Link href={href} className="fp-attention-row"><span className={cn('grid size-9 shrink-0 place-items-center rounded-[11px]',cls)}>{icon}</span><span className="min-w-0 flex-1"><strong className="block text-[14px]">{title}</strong><small className="mt-0.5 block text-[14px] text-[var(--fp-muted)]">{sub}</small></span><ArrowRight size={14} className="text-[var(--fp-subtle)]"/></Link>}
function RouteStat({label,value}:{label:string;value:string}){return <div className="rounded-[12px] bg-[#f6f8f5] p-3"><span className="text-[14px] font-medium text-[var(--fp-muted)]">{label}</span><strong className="mt-1 block truncate text-[15px]">{value}</strong></div>}
function PipelineStat({label,value}:{label:string;value:number}){return <div className="rounded-[12px] border border-[var(--fp-border)] bg-[#fafbf8] p-3.5"><span className="text-[13px] font-medium text-[var(--fp-muted)]">{label}</span><strong className="mt-1 block text-[22px] tracking-[-.04em]">{value}</strong></div>}
function ReadinessRow({done,label,href}:{done:boolean;label:string;href:string}){return <Link href={href} className="flex items-center gap-3 rounded-[10px] px-1 py-1.5"><span className={cn('grid size-6 place-items-center rounded-full',done?'bg-[var(--fp-green-soft)] text-[var(--fp-green)]':'bg-[#f0f1ee] text-[var(--fp-subtle)]')}>{done?<CheckCircle2 size={14}/>:<span className="size-1.5 rounded-full bg-current"/>}</span><span className="flex-1 text-[14px] font-medium">{label}</span><ArrowRight size={13} className="text-[var(--fp-subtle)]"/></Link>}
