'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { AlertTriangle, CalendarDays, CheckSquare2, Clock3, Download, FileCheck2, History, Pencil, Plus, RefreshCw, Search, ShieldCheck, Trash2, WalletCards } from 'lucide-react'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { workspaceDictionaries } from '@/lib/workspace-i18n'
import { workspaceCopy } from '@/lib/workspace-copy'
import { useFxMap } from '@/hooks/use-fx-map'
import { dayDiff, isOutstanding, isSettled, money, normalize, providerLabel, relativeDate } from '@/lib/metrics'
import { PageHeader, MetricCard, EmptyState, StatusBadge } from '@/components/workspace/primitives'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SelectMenu } from '@/components/ui/select-menu'
import { Card } from '@/components/ui/card'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { createClient } from '@/lib/supabase/client'
import type { PaymentDraft } from '@/lib/types'
import { cn } from '@/lib/utils'
import { userError } from '@/lib/user-error'

type StatusFilter='all'|'draft'|'ready'|'paid'|'received'|'failed'|'cancelled'
type Focus='all'|'due'|'overdue'|'approval'|'reconcile'
const statusFilters:StatusFilter[]=['all','draft','ready','paid','received','failed','cancelled']

export default function PaymentsPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const ru=lang==='ru';const t=workspaceDictionaries[lang];const copy=workspaceCopy[lang];const params=useSearchParams();const router=useRouter()
  const [statusFilter,setStatusFilter]=useState<StatusFilter>('all');const [focus,setFocus]=useState<Focus>('all');const [query,setQuery]=useState('');const [selectedId,setSelectedId]=useState<string|null>(null);const [selectedIds,setSelectedIds]=useState<Set<string>>(new Set());const [working,setWorking]=useState(false);const [notice,setNotice]=useState('')
  useEffect(()=>{if(params.get('new')==='1')router.replace('/payments/new');const id=params.get('selected');if(id)setSelectedId(id)},[params,router])
  const providerNames=useMemo(()=>new Map(ws.providerRules.map(r=>[r.provider_code,r.display_name||providerLabel(r.provider_code)])),[ws.providerRules])
  const base=ws.profile?.preferred_currency||null;const currencies=useMemo(()=>Array.from(new Set(ws.payments.map(p=>p.currency))),[ws.payments]);const fx=useFxMap(base,currencies)
  const now=new Date();const monthStart=new Date(now.getFullYear(),now.getMonth(),1);const monthEnd=new Date(now.getFullYear(),now.getMonth()+1,1)
  const sum=(rows:PaymentDraft[])=>base?rows.reduce((s,p)=>s+(normalize(Number(p.amount),p.currency,base,fx.rates)||0),0):null
  const dueWeek=ws.payments.filter(isOutstanding).filter(p=>{const d=dayDiff(p.due_date);return d!=null&&d>=0&&d<=7});const ready=ws.payments.filter(p=>p.status==='ready');const overdue=ws.payments.filter(isOutstanding).filter(p=>{const d=dayDiff(p.due_date);return d!=null&&d<0});const monthSettled=ws.payments.filter(isSettled).filter(p=>{const d=new Date(p.received_at||p.paid_at||p.updated_at);return d>=monthStart&&d<monthEnd})
  const approvalQueue=ws.payments.filter(p=>['required','pending','rejected'].includes(p.approval_status))
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return ws.payments.filter(p=>{if(statusFilter!=='all'&&p.status!==statusFilter)return false;if(focus==='due'){const d=dayDiff(p.due_date);if(!(isOutstanding(p)&&d!=null&&d>=0&&d<=7))return false}else if(focus==='overdue'){const d=dayDiff(p.due_date);if(!(isOutstanding(p)&&d!=null&&d<0))return false}else if(focus==='approval'&&!['required','pending','rejected'].includes(p.approval_status))return false;else if(focus==='reconcile'&&!['unmatched','needs_review'].includes(p.reconciliation_status))return false;return !q||`${p.invoice_number} ${p.supplier_name} ${p.route_provider_code||''} ${p.reference}`.toLowerCase().includes(q)})},[ws.payments,statusFilter,focus,query])
  const selected=ws.payments.find(p=>p.id===selectedId)||null;const selectedCp=selected?.counterparty_id?ws.counterparties.find(c=>c.id===selected.counterparty_id):null;const timeline=selected?ws.paymentEvents.filter(e=>e.payment_id===selected.id).slice(0,10):[]
  const chosen=ws.payments.filter(p=>selectedIds.has(p.id));const allChosen=filtered.length>0&&filtered.every(p=>selectedIds.has(p.id));const canReady=chosen.length>0&&chosen.every(p=>['draft','failed'].includes(p.status)&&!['required','pending','rejected'].includes(p.approval_status));const canPaid=chosen.length>0&&chosen.every(p=>p.status==='ready'&&!['required','pending','rejected'].includes(p.approval_status));const canCancel=chosen.length>0&&chosen.every(p=>['draft','ready','failed'].includes(p.status))

  function editPayment(p:PaymentDraft){router.push(`/payments/${p.id}/edit`)}
  function toggle(id:string){setSelectedIds(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
  function toggleAll(){setSelectedIds(current=>{const next=new Set(current);if(allChosen)for(const p of filtered)next.delete(p.id);else for(const p of filtered)next.add(p.id);return next})}
  async function setStatus(payment:PaymentDraft,status:'ready'|'paid'|'received'|'cancelled'|'failed'){setWorking(true);setNotice('');const {error}=await createClient().rpc('flowpay_set_payment_status',{p_payment_id:payment.id,p_status:status});setWorking(false);if(error){setNotice(String(error.message||'').includes('PAYMENT_APPROVAL')?(ru?'Сначала завершите согласование платежа.':'Complete the payment approval first.'):userError(lang,'payment'));return}await ws.refresh()}
  async function bulkStatus(status:'ready'|'paid'|'cancelled'){if(!chosen.length)return;setWorking(true);setNotice('');const {error}=await createClient().rpc('flowpay_bulk_set_payment_status',{p_payment_ids:chosen.map(p=>p.id),p_status:status});setWorking(false);if(error){setNotice(ru?'Не удалось применить действие ко всей выборке. Изменения отменены, проверьте статусы и согласования.':'The bulk action could not be applied to the full selection. Changes were rolled back; check statuses and approvals.');return}setSelectedIds(new Set());await ws.refresh()}
  async function setPriority(payment:PaymentDraft,priority:PaymentDraft['priority']){setWorking(true);setNotice('');const {error}=await createClient().rpc('flowpay_update_payment_priority',{p_payment_id:payment.id,p_priority:priority});setWorking(false);if(error){setNotice(userError(lang,'save'));return}await ws.refresh()}
  async function deletePayment(payment:PaymentDraft){if(payment.status!=='draft')return;if(!window.confirm(ru?'Удалить этот черновик платежа?':'Delete this payment draft?'))return;setWorking(true);const {error}=await createClient().rpc('flowpay_delete_payment_draft',{p_payment_id:payment.id});setWorking(false);if(error){setNotice(userError(lang,'delete'));return}setSelectedId(null);setSelectedIds(c=>{const n=new Set(c);n.delete(payment.id);return n});await ws.refresh()}
  function exportCsv(){const rows=filtered.map(p=>[p.invoice_number,p.supplier_name,p.amount,p.currency,p.status,p.priority,p.due_date||'',p.route_provider_code||'',p.reconciliation_status]);const content='Invoice,Supplier,Amount,Currency,Status,Priority,Due,Route,Reconciliation\n'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='flowpay-payments.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}

  return <div className="fp-enter"><PageHeader title={ru?'Платежи':'Payments'} subtitle={ru?'Главный рабочий список: подготовьте платёж, выберите вариант, пройдите согласование и отслеживайте результат.':'Your main worklist: prepare a payment, select an option, complete controls and track the result.'} actions={<Button onClick={()=>router.push('/payments/new')}><Plus size={16}/>{t.payments.create}</Button>}/>
    {notice&&<div className="mb-4 rounded-[11px] bg-[var(--fp-red-soft)] p-3 text-[13px] text-[var(--fp-red)]">{notice}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={ru?'К оплате за 7 дней':'Due in 7 days'} value={base?money(sum(dueWeek),base,lang,true):String(dueWeek.length)} meta={`${dueWeek.length} ${ru?'платежей':'payments'}`} icon={<CalendarDays size={16}/>}/><MetricCard label={ru?'Готовы к оплате':'Ready to pay'} value={base?money(sum(ready),base,lang,true):String(ready.length)} meta={`${ready.length} ${ru?'платежей':'payments'}`} icon={<Clock3 size={16}/>}/><MetricCard label={ru?'Просрочено':'Overdue'} value={base?money(sum(overdue),base,lang,true):String(overdue.length)} meta={`${overdue.length} ${ru?'требуют внимания':'need attention'}`} icon={<AlertTriangle size={16}/>} className={overdue.length?'[&_strong]:text-[var(--fp-red)]':''}/><MetricCard label={ru?'Оплачено за месяц':'Settled this month'} value={base?money(sum(monthSettled),base,lang,true):String(monthSettled.length)} meta={t.common.thisMonth} icon={<WalletCards size={16}/>}/></div>

    <Card className="mt-4 overflow-hidden"><div className="border-b border-[var(--fp-border)] p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="flex h-11 min-w-0 flex-1 items-center gap-2 rounded-[10px] border border-[var(--fp-border)] bg-white px-3"><Search size={15} className="text-[var(--fp-subtle)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ru?'Поставщик, счёт, reference или провайдер…':'Supplier, invoice, reference or provider…'} className="w-full bg-transparent text-[14px] outline-none placeholder:text-[var(--fp-subtle)]"/></label><div className="flex flex-wrap gap-2"><SelectMenu value={statusFilter} onChange={v=>setStatusFilter(v as StatusFilter)} options={statusFilters.map(v=>({value:v,label:v==='all'?(ru?'Все статусы':'All statuses'):statusName(v,ru)}))}/><Button variant="secondary" size="sm" onClick={exportCsv}><Download size={14}/>{t.common.export}</Button></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><span className="mr-1 text-[11px] font-semibold uppercase tracking-[.08em] text-[var(--fp-subtle)]">{ru?'Быстрый фокус':'Quick focus'}</span>{([{key:'all',ru:'Все',en:'All'},{key:'due',ru:'К оплате',en:'Due soon'},{key:'overdue',ru:'Просрочено',en:'Overdue'},{key:'approval',ru:'Нужно решение',en:'Needs approval'},{key:'reconcile',ru:'На сверке',en:'Reconcile'}] as {key:Focus;ru:string;en:string}[]).map(item=><button key={item.key} onClick={()=>setFocus(item.key)} className={cn('rounded-full border px-3 py-1.5 text-[12px] font-semibold transition',focus===item.key?'border-[#bfd4c4] bg-[var(--fp-green-soft)] text-[var(--fp-green-strong)]':'border-[var(--fp-border)] bg-white text-[var(--fp-muted)] hover:bg-[var(--fp-surface-muted)]')}>{ru?item.ru:item.en}</button>)}</div></div>
      {selectedIds.size>0&&<div className="flex flex-col gap-3 border-b border-[#cfe0d3] bg-[#f3f8f4] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-[13px]"><CheckSquare2 size={15} className="text-[var(--fp-green)]"/><strong>{selectedIds.size}</strong><span className="text-[var(--fp-muted)]">{ru?'выбрано':'selected'}</span></div><div className="flex flex-wrap gap-2">{canReady&&<Button size="sm" disabled={working} onClick={()=>bulkStatus('ready')}>{ru?'Готовы к оплате':'Mark ready'}</Button>}{canPaid&&<Button size="sm" disabled={working} onClick={()=>bulkStatus('paid')}>{ru?'Отметить оплаченными':'Mark paid'}</Button>}{canCancel&&<Button variant="secondary" size="sm" disabled={working} onClick={()=>bulkStatus('cancelled')}>{ru?'Отменить':'Cancel'}</Button>}<Button variant="ghost" size="sm" onClick={()=>setSelectedIds(new Set())}>{ru?'Снять выбор':'Clear'}</Button></div></div>}
      <div className="grid min-h-[520px] xl:grid-cols-[minmax(0,1fr)_390px]"><div className="overflow-x-auto border-b border-[var(--fp-border)] xl:border-b-0 xl:border-r"><table className="w-full min-w-[850px] border-collapse text-left text-[13px]"><thead className="bg-[#fafbf8] text-[11px] font-semibold uppercase tracking-[.06em] text-[var(--fp-subtle)]"><tr><th className="w-10 px-4 py-3"><input type="checkbox" checked={allChosen} onChange={toggleAll} aria-label={ru?'Выбрать всё':'Select all'}/></th><th className="px-3 py-3">{ru?'Поставщик':'Supplier'}</th><th className="px-3 py-3">{ru?'Сумма':'Amount'}</th><th className="px-3 py-3">{ru?'Срок':'Due'}</th><th className="px-3 py-3">{ru?'Приоритет':'Priority'}</th><th className="px-3 py-3">{ru?'Статус':'Status'}</th><th className="px-3 py-3">{ru?'Контроль':'Control'}</th></tr></thead><tbody className="divide-y divide-[var(--fp-border)]">{filtered.map(p=>{const cp=p.counterparty_id?ws.counterparties.find(c=>c.id===p.counterparty_id):null;const overdueFlag=isOutstanding(p)&&(dayDiff(p.due_date)||0)<0;return <tr key={p.id} onClick={()=>setSelectedId(p.id)} className={cn('cursor-pointer transition hover:bg-[#fafbf8]',selectedId===p.id&&'bg-[#f3f8f4]')}><td className="px-4 py-3" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selectedIds.has(p.id)} onChange={()=>toggle(p.id)} aria-label={ru?'Выбрать платёж':'Select payment'}/></td><td className="px-3 py-3"><span className="flex items-center gap-2"><CountryFlag code={cp?.country||p.route_to_country}/><span className="min-w-0"><strong className="block max-w-[190px] truncate text-[13px]">{p.supplier_name}</strong><small className="block max-w-[190px] truncate text-[11px] text-[var(--fp-muted)]">{p.invoice_number||p.reference||'—'}</small></span></span></td><td className="px-3 py-3 font-semibold">{money(p.amount,p.currency,lang)}</td><td className={cn('px-3 py-3 text-[var(--fp-muted)]',overdueFlag&&'font-semibold text-[var(--fp-red)]')}>{relativeDate(p.due_date,lang)}</td><td className="px-3 py-3"><PriorityBadge priority={p.priority} ru={ru}/></td><td className="px-3 py-3"><StatusBadge status={overdueFlag?'overdue':p.status}/></td><td className="px-3 py-3"><div className="flex flex-wrap gap-1"><StatusBadge status={p.approval_status}/>{['paid','received'].includes(p.status)&&<StatusBadge status={p.reconciliation_status}/>}</div></td></tr>})}</tbody></table>{filtered.length===0&&<div className="p-5"><EmptyState title={ws.payments.length?(ru?'По этому фильтру ничего нет':'No payments match this view'):(ru?'Создайте первый платёж':'Create your first payment')} description={ru?'Используйте быстрые фильтры сверху или создайте новый платёж.':'Use the quick filters above or create a new payment.'} actionLabel={ru?'Новый платёж':'New payment'} onAction={()=>router.push('/payments/new')}/></div>}</div>
        <aside className="p-5 sm:p-6">{selected?<><div className="flex items-start justify-between gap-3"><div><span className="text-[11px] font-semibold uppercase tracking-[.08em] text-[var(--fp-subtle)]">{selected.invoice_number||(ru?'Платёж':'Payment')}</span><h2 className="mt-1 text-[18px] font-semibold tracking-[-.025em]">{selected.supplier_name}</h2><p className="mt-1 text-[13px] text-[var(--fp-muted)]">{money(selected.amount,selected.currency,lang)}</p></div><StatusBadge status={selected.status}/></div>
          <div className="mt-5 grid gap-3"><Info label={ru?'Маршрут':'Route'} value={selected.route_from_country&&selected.route_to_country?`${selected.route_from_country} → ${selected.route_to_country}`:'—'}/><Info label={ru?'Провайдер':'Provider'} value={selected.route_provider_code?(providerNames.get(selected.route_provider_code)||providerLabel(selected.route_provider_code)):'—'}/><Info label={ru?'Срок':'Due date'} value={relativeDate(selected.due_date,lang)}/><Info label="Reference" value={selected.reference||'—'}/></div>
          <div className="mt-4 rounded-[12px] border border-[var(--fp-border)] bg-[#f8faf7] p-3"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[13px] font-semibold"><ShieldCheck size={14} className="text-[var(--fp-green)]"/>{ru?'Согласование':'Approval'}</span><StatusBadge status={selected.approval_status}/></div>{['required','pending','rejected'].includes(selected.approval_status)&&<Button variant="secondary" size="sm" className="mt-3 w-full" onClick={()=>router.push(`/approvals?payment=${selected.id}`)}><FileCheck2 size={14}/>{ru?'Открыть согласование':'Open approval'}</Button>}</div>
          {['paid','received'].includes(selected.status)&&<div className="mt-3 rounded-[12px] border border-[var(--fp-border)] bg-[#f8faf7] p-3"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-[13px] font-semibold"><RefreshCw size={14} className="text-[var(--fp-green)]"/>{ru?'Сверка':'Reconciliation'}</span><StatusBadge status={selected.reconciliation_status}/></div><Button variant="secondary" size="sm" className="mt-3 w-full" onClick={()=>router.push('/reconciliation')}><RefreshCw size={14}/>{ru?'Сверить платёж':'Reconcile payment'}</Button></div>}
          <div className="mt-4"><label className="text-[12px] font-semibold text-[var(--fp-muted)]">{ru?'Приоритет':'Priority'}</label><SelectMenu value={selected.priority} onChange={v=>setPriority(selected,v as PaymentDraft['priority'])} options={[{value:'low',label:ru?'Низкий':'Low'},{value:'normal',label:ru?'Обычный':'Normal'},{value:'high',label:ru?'Высокий':'High'},{value:'urgent',label:ru?'Срочный':'Urgent'}]}/></div>
          <div className="mt-4 grid grid-cols-2 gap-2">{selected.status==='draft'&&!['required','pending','rejected'].includes(selected.approval_status)&&<Button disabled={working} onClick={()=>setStatus(selected,'ready')}>{ru?'Готов к оплате':'Mark ready'}</Button>}{selected.status==='ready'&&!['required','pending','rejected'].includes(selected.approval_status)&&<Button disabled={working} onClick={()=>setStatus(selected,'paid')}>{ru?'Оплачен':'Mark paid'}</Button>}{selected.status==='paid'&&<Button disabled={working} onClick={()=>setStatus(selected,'received')}>{ru?'Получен':'Mark received'}</Button>}{['draft','ready','failed'].includes(selected.status)&&<Button variant="secondary" disabled={working} onClick={()=>setStatus(selected,'cancelled')}>{ru?'Отменить':'Cancel'}</Button>}{['draft','ready'].includes(selected.status)&&<Button variant="secondary" onClick={()=>editPayment(selected)}><Pencil size={13}/>{ru?'Изменить':'Edit'}</Button>}{selected.status==='draft'&&<Button variant="ghost" onClick={()=>deletePayment(selected)}><Trash2 size={13}/>{ru?'Удалить':'Delete'}</Button>}</div>
          <div className="mt-5 border-t border-[var(--fp-border)] pt-4"><div className="flex items-center gap-2 text-[12px] font-semibold text-[var(--fp-muted)]"><History size={14}/>{ru?'История платежа':'Payment timeline'}</div><div className="mt-3 space-y-3">{timeline.length?timeline.map(e=><div key={e.id} className="flex gap-3"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-[var(--fp-green)]"/><div className="min-w-0"><strong className="block text-[12px]">{eventName(e.event,e.from_value,e.to_value,ru)}</strong><small className="text-[11px] text-[var(--fp-subtle)]">{relativeDate(e.created_at,lang)}</small></div></div>):<p className="text-[12px] text-[var(--fp-subtle)]">{ru?'История появится после обновления базы до 2.1.':'Timeline appears after the 2.1 database migration.'}</p>}</div></div>
        </>:<EmptyState compact title={ru?'Выберите платёж':'Select a payment'} description={ru?'Справа появятся детали, контроль, приоритет и история.':'Details, controls, priority and history will appear here.'}/>}</aside>
      </div></Card>
  </div>
}

function Info({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-3 border-b border-[var(--fp-border)] pb-2.5 text-[13px]"><span className="text-[var(--fp-muted)]">{label}</span><strong className="max-w-[210px] text-right font-medium">{value}</strong></div>}
function PriorityBadge({priority,ru}:{priority:PaymentDraft['priority'];ru:boolean}){const labels={low:ru?'Низкий':'Low',normal:ru?'Обычный':'Normal',high:ru?'Высокий':'High',urgent:ru?'Срочный':'Urgent'};return <span className={cn('rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-[.04em]',priority==='urgent'?'bg-[var(--fp-red-soft)] text-[var(--fp-red)]':priority==='high'?'bg-[var(--fp-amber-soft)] text-[var(--fp-amber)]':'bg-[#f0f2ef] text-[var(--fp-muted)]')}>{labels[priority]}</span>}
function statusName(value:StatusFilter,ru:boolean){const map:Record<Exclude<StatusFilter,'all'>,[string,string]>={draft:['Черновики','Draft'],ready:['Готовы','Ready'],paid:['Оплачены','Paid'],received:['Получены','Received'],failed:['Ошибки','Failed'],cancelled:['Отменены','Cancelled']};const row=map[value as Exclude<StatusFilter,'all'>];return ru?row[0]:row[1]}
function eventName(event:string,from:string|null,to:string|null,ru:boolean){if(event==='created')return ru?'Платёж создан':'Payment created';if(event==='status_changed')return ru?`Статус: ${from||'—'} → ${to||'—'}`:`Status: ${from||'—'} → ${to||'—'}`;if(event==='approval_changed')return ru?`Согласование: ${from||'—'} → ${to||'—'}`:`Approval: ${from||'—'} → ${to||'—'}`;if(event==='reconciliation_changed')return ru?`Сверка: ${from||'—'} → ${to||'—'}`:`Reconciliation: ${from||'—'} → ${to||'—'}`;if(event==='priority_changed')return ru?`Приоритет: ${from||'—'} → ${to||'—'}`:`Priority: ${from||'—'} → ${to||'—'}`;return ru?'Платёж обновлён':'Payment updated'}
