'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, Building2, CheckCircle2, Globe2, Loader2, WalletCards } from 'lucide-react'
import { FlowPayLogo } from '@/components/brand/FlowPayLogo'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SearchSelect } from '@/components/ui/search-select'
import { useLanguage } from '@/components/LanguageContext'
import { countryOptions, currencyOptions, defaultCurrencyForCountry } from '@/lib/countries'
import { createClient } from '@/lib/supabase/client'

const copy={
  ru:{eyebrow:'Настройка аккаунта',title:'Подготовим FlowPay к работе',sub:'Три базовых параметра нужны для корректных валют, отчётности и платежных направлений.',company:'Название компании',companyPh:'ООО / компания',country:'Страна компании',currency:'Базовая валюта',hint:'Её можно изменить позже в настройках.',button:'Продолжить в FlowPay',saving:'Сохраняем…',error:'Не удалось сохранить настройки. Попробуйте ещё раз.',steps:['Компания','Регион','Отчётность'],safe:'Настройки применяются только к вашему аккаунту.'},
  en:{eyebrow:'Account setup',title:'Set up FlowPay for your business',sub:'Three details let us configure reporting, currencies and relevant payment corridors.',company:'Company name',companyPh:'Your company',country:'Company country',currency:'Reporting currency',hint:'You can change this later in Settings.',button:'Continue to FlowPay',saving:'Saving…',error:'We could not save your settings. Please try again.',steps:['Company','Region','Reporting'],safe:'These settings apply only to your account.'},
  fr:{eyebrow:'Configuration',title:'Configurez FlowPay pour votre entreprise',sub:'Trois informations suffisent pour préparer les devises, rapports et corridors.',company:'Nom de l’entreprise',companyPh:'Votre entreprise',country:'Pays',currency:'Devise de reporting',hint:'Modifiable plus tard dans les paramètres.',button:'Continuer vers FlowPay',saving:'Enregistrement…',error:'Impossible d’enregistrer. Réessayez.',steps:['Entreprise','Région','Reporting'],safe:'Ces paramètres ne concernent que votre compte.'},
  de:{eyebrow:'Einrichtung',title:'FlowPay für Ihr Unternehmen einrichten',sub:'Drei Angaben konfigurieren Reporting, Währungen und relevante Zahlungswege.',company:'Unternehmensname',companyPh:'Ihr Unternehmen',country:'Land',currency:'Berichtswährung',hint:'Später in den Einstellungen änderbar.',button:'Weiter zu FlowPay',saving:'Speichern…',error:'Einstellungen konnten nicht gespeichert werden.',steps:['Unternehmen','Region','Reporting'],safe:'Diese Einstellungen gelten nur für Ihr Konto.'},
  es:{eyebrow:'Configuración',title:'Configura FlowPay para tu empresa',sub:'Tres datos bastan para preparar divisas, informes y rutas de pago.',company:'Nombre de empresa',companyPh:'Tu empresa',country:'País',currency:'Moneda de informes',hint:'Podrás cambiarla después en Ajustes.',button:'Continuar a FlowPay',saving:'Guardando…',error:'No se pudo guardar la configuración.',steps:['Empresa','Región','Informes'],safe:'Estos ajustes solo se aplican a tu cuenta.'},
} as const

export default function OnboardingPage(){
  const {lang}=useLanguage();const c=copy[lang];const router=useRouter();const [name,setName]=useState('');const [country,setCountry]=useState('');const [currency,setCurrency]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const countries=useMemo(()=>countryOptions(lang).map(([code,label])=>({value:code,label,description:code,leading:<CountryFlag code={code}/>})),[lang])
  const currencies=useMemo(()=>currencyOptions(lang).map(item=>({value:item.code,label:item.code,description:item.name,leading:<span className="grid size-6 place-items-center rounded-[7px] bg-[#eef4ef] text-[12px] font-semibold text-[var(--fp-green-strong)]">{item.symbol}</span>})),[lang])
  function chooseCountry(value:string){setCountry(value);const mapped=defaultCurrencyForCountry(value);if(!currency&&mapped)setCurrency(mapped)}
  async function submit(){if(name.trim().length<2||!country||!currency)return;setSaving(true);setError('');try{const client=createClient();const {data}=await client.auth.getSession();const token=data.session?.access_token;if(!token){router.replace('/login');return}const response=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({name:name.trim(),country,currency,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||''})});if(!response.ok)throw new Error('SAVE_FAILED');router.replace('/dashboard');router.refresh()}catch{setError(c.error)}finally{setSaving(false)}}
  return <main className="min-h-screen bg-[#f7f8f5] px-4 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-[1060px]"><FlowPayLogo/><div className="mt-8 grid overflow-hidden rounded-[24px] border border-[var(--fp-border)] bg-white shadow-[0_30px_90px_rgba(31,52,38,.08)] lg:grid-cols-[.78fr_1.22fr]"><aside className="border-b border-[var(--fp-border)] bg-[#eef4ef] p-7 sm:p-9 lg:border-b-0 lg:border-r"><span className="text-[12px] font-semibold uppercase tracking-[.13em] text-[var(--fp-green)]">{c.eyebrow}</span><h1 className="mt-4 text-[34px] font-semibold leading-[1.05] tracking-[-.055em] sm:text-[42px]">{c.title}</h1><p className="mt-5 max-w-md text-[15px] leading-6 text-[var(--fp-muted)]">{c.sub}</p><div className="mt-9 space-y-3">{c.steps.map((step,i)=><div key={step} className="flex items-center gap-3 rounded-[13px] border border-white/80 bg-white/70 p-3.5"><span className="grid size-8 place-items-center rounded-[9px] bg-white text-[var(--fp-green)] shadow-sm">{i===0?<Building2 size={16}/>:i===1?<Globe2 size={16}/>:<WalletCards size={16}/>}</span><strong className="text-[14px]">{step}</strong><CheckCircle2 size={15} className="ml-auto text-[#9bbca4]"/></div>)}</div></aside><section className="p-6 sm:p-9 lg:p-12"><div className="mx-auto max-w-[540px]"><h2 className="text-[23px] font-semibold tracking-[-.035em]">{c.eyebrow}</h2><div className="mt-7 space-y-5"><label className="block space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.company}</span><Input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={c.companyPh}/></label><label className="block space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.country}</span><SearchSelect value={country} onChange={chooseCountry} options={countries}/></label><label className="block space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.currency}</span><SearchSelect value={currency} onChange={setCurrency} options={currencies} variant="currency"/><small className="block text-[13px] font-normal text-[var(--fp-subtle)]">{c.hint}</small></label></div>{error&&<div className="mt-5 rounded-[12px] bg-[var(--fp-red-soft)] p-3 text-[14px] text-[var(--fp-red)]">{error}</div>}<Button size="lg" className="mt-7 w-full" disabled={saving||name.trim().length<2||!country||!currency} onClick={submit}>{saving?<Loader2 size={16} className="animate-spin"/>:<ArrowRight size={16}/>} {saving?c.saving:c.button}</Button><p className="mt-4 text-center text-[12px] text-[var(--fp-subtle)]">{c.safe}</p></div></section></div></div></main>
}
