'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Building2, Check, ChevronDown, Landmark, Loader2, Search } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { withClientTimeout } from '@/lib/client-timeout'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { cn } from '@/lib/utils'
import type { BankDirectoryEntry } from '@/lib/bank-directory'
import type { Language } from '@/lib/types'

function host(value:string|null){if(!value)return '';try{return new URL(value).hostname.replace(/^www\./,'')}catch{return ''}}
function BankMark({bank}:{bank:BankDirectoryEntry}){const [failed,setFailed]=useState(false);if(bank.logoUrl&&!failed)return <span className="grid size-9 shrink-0 place-items-center overflow-hidden rounded-[9px] border border-[#e1e7e1] bg-white p-1"><img src={bank.logoUrl} alt="" referrerPolicy="no-referrer" className="max-h-full max-w-full object-contain" onError={()=>setFailed(true)}/></span>;return <span className="grid size-9 shrink-0 place-items-center rounded-[9px] bg-[#eef4ef] text-[var(--fp-green)]"><Landmark size={16}/></span>}

export function BankSearchField({country,value,onChange,onBankSelect,lang,disabled=false}:{country:string;value:string;onChange:(value:string)=>void;onBankSelect:(bank:BankDirectoryEntry)=>void;lang:Language;disabled?:boolean}){
  const ru=lang==='ru';const root=useRef<HTMLDivElement>(null);const [open,setOpen]=useState(false);const [banks,setBanks]=useState<BankDirectoryEntry[]>([]);const [loading,setLoading]=useState(false);const [loadedCountry,setLoadedCountry]=useState('');const [degraded,setDegraded]=useState(false);const [error,setError]=useState('')
  const filtered=useMemo(()=>{const q=value.trim().toLocaleLowerCase();if(!q)return banks.slice(0,18);return banks.filter(b=>`${b.name} ${b.bic||''} ${host(b.website)}`.toLocaleLowerCase().includes(q)).slice(0,18)},[banks,value])
  useEffect(()=>{const click=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('mousedown',click);return()=>document.removeEventListener('mousedown',click)},[])
  useEffect(()=>{setBanks([]);setLoadedCountry('');setDegraded(false);setError('');if(country)void load(country)},[country])
  async function load(target=country){if(!target||loading||loadedCountry===target)return;setLoading(true);setError('');try{const client=createClient();const {data}=await withClientTimeout(client.auth.getSession(),6_000,'BANK_SESSION_TIMEOUT');const token=data.session?.access_token;if(!token)throw new Error('UNAUTHORIZED');const response=await fetch(`/api/banks?country=${encodeURIComponent(target)}&lang=${encodeURIComponent(lang)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const body=await response.json() as {banks?:BankDirectoryEntry[];degraded?:boolean};if(!response.ok)throw new Error('BANK_DIRECTORY_FAILED');setBanks(body.banks||[]);setDegraded(Boolean(body.degraded));setLoadedCountry(target)}catch{setError(ru?'Справочник банков временно недоступен. Название можно ввести вручную.':'Bank directory is temporarily unavailable. You can enter the bank name manually.')}finally{setLoading(false)}}
  return <div ref={root} className="relative"><div className={cn('flex h-12 items-center gap-2 rounded-[12px] border border-[var(--fp-border)] bg-white px-3.5 transition focus-within:border-[#8fb59b] focus-within:ring-4 focus-within:ring-[#eaf4ed]',disabled&&'bg-[#f5f6f3]')}><Building2 size={16} className="shrink-0 text-[var(--fp-green)]"/><input disabled={disabled||!country} value={value} onFocus={()=>{setOpen(true);void load()}} onChange={e=>{onChange(e.target.value);setOpen(true)}} placeholder={!country?(ru?'Сначала выберите страну банка':'Select bank country first'):(ru?'Начните вводить название банка':'Start typing a bank name')} className="min-w-0 flex-1 bg-transparent text-[15px] outline-none placeholder:text-[var(--fp-subtle)]"/><button type="button" disabled={disabled||!country} onClick={()=>{setOpen(v=>!v);void load()}} className="grid size-7 shrink-0 place-items-center text-[var(--fp-subtle)]">{loading?<Loader2 size={15} className="animate-spin"/>:<ChevronDown size={15} className={cn('transition',open&&'rotate-180')}/>}</button></div>
    {open&&country&&<div className="fp-pop absolute left-0 right-0 top-[54px] z-50 overflow-hidden rounded-[14px] border border-[#dfe4de] bg-white shadow-[0_18px_50px_rgba(18,38,25,.14)]"><div className="flex items-center gap-2 border-b border-[var(--fp-border)] bg-[#fafbf9] px-3 py-2 text-[11px] text-[var(--fp-muted)]"><Search size={13}/><span>{ru?'Банки выбранной страны':'Banks in selected country'}</span><CountryFlag code={country}/><span className="ml-auto">{banks.length}</span></div><div className="fp-scrollbar max-h-[310px] overflow-y-auto p-1.5">{filtered.length?filtered.map(bank=><button key={bank.id} type="button" onClick={()=>{onChange(bank.name);onBankSelect(bank);setOpen(false)}} className="flex w-full items-center gap-3 rounded-[10px] px-2.5 py-2.5 text-left hover:bg-[#f5f8f4]"><BankMark bank={bank}/><span className="min-w-0 flex-1"><strong className="block truncate text-[13px] font-semibold">{bank.name}</strong><small className="mt-0.5 block truncate text-[11px] text-[var(--fp-muted)]">{[bank.bic?`BIC ${bank.bic}`:null,host(bank.website)].filter(Boolean).join(' · ')||(ru?'Банковская организация':'Banking institution')}</small></span>{bank.name===value&&<span className="grid size-6 place-items-center rounded-full bg-[var(--fp-green)] text-white"><Check size={12}/></span>}</button>):<div className="px-4 py-8 text-center"><Landmark size={18} className="mx-auto text-[var(--fp-subtle)]"/><p className="mt-2 text-[12px] text-[var(--fp-muted)]">{loading?(ru?'Загружаем банки…':'Loading banks…'):(ru?'Совпадений нет. Оставьте введённое название вручную.':'No matches. Keep the typed bank name manually.')}</p></div>}</div>{(degraded||error)&&<div className="border-t border-[var(--fp-border)] px-3 py-2 text-[11px] leading-4 text-[var(--fp-subtle)]">{error||(ru?'Показан резервный проверенный список; полный каталог временно недоступен.':'Showing a curated fallback list; the full directory is temporarily unavailable.')}</div>}</div>}
    {country&&<p className="mt-1.5 text-[11px] leading-4 text-[var(--fp-subtle)]">{ru?'Поиск по реальному банковскому справочнику. BIC при наличии подставляется автоматически и остаётся редактируемым.':'Searches a real bank directory. BIC is auto-filled when available and remains editable.'}</p>}
  </div>
}
