'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Loader2, Save } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { SearchSelect } from '@/components/ui/search-select'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { useWorkspace } from './WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { countryOptions, currencyOptions, defaultCurrencyForCountry } from '@/lib/countries'
import { createClient } from '@/lib/supabase/client'
import { countryUsesIban, formatIban, isValidBic, isValidIban } from '@/lib/payment-validation'
import { workspaceCopy } from '@/lib/workspace-copy'
import { userError } from '@/lib/user-error'
import type { Counterparty } from '@/lib/types'

export function CounterpartyForm({initial=null}:{initial?:Counterparty|null}){
  const ws=useWorkspace();const {lang}=useLanguage();const router=useRouter();const c=workspaceCopy[lang].counterparty;const common=workspaceCopy[lang].common
  const [name,setName]=useState('');const [country,setCountry]=useState('');const [currency,setCurrency]=useState('');const [bankCountry,setBankCountry]=useState('');const [bankName,setBankName]=useState('');const [account,setAccount]=useState('');const [holder,setHolder]=useState('');const [bic,setBic]=useState('');const [email,setEmail]=useState('');const [taxId,setTaxId]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const countries=useMemo(()=>countryOptions(lang).map(([code,label])=>({value:code,label,description:code,leading:<CountryFlag code={code}/>})),[lang])
  const currencies=useMemo(()=>currencyOptions(lang).map(item=>({value:item.code,label:item.code,description:item.name,leading:<span className="w-5 text-center text-[14px] font-semibold">{item.symbol}</span>})),[lang])
  useEffect(()=>{setName(initial?.name??'');setCountry(initial?.country??'');setCurrency(initial?.currency??'');setBankCountry(initial?.bank_country??initial?.country??'');setBankName(initial?.bank_name??'');setAccount(initial?.account_number??'');setHolder(initial?.account_holder??'');setBic(initial?.bic??'');setEmail(initial?.email??'');setTaxId(initial?.tax_id??'');setError('')},[initial])
  function chooseCountry(code:string){setCountry(code);if(!bankCountry)setBankCountry(code);if(!initial||!currency)setCurrency(defaultCurrencyForCountry(code))}
  async function submit(event:FormEvent){event.preventDefault();if(!ws.user||!name.trim()||!country||!currency||!bankCountry)return;setError('');if(account&&countryUsesIban(bankCountry)&&!isValidIban(account)){setError(lang==='ru'?'Проверьте IBAN — контрольная сумма не совпадает.':'Please check the IBAN — its checksum is invalid.');return}if(bic&&!isValidBic(bic)){setError(lang==='ru'?'Проверьте BIC / SWIFT — формат реквизита неверный.':'Please check the BIC / SWIFT — the format is invalid.');return}setSaving(true);try{const {error}=await createClient().rpc('flowpay_upsert_counterparty',{p_counterparty_id:initial?.id||null,p_name:name.trim(),p_country:country,p_currency:currency,p_bank_country:bankCountry,p_bank_name:bankName.trim(),p_account_number:account?formatIban(account):'',p_account_holder:holder.trim(),p_bic:bic.trim().toUpperCase(),p_email:email.trim(),p_tax_id:taxId.trim()});if(error)throw error;await ws.refresh();router.push('/counterparties')}catch{setError(userError(lang,'save'))}finally{setSaving(false)}}
  const editing=Boolean(initial);const title=editing?(lang==='ru'?'Изменить контрагента':'Edit counterparty'):c.title;const description=editing?(lang==='ru'?'Обновите данные компании и платёжные реквизиты.':'Update company and payment details.'):c.description;const submitLabel=editing?(lang==='ru'?'Сохранить изменения':'Save changes'):c.create
  return <div className="fp-enter"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={()=>router.push('/counterparties')} className="mb-3 inline-flex items-center gap-2 text-[13px] font-medium text-[var(--fp-muted)] hover:text-[var(--fp-text)]"><ArrowLeft size={14}/>{lang==='ru'?'Контрагенты':'Counterparties'}</button><h1 className="text-[30px] font-semibold tracking-[-.045em]">{title}</h1><p className="mt-2 text-[14px] text-[var(--fp-muted)]">{description}</p></div><span className="rounded-full border border-[var(--fp-border)] bg-white px-3 py-1.5 text-[12px] text-[var(--fp-muted)]">{editing?(lang==='ru'?'Редактирование':'Editing'):(lang==='ru'?'Новая запись':'New record')}</span></div>
  <form onSubmit={submit} className="grid gap-4 xl:grid-cols-[1fr_.9fr]"><Card className="p-5 sm:p-6"><h2 className="text-[15px] font-semibold">{lang==='ru'?'Компания':'Company'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.company}</span><Input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.companyCountry}</span><SearchSelect value={country} onChange={chooseCountry} options={countries} placeholder={common.selectCountry}/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.preferredCurrency}</span><SearchSelect value={currency} onChange={setCurrency} options={currencies} variant="currency"/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.email}</span><Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)] sm:col-span-2"><span>{c.taxId}</span><Input value={taxId} onChange={e=>setTaxId(e.target.value)}/></label></div></Card>
  <Card className="p-5 sm:p-6"><h2 className="text-[15px] font-semibold">{c.bankDetails}</h2><p className="mt-1 text-[13px] text-[var(--fp-muted)]">{lang==='ru'?'Используются при подготовке платежей этому получателю.':'Used when preparing payments to this beneficiary.'}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.bankCountry}</span><SearchSelect value={bankCountry} onChange={setBankCountry} options={countries} placeholder={common.selectCountry}/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.bankName}</span><Input value={bankName} onChange={e=>setBankName(e.target.value)}/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)] sm:col-span-2"><span>{c.account}</span><Input value={account} onChange={e=>setAccount(e.target.value)} autoCapitalize="characters"/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.accountHolder}</span><Input value={holder} onChange={e=>setHolder(e.target.value)}/></label><label className="space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.bic}</span><Input value={bic} onChange={e=>setBic(e.target.value)} autoCapitalize="characters"/></label></div></Card>
  <div className="xl:col-span-2">{error&&<div className="mb-4 rounded-[12px] border border-[#f0cfd2] bg-[var(--fp-red-soft)] px-4 py-3 text-[14px] text-[var(--fp-red)]">{error}</div>}<div className="flex justify-end gap-2 rounded-[14px] border border-[var(--fp-border)] bg-white p-4"><Button type="button" variant="secondary" onClick={()=>router.push('/counterparties')}>{lang==='ru'?'Отмена':'Cancel'}</Button><Button disabled={saving}>{saving?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} {submitLabel}</Button></div></div></form></div>
}
