'use client'
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowRight, Loader2, Route as RouteIcon } from 'lucide-react'
import { Dialog } from '@/components/ui/dialog'
import { Input, Textarea } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { SearchSelect } from '@/components/ui/search-select'
import { SelectMenu } from '@/components/ui/select-menu'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { useWorkspace } from './WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { countryName, countryOptions, currencyOptions } from '@/lib/countries'
import { workspaceCopy } from '@/lib/workspace-copy'
import { money, speedLabel } from '@/lib/metrics'
import { createClient } from '@/lib/supabase/client'
import type { Invoice, PaymentDraft, QuoteResponse, QuoteRoute } from '@/lib/types'
import { cn } from '@/lib/utils'
import { userError } from '@/lib/user-error'

type Props={open:boolean;onOpenChange:(v:boolean)=>void;onSaved?:()=>void;initialInvoice?:Invoice|null;initialPayment?:PaymentDraft|null}
export function PaymentDialog({open,onOpenChange,onSaved,initialInvoice=null,initialPayment=null}:Props){
  const ws=useWorkspace();const {lang}=useLanguage();const c=workspaceCopy[lang].payment;const common=workspaceCopy[lang].common;const [counterpartyId,setCounterpartyId]=useState('');const [supplier,setSupplier]=useState('');const [invoice,setInvoice]=useState('');const [amount,setAmount]=useState('');const [currency,setCurrency]=useState(ws.profile?.preferred_currency||'');const [recipientCurrency,setRecipientCurrency]=useState('');const [due,setDue]=useState('');const [notes,setNotes]=useState('');const [reference,setReference]=useState('');const [fromCountry,setFromCountry]=useState(ws.profile?.country||'');const [toCountry,setToCountry]=useState('');const [routes,setRoutes]=useState<QuoteRoute[]>([]);const [routeId,setRouteId]=useState('');const [paymentMethod,setPaymentMethod]=useState<'bank_transfer'|'swift'|'local'>('bank_transfer');const [chargeType,setChargeType]=useState<'shared'|'sender'|'recipient'>('shared');const [quoting,setQuoting]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const idempotencyRef=useRef('')
  useEffect(()=>{if(!open)return;idempotencyRef.current=initialPayment?.id||crypto.randomUUID();const source=initialPayment;const invoiceSource=initialInvoice;const linkedId=source?.counterparty_id||invoiceSource?.counterparty_id||'';const cp=linkedId?ws.counterparties.find(c=>c.id===linkedId):null;setCounterpartyId(linkedId);setSupplier(source?.supplier_name||invoiceSource?.supplier_name||'');setInvoice(source?.invoice_number||invoiceSource?.invoice_number||'');setAmount(source?String(source.amount):invoiceSource?String(invoiceSource.amount):'');setCurrency(source?.currency||invoiceSource?.currency||ws.profile?.preferred_currency||'');setRecipientCurrency(source?.recipient_currency||cp?.currency||invoiceSource?.currency||'');setDue(source?.due_date||invoiceSource?.due_date||'');setNotes(source?.notes||invoiceSource?.notes||'');setReference(source?.reference||invoiceSource?.reference||'');setFromCountry(source?.route_from_country||ws.profile?.country||'');setToCountry(source?.route_to_country||cp?.country||'');const existingRoute=source?.route_snapshot||null;setRoutes(existingRoute?[existingRoute]:[]);setRouteId(existingRoute?.id||'');setPaymentMethod(source?.payment_method||((ws.profile?.default_payment_method as 'bank_transfer'|'swift'|'local')||'bank_transfer'));setChargeType(source?.charge_type||((ws.profile?.default_charge_type as 'shared'|'sender'|'recipient')||'shared'));setError('')},[open,ws.profile,initialInvoice,initialPayment,ws.counterparties])
  const cpOptions=useMemo(()=>ws.counterparties.map(c=>({value:c.id,label:c.name,description:`${countryName(c.country,lang)} · ${c.currency}`,leading:<CountryFlag code={c.country}/>})),[ws.counterparties,lang])
  const countries=useMemo(()=>countryOptions(lang).map(([code,label])=>({value:code,label,description:code,leading:<CountryFlag code={code}/>})),[lang])
  const currencies=useMemo(()=>currencyOptions(lang).map(c=>({value:c.code,label:c.code,description:c.name,leading:<span className="grid w-5 place-items-center text-[14px] font-semibold text-[var(--fp-muted)]">{c.symbol}</span>})),[lang])
  function clearQuote(){setRoutes([]);setRouteId('')}
  function chooseCounterparty(id:string){clearQuote();setCounterpartyId(id);const cp=ws.counterparties.find(c=>c.id===id);if(cp){setSupplier(cp.name);setToCountry(cp.country);setRecipientCurrency(cp.currency)}}
  async function quote(){if(!fromCountry||!toCountry||!amount||!currency||!recipientCurrency||fromCountry===toCountry)return;setQuoting(true);setError('');setRoutes([]);setRouteId('');try{const client=createClient();const {data:sessionData}=await client.auth.getSession();const token=sessionData.session?.access_token;const res=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({fromCountry,toCountry,amount:Number(amount),sourceCurrency:currency,recipientCurrency})});const data=(await res.json()) as QuoteResponse&{error?:string};if(!res.ok)throw new Error(data.error||'QUOTE_FAILED');setRoutes(data.routes||[]);if(data.routes?.[0])setRouteId(data.routes[0].id)}catch(e){setError(userError(lang,'route'))}finally{setQuoting(false)}}
  async function submit(e:FormEvent){e.preventDefault();if(!ws.user||!supplier.trim()||!currency||!recipientCurrency||!Number.isFinite(Number(amount))||Number(amount)<=0)return;setSaving(true);setError('');try{const selected=routes.find(r=>r.id===routeId)||null;const client=createClient();const idempotencyKey=initialPayment?.id||idempotencyRef.current||crypto.randomUUID();if(!idempotencyRef.current)idempotencyRef.current=idempotencyKey;const {data:paymentId,error:paymentError}=await client.rpc('flowpay_upsert_payment',{p_payment_id:initialPayment?.id||null,p_idempotency_key:idempotencyKey,p_counterparty_id:counterpartyId||null,p_supplier_name:supplier.trim(),p_invoice_number:invoice.trim(),p_amount:Number(amount),p_currency:currency,p_due_date:due||null,p_route_provider_code:selected?.providerCode||null,p_estimated_fee:selected?.fee??null,p_notes:notes.trim(),p_route_from_country:fromCountry||null,p_route_to_country:toCountry||null,p_recipient_currency:recipientCurrency||null,p_recipient_amount:selected?.recipientGets??null,p_reference:reference.trim(),p_route_snapshot:selected,p_payment_method:paymentMethod,p_charge_type:chargeType});if(paymentError)throw paymentError;if(initialInvoice&&paymentId){const {error:invoiceError}=await client.rpc('flowpay_link_invoice_payment',{p_invoice_id:initialInvoice.id,p_payment_id:paymentId});if(invoiceError)throw invoiceError}await ws.refresh();onSaved?.();onOpenChange(false)}catch{setError(userError(lang,'save'))}finally{setSaving(false)}}
  const editing=Boolean(initialPayment);const dialogTitle=editing?(lang==='ru'?'Изменить платёж':'Edit payment'):c.title;const submitLabel=editing?(lang==='ru'?'Сохранить изменения':'Save changes'):c.create
  return <Dialog open={open} onOpenChange={onOpenChange} title={dialogTitle} description={editing?(lang==='ru'?'Обновите сумму, сроки, контрагента или выбранный маршрут.':'Update the amount, due date, counterparty or selected route.'):c.description} className="sm:max-w-[760px]"><form onSubmit={submit} className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.counterparty}</span><SearchSelect value={counterpartyId} onChange={chooseCounterparty} options={cpOptions} placeholder={c.selectCounterparty}/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.supplier}</span><Input value={supplier} onChange={e=>setSupplier(e.target.value)} required placeholder={c.supplierPlaceholder}/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.invoice}</span><Input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="INV-…"/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.reference}</span><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="PO / reference"/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.amount}</span><Input type="number" min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);clearQuote()}} required/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.currency}</span><SearchSelect value={currency} onChange={v=>{setCurrency(v);clearQuote()}} options={currencies} variant="currency"/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{common.receiveCurrency}</span><SearchSelect value={recipientCurrency} onChange={v=>{setRecipientCurrency(v);clearQuote()}} options={currencies} variant="currency"/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.due}</span><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{lang==='ru'?'Способ платежа':lang==='fr'?'Mode de paiement':lang==='de'?'Zahlungsart':lang==='es'?'Método de pago':'Payment method'}</span><SelectMenu value={paymentMethod} onChange={v=>setPaymentMethod(v as 'bank_transfer'|'swift'|'local')} options={[{value:'bank_transfer',label:workspaceCopy[lang].settings.bankTransfer},{value:'swift',label:'SWIFT'},{value:'local',label:workspaceCopy[lang].settings.localTransfer}]}/></label><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{lang==='ru'?'Комиссия банка':lang==='fr'?'Répartition des frais':lang==='de'?'Gebührenregelung':lang==='es'?'Reparto de comisiones':'Bank charge type'}</span><SelectMenu value={chargeType} onChange={v=>setChargeType(v as 'shared'|'sender'|'recipient')} options={[{value:'shared',label:workspaceCopy[lang].settings.shared},{value:'sender',label:workspaceCopy[lang].settings.sender},{value:'recipient',label:workspaceCopy[lang].settings.recipient}]}/></label></div>
    <div className="rounded-[13px] border border-[var(--fp-border)] bg-[#fafbf8] p-4"><div className="grid gap-3 sm:grid-cols-[1fr_24px_1fr_auto] sm:items-end"><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.source}</span><SearchSelect value={fromCountry} onChange={v=>{setFromCountry(v);clearQuote()}} options={countries} placeholder={common.selectCountry}/></label><ArrowRight size={15} className="mb-3 hidden text-[var(--fp-subtle)] sm:block"/><label className="space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.destination}</span><SearchSelect value={toCountry} onChange={v=>{setToCountry(v);clearQuote()}} options={countries} placeholder={common.selectCountry}/></label><Button type="button" variant="secondary" onClick={quote} disabled={quoting||!fromCountry||!toCountry||!amount||!currency||!recipientCurrency||fromCountry===toCountry}>{quoting?<Loader2 size={14} className="animate-spin"/>:<RouteIcon size={14}/>}{c.findRoutes}</Button></div>
      {routes.length>0&&<div className="mt-4 grid gap-2 sm:grid-cols-2">{routes.slice(0,4).map((route,i)=><button type="button" key={route.id} onClick={()=>setRouteId(route.id)} className={cn('rounded-[11px] border p-3 text-left transition',routeId===route.id?'border-[#9dbba5] bg-[var(--fp-green-soft)]':'border-[var(--fp-border)] bg-white hover:border-[var(--fp-border-strong)]')}><div className="flex items-center justify-between"><strong className="text-[14px]">{route.providerName}</strong><span className="text-[14px] font-semibold text-[var(--fp-green)]">{route.score}</span></div><div className="mt-2 flex justify-between text-[14px] text-[var(--fp-muted)]"><span>{money(route.fee,currency,lang)}</span><span>{route.recipientGets==null?speedLabel(route.speedMinutes,lang):`${money(route.recipientGets,recipientCurrency,lang)} · ${speedLabel(route.speedMinutes,lang)}`}</span></div>{i===0&&<span className="mt-2 inline-block rounded-full bg-white/70 px-2 py-1 text-[14px] font-semibold text-[var(--fp-green-strong)]">{c.bestScore}</span>}</button>)}</div>}
      {!quoting&&routes.length===0&&fromCountry&&toCountry&&amount&&<p className="mt-3 text-[14px] text-[var(--fp-muted)]">{c.noRouteBefore}</p>}
    </div>
    <label className="block space-y-1.5 text-[14px] font-medium text-[var(--fp-muted)]"><span>{c.notes}</span><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={c.notesPlaceholder}/></label>
    {error&&<div className="rounded-[10px] bg-[var(--fp-red-soft)] p-3 text-[14px] text-[var(--fp-red)]">{error}</div>}
    <div className="flex justify-end gap-2 border-t border-[var(--fp-border)] pt-4"><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>{lang==='ru'?'Отмена':lang==='fr'?'Annuler':lang==='de'?'Abbrechen':lang==='es'?'Cancelar':'Cancel'}</Button><Button disabled={saving}>{saving&&<Loader2 size={14} className="animate-spin"/>}{submitLabel}</Button></div>
  </form></Dialog>
}
