'use client'
import type { ReactNode } from 'react'
import { ArrowRight, Inbox, Plus } from 'lucide-react'
import { Badge, type BadgeTone } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { useLanguage } from '@/components/LanguageContext'
import type { Language } from '@/lib/types'

export function PageHeader({title,subtitle,actions,eyebrow}:{title:string;subtitle?:string;actions?:ReactNode;eyebrow?:string}){
  return <div className="mb-6 flex flex-col gap-4 sm:mb-7 sm:flex-row sm:items-end sm:justify-between">
    <div className="min-w-0">{eyebrow&&<div className="mb-2 text-[14px] font-semibold uppercase tracking-[.12em] text-[var(--fp-green)]">{eyebrow}</div>}<h1 className="text-[32px] font-semibold leading-[1.04] tracking-[-.05em] text-[#101714] sm:text-[36px]">{title}</h1>{subtitle&&<p className="mt-2.5 max-w-3xl text-[15px] leading-6 text-[var(--fp-muted)]">{subtitle}</p>}</div>{actions&&<div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}
  </div>
}

export function MetricCard({label,value,meta,trend,icon,children,className,accent=false}:{label:string;value:string;meta?:string;trend?:string|null;icon?:ReactNode;children?:ReactNode;className?:string;accent?:boolean}){
  return <div className={cn('fp-card group relative min-h-[150px] overflow-hidden p-5 sm:p-6',accent&&'border-[#cfe0d3] bg-[linear-gradient(145deg,#ffffff_0%,#f4f9f5_100%)]',className)}>
    {accent&&<div className="pointer-events-none absolute -right-8 -top-12 size-36 rounded-full bg-[#dcefe1]/60 blur-2xl"/>}
    <div className="relative flex items-start justify-between gap-3"><span className="text-[14px] font-semibold tracking-[-.01em] text-[#56615a]">{label}</span>{icon&&<span className="grid size-9 place-items-center rounded-[11px] bg-[#eef5ef] text-[var(--fp-green)] transition-transform duration-200 group-hover:-translate-y-0.5">{icon}</span>}</div>
    <div className="relative mt-4 flex items-center gap-2"><strong className="text-[31px] font-semibold leading-none tracking-[-.055em] sm:text-[34px]">{value}</strong>{trend&&<Badge tone="success" className="h-6 px-2.5 text-[14px]">{trend}</Badge>}</div>
    {meta&&<p className="relative mt-2 text-[14px] leading-5 text-[var(--fp-muted)]">{meta}</p>}{children&&<div className="relative mt-4">{children}</div>}
  </div>
}

export function EmptyState({title,description,actionLabel,onAction,compact=false,icon}:{title:string;description?:string;actionLabel?:string;onAction?:()=>void;compact?:boolean;icon?:ReactNode}){
  return <div className={cn('flex flex-col items-center justify-center rounded-[14px] border border-[#e3e8e3] bg-[linear-gradient(180deg,#fbfcfa_0%,#f6f9f6_100%)] px-6 text-center shadow-[inset_0_1px_0_rgba(255,255,255,.75)]',compact?'min-h-36 py-7':'min-h-56 py-10')}><span className="grid size-11 place-items-center rounded-[13px] border border-[#dbe7dd] bg-white text-[var(--fp-green)] shadow-[0_4px_16px_rgba(23,66,36,.06)]">{icon||<Inbox size={19}/>}</span><strong className="mt-4 max-w-md text-[16px] font-semibold leading-5 tracking-[-.015em]">{title}</strong>{description&&<p className="mt-2 max-w-md text-[14px] leading-5 text-[var(--fp-muted)]">{description}</p>}{actionLabel&&onAction&&<Button size="sm" className="mt-5" onClick={onAction}><Plus size={14}/>{actionLabel}</Button>}</div>
}

export function StatusBadge({status}:{status:string}){const {lang}=useLanguage();const normalized=status.toLowerCase();let tone:BadgeTone='neutral';if(['paid','received','verified','completed','active','details_ready'].includes(normalized))tone='success';else if(['ready','in_review','scheduled'].includes(normalized))tone='info';else if(['rejected','failed','overdue','revoked','cancelled','details_invalid'].includes(normalized))tone='danger';else if(['pending','warning','open','details_missing'].includes(normalized))tone='warning';return <Badge tone={tone}>{statusLabel(normalized,lang)}</Badge>}

function statusLabel(status:string,lang:Language){const labels:Record<Language,Record<string,string>>={ru:{draft:'Черновик',ready:'Готов к оплате',paid:'Оплачен',received:'Получен',verified:'Проверен',completed:'Завершён',active:'Активен',in_review:'На проверке',scheduled:'Запланирован',rejected:'Отклонён',failed:'Ошибка',overdue:'Просрочен',revoked:'Отозван',pending:'Ожидает',warning:'Внимание',open:'Открыт',cancelled:'Отменён',unverified:'Не проверен',details_ready:'Реквизиты готовы',details_missing:'Нужны реквизиты',details_invalid:'Проверьте реквизиты'},en:{draft:'Draft',ready:'Ready to pay',paid:'Paid',received:'Received',verified:'Verified',completed:'Completed',active:'Active',in_review:'In review',scheduled:'Scheduled',rejected:'Rejected',failed:'Failed',overdue:'Overdue',revoked:'Revoked',pending:'Pending',warning:'Attention',open:'Open',cancelled:'Cancelled',unverified:'Unverified',details_ready:'Details ready',details_missing:'Details needed',details_invalid:'Check details'},fr:{draft:'Brouillon',ready:'Prêt à payer',paid:'Payé',received:'Reçu',verified:'Vérifié',completed:'Terminé',active:'Actif',in_review:'À vérifier',scheduled:'Planifié',rejected:'Refusé',failed:'Échec',overdue:'En retard',revoked:'Révoqué',pending:'En attente',warning:'Attention',open:'Ouverte',cancelled:'Annulée',unverified:'Non vérifié',details_ready:'Coordonnées prêtes',details_missing:'Coordonnées requises',details_invalid:'Vérifier les coordonnées'},de:{draft:'Entwurf',ready:'Zahlungsbereit',paid:'Bezahlt',received:'Empfangen',verified:'Verifiziert',completed:'Abgeschlossen',active:'Aktiv',in_review:'In Prüfung',scheduled:'Geplant',rejected:'Abgelehnt',failed:'Fehlgeschlagen',overdue:'Überfällig',revoked:'Widerrufen',pending:'Ausstehend',warning:'Achtung',open:'Offen',cancelled:'Storniert',unverified:'Nicht verifiziert',details_ready:'Daten vollständig',details_missing:'Daten erforderlich',details_invalid:'Daten prüfen'},es:{draft:'Borrador',ready:'Listo para pagar',paid:'Pagado',received:'Recibido',verified:'Verificado',completed:'Completado',active:'Activo',in_review:'En revisión',scheduled:'Programado',rejected:'Rechazado',failed:'Fallido',overdue:'Vencido',revoked:'Revocado',pending:'Pendiente',warning:'Atención',open:'Abierta',cancelled:'Cancelada',unverified:'Sin verificar',details_ready:'Datos listos',details_missing:'Faltan datos',details_invalid:'Revisar datos'}};return labels[lang][status]||status.replaceAll('_',' ')}

export function SectionTitle({title,action,href,subtitle}:{title:string;action?:string;href?:string;subtitle?:string}){return <div className="flex items-start justify-between gap-4"><div><h2 className="text-[17px] font-semibold tracking-[-.025em]">{title}</h2>{subtitle&&<p className="mt-1 text-[14px] leading-5 text-[var(--fp-muted)]">{subtitle}</p>}</div>{action&&href&&<a href={href} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2 text-[14px] font-semibold text-[var(--fp-green)] transition hover:bg-[var(--fp-green-soft)] hover:text-[var(--fp-green-strong)]">{action}<ArrowRight size={13}/></a>}</div>}
