'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowLeftRight, ArrowRight, BarChart3, Check, CircleDollarSign, Globe2, LockKeyhole, Route, ShieldCheck, Users } from 'lucide-react'
import { FlowPayLogo } from '@/components/brand/FlowPayLogo'
import { CountryFlag } from '@/components/brand/CountryFlag'
import { SelectMenu } from '@/components/ui/select-menu'
import { currencyName, currencySymbol } from '@/lib/countries'
import { Button } from '@/components/ui/button'
import { Calculator } from '@/components/Calculator'
import { AuditForm } from '@/components/AuditForm'
import { useLanguage } from '@/components/LanguageContext'
import { createClient } from '@/lib/supabase/client'
import type { Language } from '@/lib/types'

type PublicRule = { provider_code:string; display_name:string|null; from_country:string; to_country:string; currencies:string[] }
type Coverage = { providers:number; corridors:number; currencies:number; rules:PublicRule[] }

type HomeCopy = {
  product:string; compare:string; security:string; resources:string; sign:string; dashboard:string; start:string
  hero:string; sub:string; open:string; audit:string; badges:string[]
  stats:[string,string,string,string]
  why:string; whyTitle:string; features:[string,string][]
  how:string; howTitle:string; steps:[string,string][]
  secure:[string,string][]
  ready:string; readySub:string; footer:string
  preview:{routes:string; providers:string; corridors:string; currencies:string; empty:string; configured:string}
}

const copy:Record<Language,HomeCopy>={
  ru:{product:'Продукт',compare:'Сравнение',security:'Безопасность',resources:'Возможности',sign:'Войти',dashboard:'Кабинет',start:'Начать',hero:'Международные бизнес-платежи, проще.',sub:'FlowPay помогает финансовым командам сравнивать международные способы оплаты, контролировать комиссии и вести расчёты с поставщиками в одном кабинете.',open:'Открыть FlowPay',audit:'Проверить платёж',badges:['Сравнение способов оплаты','Референсные курсы ECB','Защищённые данные'],stats:['Платёжных партнёров','Доступных направлений','Поддерживаемых валют','Источник курсов'],why:'Почему FlowPay',whyTitle:'Единый кабинет для международных платежей и контроля расходов.',features:[['Умная маршрутизация','Сравнивайте доступные варианты по стоимости, скорости и надёжности.'],['Референсные курсы','Ориентируйтесь на курсы ECB и сразу видьте влияние конвертации на итоговую стоимость.'],['Контрагенты','Храните реквизиты, счета и историю расчётов с поставщиками в одном месте.'],['Аналитика','Следите за объёмом платежей, комиссиями, сроками и экономией по фактическим операциям.']],how:'Как это работает',howTitle:'От счёта до решения — в три шага.',steps:[['Создайте платёж','Укажите сумму, валюту, поставщика и срок оплаты.'],['Сравните варианты','FlowPay покажет доступные способы оплаты и поможет выбрать подходящий.'],['Контролируйте результат','Сохраняйте решение, отслеживайте статус и анализируйте расходы в кабинете.']],secure:[['Защита аккаунта','Доступ к финансовым данным ограничен вашим авторизованным аккаунтом.'],['Контролируемый доступ','Платёжные данные и операции доступны только после входа в защищённый аккаунт.'],['Прозрачные расчёты','Если нужный вариант или курс недоступен, FlowPay не подменяет его вымышленными данными.']],ready:'Готовы привести международные платежи в порядок?',readySub:'Добавьте контрагентов и начните сравнивать доступные варианты оплаты.',footer:'FlowPay · управление международными платежами · расчёты носят информационный характер.',preview:{routes:'Маршруты',providers:'Партнёры',corridors:'Направления',currencies:'Валюты',empty:'Доступные варианты появятся после подключения платёжных направлений',configured:'Доступные варианты'}},
  en:{product:'Product',compare:'Compare',security:'Security',resources:'Resources',sign:'Sign in',dashboard:'Dashboard',start:'Get started',hero:'International business payments, simplified.',sub:'FlowPay helps finance teams compare cross-border payment options, control fees and manage supplier payments from one clear account.',open:'Open FlowPay',audit:'Audit a payment',badges:['Payment option comparison','ECB reference rates','Protected account data'],stats:['Payment partners','Available corridors','Supported currencies','FX source'],why:'Why FlowPay',whyTitle:'One place to manage international payments and payment costs.',features:[['Smart routing','Compare available options by cost, speed and reliability.'],['Reference rates','Use ECB reference rates to understand how conversion affects total payment cost.'],['Counterparties','Keep supplier bank details, invoices and payment history together.'],['Analytics','Track payment volume, fees, settlement time and savings from actual activity.']],how:'How it works',howTitle:'From invoice to decision in three steps.',steps:[['Create a payment','Add the amount, currency, supplier and due date.'],['Compare options','FlowPay shows available payment options and helps you choose the right one.'],['Control the outcome','Save the decision, track status and analyse payment costs from your account.']],secure:[['Account protection','Access to financial data is restricted to your authenticated account.'],['Controlled access','Sensitive payment tools remain protected behind authenticated account access.'],['Transparent calculations','If an option or reference rate is unavailable, FlowPay does not replace it with invented data.']],ready:'Ready to simplify international payments?',readySub:'Add counterparties and start comparing available payment options.',footer:'FlowPay · international payment operations · calculations are provided for information only.',preview:{routes:'Routes',providers:'Partners',corridors:'Corridors',currencies:'Currencies',empty:'Available options will appear after payment corridors are connected',configured:'Available options'}},
  fr:{product:'Produit',compare:'Comparer',security:'Sécurité',resources:'Fonctions',sign:'Connexion',dashboard:'Tableau de bord',start:'Commencer',hero:'Les paiements internationaux, simplifiés.',sub:'FlowPay aide les équipes finance à comparer les options de paiement internationales, contrôler les frais et gérer les règlements fournisseurs depuis un seul compte.',open:'Ouvrir FlowPay',audit:'Auditer un paiement',badges:['Comparaison des options','Taux de référence BCE','Données protégées'],stats:['Partenaires de paiement','Corridors disponibles','Devises prises en charge','Source FX'],why:'Pourquoi FlowPay',whyTitle:'Un seul espace pour piloter les paiements internationaux et leurs coûts.',features:[['Routage intelligent','Comparez les options disponibles par coût, vitesse et fiabilité.'],['Taux de référence','Utilisez les taux BCE pour comprendre l’impact de la conversion sur le coût total.'],['Contreparties','Centralisez coordonnées bancaires, factures et historique des paiements.'],['Analytique','Suivez volumes, frais, délais et économies à partir de vos opérations réelles.']],how:'Comment ça marche',howTitle:'De la facture à la décision en trois étapes.',steps:[['Créer un paiement','Ajoutez le montant, la devise, le fournisseur et l’échéance.'],['Comparer les options','FlowPay présente les options disponibles pour choisir la plus adaptée.'],['Suivre le résultat','Conservez la décision, suivez le statut et analysez les coûts depuis votre compte.']],secure:[['Protection du compte','L’accès aux données financières est limité à votre compte authentifié.'],['Accès contrôlé','Les données et outils de paiement restent protégés derrière l’accès authentifié au compte.'],['Calculs transparents','Si une option ou un taux est indisponible, FlowPay ne le remplace pas par des données fictives.']],ready:'Prêt à simplifier vos paiements internationaux ?',readySub:'Ajoutez vos contreparties et comparez les options de paiement disponibles.',footer:'FlowPay · gestion des paiements internationaux · calculs fournis à titre informatif.',preview:{routes:'Routes',providers:'Partenaires',corridors:'Corridors',currencies:'Devises',empty:'Les options disponibles apparaîtront après la connexion des corridors de paiement',configured:'Options disponibles'}},
  de:{product:'Produkt',compare:'Vergleichen',security:'Sicherheit',resources:'Funktionen',sign:'Anmelden',dashboard:'Übersicht',start:'Starten',hero:'Internationale Geschäftszahlungen, vereinfacht.',sub:'FlowPay hilft Finanzteams, internationale Zahlungsoptionen zu vergleichen, Gebühren zu kontrollieren und Lieferantenzahlungen in einem übersichtlichen Konto zu verwalten.',open:'FlowPay öffnen',audit:'Zahlung prüfen',badges:['Zahlungsoptionen vergleichen','EZB-Referenzkurse','Geschützte Kontodaten'],stats:['Zahlungspartner','Verfügbare Korridore','Unterstützte Währungen','FX-Quelle'],why:'Warum FlowPay',whyTitle:'Ein zentraler Ort für internationale Zahlungen und Kostenkontrolle.',features:[['Smartes Routing','Vergleichen Sie verfügbare Optionen nach Kosten, Geschwindigkeit und Zuverlässigkeit.'],['Referenzkurse','Nutzen Sie EZB-Referenzkurse, um die Auswirkungen der Umrechnung auf die Gesamtkosten zu verstehen.'],['Geschäftspartner','Verwalten Sie Bankdaten, Rechnungen und Zahlungshistorie gemeinsam.'],['Analyse','Verfolgen Sie Volumen, Gebühren, Laufzeiten und Einsparungen aus echten Transaktionen.']],how:'So funktioniert es',howTitle:'Von der Rechnung zur Entscheidung in drei Schritten.',steps:[['Zahlung erstellen','Betrag, Währung, Lieferant und Fälligkeit hinzufügen.'],['Optionen vergleichen','FlowPay zeigt verfügbare Zahlungsoptionen und erleichtert die Auswahl.'],['Ergebnis kontrollieren','Entscheidung speichern, Status verfolgen und Zahlungskosten im Konto analysieren.']],secure:[['Kontoschutz','Der Zugriff auf Finanzdaten ist auf Ihr authentifiziertes Konto beschränkt.'],['Kontrollierter Zugriff','Zahlungsdaten und Funktionen bleiben durch den authentifizierten Kontozugriff geschützt.'],['Transparente Berechnung','Fehlende Optionen oder Referenzkurse werden nicht durch erfundene Daten ersetzt.']],ready:'Bereit für einfachere internationale Zahlungen?',readySub:'Geschäftspartner hinzufügen und verfügbare Zahlungsoptionen vergleichen.',footer:'FlowPay · internationale Zahlungsverwaltung · Berechnungen dienen nur zur Information.',preview:{routes:'Routen',providers:'Partner',corridors:'Korridore',currencies:'Währungen',empty:'Verfügbare Optionen erscheinen nach der Anbindung von Zahlungskorridoren',configured:'Verfügbare Optionen'}},
  es:{product:'Producto',compare:'Comparar',security:'Seguridad',resources:'Funciones',sign:'Entrar',dashboard:'Panel',start:'Empezar',hero:'Pagos internacionales para empresas, simplificados.',sub:'FlowPay ayuda a los equipos financieros a comparar opciones de pago internacionales, controlar comisiones y gestionar pagos a proveedores desde una sola cuenta.',open:'Abrir FlowPay',audit:'Auditar pago',badges:['Comparación de opciones','Tipos de referencia BCE','Datos protegidos'],stats:['Socios de pago','Corredores disponibles','Monedas compatibles','Fuente FX'],why:'Por qué FlowPay',whyTitle:'Un solo lugar para gestionar pagos internacionales y sus costes.',features:[['Enrutamiento inteligente','Compara opciones disponibles por coste, velocidad y fiabilidad.'],['Tipos de referencia','Usa los tipos del BCE para entender el impacto de la conversión en el coste total.'],['Contrapartes','Centraliza datos bancarios, facturas e historial de pagos.'],['Analítica','Controla volumen, comisiones, tiempos y ahorro a partir de operaciones reales.']],how:'Cómo funciona',howTitle:'De la factura a la decisión en tres pasos.',steps:[['Crear un pago','Añade importe, moneda, proveedor y vencimiento.'],['Comparar opciones','FlowPay muestra las opciones de pago disponibles para ayudarte a elegir.'],['Controlar el resultado','Guarda la decisión, sigue el estado y analiza los costes desde tu cuenta.']],secure:[['Protección de la cuenta','El acceso a los datos financieros está limitado a tu cuenta autenticada.'],['Acceso controlado','Los datos y herramientas de pago permanecen protegidos tras el acceso autenticado a la cuenta.'],['Cálculos transparentes','Si falta una opción o un tipo de referencia, FlowPay no lo sustituye por datos inventados.']],ready:'¿Listo para simplificar los pagos internacionales?',readySub:'Añade contrapartes y empieza a comparar opciones de pago disponibles.',footer:'FlowPay · gestión de pagos internacionales · los cálculos son informativos.',preview:{routes:'Rutas',providers:'Socios',corridors:'Corredores',currencies:'Monedas',empty:'Las opciones disponibles aparecerán al conectar corredores de pago',configured:'Opciones disponibles'}},
}

export function HomePage(){
  const {lang,setLang}=useLanguage();const c=copy[lang]
  const [coverage,setCoverage]=useState<Coverage|null>(null);const [signed,setSigned]=useState(false)
  useEffect(()=>{const s=createClient();void s.auth.getUser().then(r=>setSigned(Boolean(r.data.user)));void fetch('/api/coverage',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(data?.coverage)setCoverage(data.coverage as Coverage)}).catch(()=>{})},[])
  const target=signed?'/dashboard':'/login'
  return <div className="min-h-screen bg-[#fbfaf7] text-[#101814]">
    <header className="sticky top-0 z-50 border-b border-[#e8e9e5] bg-[#fbfaf7]/92 backdrop-blur-xl"><div className="mx-auto flex h-[66px] max-w-[1240px] items-center px-5 sm:px-7"><Link href="/"><FlowPayLogo/></Link><nav className="ml-auto hidden items-center gap-8 text-[14px] font-medium text-[#3e4741] md:flex"><a href="#product" className="transition hover:text-[var(--fp-green)]">{c.product}</a><a href="#calculator" className="transition hover:text-[var(--fp-green)]">{c.compare}</a><a href="#security" className="transition hover:text-[var(--fp-green)]">{c.security}</a><a href="#resources" className="transition hover:text-[var(--fp-green)]">{c.resources}</a></nav><div className="ml-auto flex items-center gap-2 md:ml-8"><div className="hidden sm:block"><SelectMenu value={lang} onChange={v=>setLang(v as Language)} compact align="right" ariaLabel="Language" triggerClassName="w-[92px] border-transparent bg-transparent hover:border-[var(--fp-border)] hover:bg-white" options={[{value:'ru',label:'RU',description:'Русский',leading:<Globe2 size={13}/>},{value:'en',label:'EN',description:'English',leading:<Globe2 size={13}/>},{value:'fr',label:'FR',description:'Français',leading:<Globe2 size={13}/>},{value:'de',label:'DE',description:'Deutsch',leading:<Globe2 size={13}/>},{value:'es',label:'ES',description:'Español',leading:<Globe2 size={13}/>}]} /></div><Link href={target} className="hidden rounded-[9px] px-3 py-2 text-[14px] font-medium transition hover:bg-white sm:block">{signed?c.dashboard:c.sign}</Link><Link href={target} className="rounded-[10px] bg-[var(--fp-green)] px-4 py-2.5 text-[14px] font-semibold text-white shadow-[0_4px_14px_rgba(24,122,69,.12)] transition hover:-translate-y-px hover:bg-[var(--fp-green-strong)]">{c.start}</Link></div></div></header>
    <main>
      <section className="relative overflow-hidden border-b border-[#e9ebe7] before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:h-[420px] before:bg-[radial-gradient(circle_at_72%_30%,rgba(88,140,103,.09),transparent_34%),radial-gradient(circle_at_22%_15%,rgba(255,255,255,.9),transparent_38%)]"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 pb-14 pt-16 sm:px-7 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:pb-24 lg:pt-24"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#dfe5df] bg-white px-3 py-1.5 text-[12px] font-semibold text-[var(--fp-green)]"><span className="size-1.5 rounded-full bg-[var(--fp-green)]"/>FlowPay</span><h1 className="mt-6 max-w-[570px] text-[46px] font-semibold leading-[1.01] tracking-[-.06em] sm:text-[60px] lg:text-[66px]">{c.hero}</h1><p className="mt-6 max-w-[590px] text-[13px] leading-6 text-[var(--fp-muted)] sm:text-[14px]">{c.sub}</p><div className="mt-7 flex flex-wrap gap-2"><Link href={target}><Button size="lg">{c.open}<ArrowRight size={15}/></Button></Link><a href="#audit"><Button size="lg" variant="secondary">{c.audit}</Button></a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2">{c.badges.map(b=><span key={b} className="flex items-center gap-2 text-[12px] text-[var(--fp-muted)]"><span className="grid size-4 place-items-center rounded-full border border-[#9fc5aa] text-[var(--fp-green)]"><Check size={10}/></span>{b}</span>)}</div></div><ProductPreview coverage={coverage} copy={c.preview}/></div></section>
      <section className="border-b border-[#e9ebe7] bg-white/60"><div className="mx-auto grid max-w-[1240px] grid-cols-2 px-5 py-7 sm:px-7 lg:grid-cols-4">{[[coverage?.providers??'—',c.stats[0]],[coverage?.corridors??'—',c.stats[1]],[coverage?.currencies??'—',c.stats[2]],['ECB',c.stats[3]]].map(([v,l],i)=><div key={String(l)} className={`px-4 py-3 text-center ${i?'border-l border-[#e8eae6]':''}`}><strong className="block text-[23px] font-semibold tracking-[-.04em]">{v}</strong><span className="mt-1 block text-[11px] uppercase tracking-[.08em] text-[var(--fp-subtle)]">{l}</span></div>)}</div></section>
      <section id="resources" className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><span className="text-[12px] font-semibold uppercase tracking-[.12em] text-[var(--fp-green)]">{c.why}</span><h2 className="mt-3 text-[32px] font-semibold leading-tight tracking-[-.045em]">{c.whyTitle}</h2></div><div className="grid gap-3 sm:grid-cols-2">{[[Route,...c.features[0]],[CircleDollarSign,...c.features[1]],[Users,...c.features[2]],[BarChart3,...c.features[3]]].map(([Icon,title,desc])=><div key={String(title)} className="rounded-[14px] border border-[var(--fp-border)] bg-white p-5 shadow-[var(--fp-shadow)]"><span className="grid size-9 place-items-center rounded-[10px] bg-[var(--fp-green-soft)] text-[var(--fp-green)]"><Icon size={17}/></span><h3 className="mt-5 text-[12px] font-semibold">{String(title)}</h3><p className="mt-2 text-[13px] leading-5 text-[var(--fp-muted)]">{String(desc)}</p></div>)}</div></div></section>
      <section id="calculator" className="border-y border-[#e8eae6] bg-white/65"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7"><Calculator/></div></section>
      <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7"><div className="mb-8 max-w-xl"><span className="text-[12px] font-semibold uppercase tracking-[.12em] text-[var(--fp-green)]">{c.how}</span><h2 className="mt-3 text-[34px] font-semibold tracking-[-.045em]">{c.howTitle}</h2></div><div className="grid gap-3 md:grid-cols-3">{c.steps.map((s,i)=><div key={s[0]} className="rounded-[14px] border border-[var(--fp-border)] bg-white p-6"><span className="grid size-7 place-items-center rounded-[8px] bg-[#eef3ed] text-[12px] font-bold text-[var(--fp-green)]">{i+1}</span><h3 className="mt-6 text-[13px] font-semibold">{s[0]}</h3><p className="mt-2 text-[13px] leading-5 text-[var(--fp-muted)]">{s[1]}</p></div>)}</div></section>
      <section id="security" className="border-y border-[#e8eae6] bg-[#f5f7f3]"><div className="mx-auto grid max-w-[1240px] gap-8 px-5 py-16 sm:px-7 lg:grid-cols-3">{[[ShieldCheck,...c.secure[0]],[LockKeyhole,...c.secure[1]],[Globe2,...c.secure[2]]].map(([Icon,title,desc])=><div key={String(title)} className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-[11px] bg-white text-[var(--fp-green)] shadow-sm"><Icon size={18}/></span><div><h3 className="text-[12px] font-semibold">{String(title)}</h3><p className="mt-2 text-[13px] leading-5 text-[var(--fp-muted)]">{String(desc)}</p></div></div>)}</div></section>
      <section id="audit" className="mx-auto max-w-[1240px] px-5 py-20 sm:px-7"><AuditForm/></section>
      <section className="mx-auto max-w-[1240px] px-5 pb-20 sm:px-7"><div className="overflow-hidden rounded-[18px] border border-[#dfe5df] bg-[#edf4ee] p-7 sm:flex sm:items-center sm:justify-between sm:p-9"><div><h2 className="text-[28px] font-semibold tracking-[-.045em]">{c.ready}</h2><p className="mt-2 text-[13px] text-[var(--fp-muted)]">{c.readySub}</p></div><div className="mt-5 sm:mt-0"><Link href={target}><Button size="lg">{c.start}<ArrowRight size={15}/></Button></Link></div></div></section>
    </main>
    <footer className="border-t border-[#e8eae6] bg-white"><div className="mx-auto grid max-w-[1240px] gap-5 px-5 py-8 sm:px-7 lg:grid-cols-[auto_1fr_auto] lg:items-center"><FlowPayLogo/><p className="text-[12px] text-[var(--fp-subtle)] lg:text-center">{c.footer}</p><nav className="flex flex-wrap gap-x-4 gap-y-2 text-[12px] font-medium text-[var(--fp-muted)]"><Link href="/security">{c.security}</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/status">Status</Link></nav></div></footer>
  </div>
}

function ProductPreview({coverage,copy}:{coverage:Coverage|null;copy:HomeCopy['preview']}){
  const {lang}=useLanguage()
  const configuredCurrencies=Array.from(new Set((coverage?.rules||[]).flatMap(rule=>rule.currencies||[]))).filter(Boolean)
  const [sendCurrency,setSendCurrency]=useState('')
  const [receiveCurrency,setReceiveCurrency]=useState('')
  useEffect(()=>{
    if(!configuredCurrencies.length){setSendCurrency('');setReceiveCurrency('');return}
    setSendCurrency(current=>configuredCurrencies.includes(current)?current:configuredCurrencies[0])
    setReceiveCurrency(current=>configuredCurrencies.includes(current)?current:(configuredCurrencies[1]||configuredCurrencies[0]))
  },[configuredCurrencies.join('|')])
  const currencyOptions=configuredCurrencies.map(code=>({value:code,label:code,description:currencyName(code,lang),leading:<span className="grid size-6 place-items-center rounded-[7px] bg-[#f0f4ef] text-[11px] font-bold text-[var(--fp-green-strong)]">{currencySymbol(code,lang)}</span>}))
  return <div id="product" className="relative mx-auto w-full max-w-[720px]">
    <div className="absolute -inset-12 -z-10 rounded-full bg-[radial-gradient(circle_at_center,rgba(87,139,103,.13),transparent_62%)] blur-sm"/>
    <div className="overflow-hidden rounded-[20px] border border-[#dde3dd] bg-white shadow-[0_30px_90px_rgba(29,52,37,.12)]">
      <div className="flex h-12 items-center gap-2 border-b border-[#e9ebe7] bg-[#fcfcfa] px-4">
        <span className="size-2 rounded-full bg-[#d9ded9]"/><span className="size-2 rounded-full bg-[#d9ded9]"/><span className="size-2 rounded-full bg-[#d9ded9]"/>
        <div className="ml-3 flex h-7 flex-1 items-center rounded-[8px] border border-[#edf0eb] bg-white px-3 text-[9px] text-[#a0a7a1]">flowpay.app/dashboard</div>
        <span className="grid size-7 place-items-center rounded-[8px] bg-[#eef4ef] text-[var(--fp-green)]"><BarChart3 size={12}/></span>
      </div>
      <div className="grid min-h-[390px] grid-cols-[112px_1fr] sm:grid-cols-[126px_1fr]">
        <aside className="border-r border-[#eaebe8] bg-[#fdfdfb] p-3.5"><FlowPayLogo compact/><div className="mt-7 space-y-1.5">{['Overview','Payments','Counterparties','Routes','Analytics'].map((x,i)=><div key={x} className={`flex items-center gap-1.5 rounded-[7px] px-2 py-2 text-[10px] ${i===0?'bg-[#edf4ee] font-semibold text-[var(--fp-green)]':'text-[#8a928c]'}`}><span className={`size-1.5 rounded-full ${i===0?'bg-[var(--fp-green)]':'bg-[#d9ded9]'}`}/>{x}</div>)}</div></aside>
        <div className="p-4 sm:p-5">
          <div className="grid grid-cols-3 gap-2.5">{[[coverage?.providers??'—',copy.providers],[coverage?.corridors??'—',copy.corridors],[coverage?.currencies??'—',copy.currencies]].map(([v,l],i)=><div key={String(l)} className="rounded-[10px] border border-[#e7eae5] bg-white p-3 shadow-[0_1px_2px_rgba(16,38,24,.025)]"><span className="text-[9px] font-medium text-[#8b938e]">{l}</span><div className="mt-2 flex items-end justify-between"><strong className="text-[17px] tracking-[-.04em]">{v||'—'}</strong><span className={`size-2 rounded-full ${i===0&&v?'bg-[#6db483]':'bg-[#dce3dc]'}`}/></div></div>)}</div>
          <div className="mt-2.5 rounded-[11px] border border-[#e7eae5] bg-white p-3.5"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold">{copy.configured}</span><span className="rounded-full bg-[#f1f5f1] px-2 py-1 text-[9px] font-medium text-[var(--fp-muted)]">{coverage?.rules.length??'—'}</span></div>{coverage?.rules.length?<div className="mt-3 space-y-1.5">{coverage.rules.map((r,i)=><div key={`${r.provider_code}-${i}`} className="grid grid-cols-[1fr_auto] items-center gap-2 rounded-[8px] border border-transparent bg-[#fafbf8] p-2.5 transition hover:border-[#e2e8e2] hover:bg-white"><span className="min-w-0"><strong className="block truncate text-[10px]">{r.display_name||r.provider_code}</strong><small className="mt-1 flex items-center gap-1 text-[9px] text-[var(--fp-muted)]"><CountryFlag code={r.from_country==='*'?null:r.from_country} className="h-[8px] w-[12px]"/>{r.from_country} <ArrowRight size={7}/> <CountryFlag code={r.to_country==='*'?null:r.to_country} className="h-[8px] w-[12px]"/>{r.to_country}</small></span><span className="rounded-full bg-[var(--fp-green-soft)] px-2 py-1 text-[9px] font-semibold text-[var(--fp-green)]">{r.currencies?.slice(0,2).join(' · ')||'—'}</span></div>)}</div>:<div className="mt-3 grid min-h-[104px] place-items-center rounded-[9px] border border-[#e4e8e3] bg-[#fafbf8] px-5 text-center text-[10px] leading-4 text-[var(--fp-muted)]">{copy.empty}</div>}</div>
          <div className="mt-2.5 rounded-[11px] border border-[#e7eae5] bg-white p-3.5"><div className="flex items-center justify-between"><div><span className="block text-[10px] font-semibold">{copy.currencies}</span><small className="mt-0.5 block text-[9px] text-[var(--fp-muted)]">{lang==='ru'?'Выбор валюты платежа':lang==='fr'?'Sélection des devises':lang==='de'?'Währungsauswahl':lang==='es'?'Selección de divisas':'Payment currency selection'}</small></div><CircleDollarSign size={13} className="text-[var(--fp-green)]"/></div>
            {currencyOptions.length?<div className="mt-3 grid grid-cols-[1fr_30px_1fr] items-center gap-2"><MiniCurrencySelect value={sendCurrency} onChange={setSendCurrency} options={currencyOptions}/><button type="button" onClick={()=>{setSendCurrency(receiveCurrency);setReceiveCurrency(sendCurrency)}} className="grid size-[30px] place-items-center rounded-[9px] border border-[#e1e6e0] bg-[#f7f9f6] text-[var(--fp-muted)] transition hover:border-[#bad0c0] hover:bg-[#eef5ef] hover:text-[var(--fp-green)]"><ArrowLeftRight size={11}/></button><MiniCurrencySelect value={receiveCurrency} onChange={setReceiveCurrency} options={currencyOptions}/></div>:<div className="mt-3 rounded-[9px] border border-[#e4e8e3] bg-[#fafbf8] p-3 text-center text-[10px] text-[var(--fp-muted)]">{copy.empty}</div>}
          </div>
        </div>
      </div>
    </div>
  </div>
}

function MiniCurrencySelect({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:{value:string;label:string;description:string;leading:ReactNode}[]}){
  return <SelectMenu value={value} onChange={onChange} options={options} compact triggerClassName="h-[42px] rounded-[9px] border-[#e2e6e1] bg-[#fbfcfa] px-2.5 text-[11px] hover:bg-white" panelClassName="text-[12px]" ariaLabel="Currency"/>
}
