'use client'
import { useState } from 'react'
import { ArrowLeft, Check, Clipboard, KeyRound, Loader2, ShieldCheck } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { workspaceCopy } from '@/lib/workspace-copy'
import { userError } from '@/lib/user-error'

export default function NewApiKeyPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const copy=workspaceCopy[lang];const router=useRouter();const [name,setName]=useState('Production');const [saving,setSaving]=useState(false);const [secret,setSecret]=useState('');const [copied,setCopied]=useState(false);const [error,setError]=useState('')
  async function authToken(){const mod=await import('@/lib/supabase/client');const {data}=await mod.createClient().auth.getSession();return data.session?.access_token||''}
  async function createKey(){if(!ws.user||saving)return;setSaving(true);setError('');try{const accessToken=await authToken();if(!accessToken)throw new Error('UNAUTHORIZED');const res=await fetch('/api/keys',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({name:name.trim()||'API key'})});const data=await res.json();if(!res.ok||!data.secret)throw new Error(data.error||'KEY_CREATE_FAILED');setSecret(data.secret);await ws.refresh()}catch{setError(userError(lang,'api'))}finally{setSaving(false)}}
  return <div className="fp-enter"><button onClick={()=>router.push('/developer')} className="mb-3 inline-flex items-center gap-2 text-[13px] font-medium text-[var(--fp-muted)] hover:text-[var(--fp-text)]"><ArrowLeft size={14}/>{lang==='ru'?'API':'API'}</button><h1 className="text-[30px] font-semibold tracking-[-.045em]">{secret?(lang==='ru'?'API-ключ создан':'API key created'):(lang==='ru'?'Создать API-ключ':'Create API key')}</h1><p className="mt-2 max-w-[680px] text-[14px] leading-6 text-[var(--fp-muted)]">{secret?(lang==='ru'?'Секрет показан только один раз. Сохраните его сейчас в менеджере секретов.':'The secret is shown only once. Store it in a secrets manager now.'):(lang==='ru'?'Создайте отдельный ключ для сервера, CRM или внутренней интеграции. Один ключ на одну систему упрощает отзыв и аудит доступа.':'Create a separate key for each server, CRM or internal integration.')}</p>
  <div className="mt-5 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5 sm:p-6">{secret?<><div className="flex items-center gap-2"><span className="grid size-10 place-items-center rounded-[11px] bg-[var(--fp-green-soft)] text-[var(--fp-green)]"><Check size={18}/></span><div><strong className="text-[14px]">{lang==='ru'?'Ключ активен':'Key is active'}</strong><p className="mt-1 text-[12px] text-[var(--fp-muted)]">{lang==='ru'?'Скопируйте секрет до ухода со страницы.':'Copy the secret before leaving this page.'}</p></div></div><div className="mt-5 flex items-center gap-2 rounded-[12px] border border-[var(--fp-border)] bg-[#f8faf7] p-3.5"><code className="min-w-0 flex-1 break-all text-[13px]">{secret}</code><button onClick={async()=>{await navigator.clipboard.writeText(secret);setCopied(true);setTimeout(()=>setCopied(false),1500)}} className="grid size-9 shrink-0 place-items-center rounded-[9px] border border-[var(--fp-border)] bg-white text-[var(--fp-green)]">{copied?<Check size={15}/>:<Clipboard size={15}/>}</button></div><Button className="mt-5 w-full" onClick={()=>router.push('/developer')}>{lang==='ru'?'Готово':'Done'}</Button></>:<><label className="block space-y-2 text-[13px] font-medium text-[var(--fp-muted)]"><span>{copy.api.keyName}</span><Input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Production"/></label>{error&&<div className="mt-4 rounded-[10px] bg-[var(--fp-red-soft)] p-3 text-[13px] text-[var(--fp-red)]">{error}</div>}<Button className="mt-5 w-full" onClick={createKey} disabled={saving||!name.trim()}>{saving?<Loader2 size={14} className="animate-spin"/>:<KeyRound size={14}/>} {copy.api.create}</Button></>}</Card><Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-[11px] bg-[#eef4ef] text-[var(--fp-green)]"><ShieldCheck size={18}/></span><div><h2 className="text-[15px] font-semibold">{lang==='ru'?'Как использовать ключ безопасно':'Use API keys safely'}</h2><ul className="mt-4 space-y-3 text-[13px] leading-5 text-[var(--fp-muted)]"><li>• {lang==='ru'?'Не вставляйте ключ в браузерный JavaScript или публичный репозиторий.':'Never expose the key in browser JavaScript or a public repository.'}</li><li>• {lang==='ru'?'Храните его в секретах сервера или CI/CD.':'Store it in server or CI/CD secrets.'}</li><li>• {lang==='ru'?'Создавайте отдельный ключ для каждой интеграции.':'Use a separate key for each integration.'}</li><li>• {lang==='ru'?'Сразу отзывайте ключ при подозрении на утечку.':'Revoke a key immediately if compromise is suspected.'}</li></ul></div></div></Card></div></div>
}
