export const LEGAL_VERSIONS = {
  privacy: '2026-08-17',
  terms: '2026-08-17',
} as const

export type LegalSection = { id: string; title: string; paragraphs: string[]; bullets?: string[] }
export type LegalDocument = {
  title: string
  shortTitle: string
  updated: string
  intro: string
  sections: LegalSection[]
}

export const privacyDocuments: Record<'ru'|'en', LegalDocument> = {
  ru: {
    title: 'Политика конфиденциальности FlowPay',
    shortTitle: 'Политика конфиденциальности',
    updated: 'Версия от 17 августа 2026 года',
    intro: 'Настоящая Политика объясняет, какие персональные данные обрабатываются при использовании FlowPay, для каких целей они нужны, кому могут передаваться и какие права есть у пользователя. FlowPay предназначен для рабочих процессов компаний, связанных с международными платежами, контрагентами, счетами, аналитикой и API.',
    sections: [
      {id:'controller',title:'1. Кто отвечает за обработку данных',paragraphs:['Контролёром персональных данных является оператор сервиса FlowPay. До коммерческого запуска оператор обязан указать на этой странице своё полное юридическое наименование, регистрационные сведения, юридический адрес и рабочий контакт по вопросам конфиденциальности. Если FlowPay используется по отдельному корпоративному договору, сведения об операторе также могут быть указаны в таком договоре.','По вопросам приватности, доступа к данным, исправления или удаления используйте официальный канал поддержки FlowPay, доступный в сервисе.']},
      {id:'data',title:'2. Какие данные мы обрабатываем',paragraphs:['Мы обрабатываем только данные, необходимые для работы продукта, безопасности и выполнения запросов пользователя.'],bullets:['данные аккаунта: email, идентификатор пользователя, сведения о входах и настройках безопасности;','данные компании: название, страна, базовая валюта, регистрационный номер, адрес и настройки рабочего пространства;','данные контрагентов: название, страна, валюта, контактные и банковские реквизиты, если пользователь их добавил;','данные счетов и платёжных операций: суммы, валюты, сроки, статусы, ссылки на контрагентов, маршруты и заметки;','данные использования API: имя и префикс API-ключа, endpoint, статус ответа, длительность и время запроса; секрет API-ключа после создания повторно не отображается;','технические и защитные данные: IP/географический регион, timezone, user-agent, request ID, события безопасности и диагностические записи, когда это необходимо для защиты и стабильности сервиса.']},
      {id:'purposes',title:'3. Цели и правовые основания',paragraphs:['Данные используются для предоставления запрошенных функций FlowPay, исполнения договорных отношений с пользователем или компанией, обеспечения безопасности, предотвращения злоупотреблений, поддержки, ведения технических журналов и соблюдения обязательных требований закона.','Когда обработка необходима для работы аккаунта или выполнения функции, она не основывается на отдельном маркетинговом согласии. Отдельное согласие запрашивается только для тех целей, где оно действительно требуется законом.']},
      {id:'geo',title:'4. Определение страны и часового пояса',paragraphs:['При первичной настройке FlowPay может использовать географические заголовки инфраструктуры хостинга для предложения страны и часового пояса. Эти данные используются только как начальная подсказка. Пользователь всегда может изменить страну и валюту вручную до сохранения профиля.']},
      {id:'providers',title:'5. Поставщики и получатели данных',paragraphs:['Для работы сервиса могут использоваться поставщики облачной инфраструктуры, базы данных, аутентификации, доставки приложения, мониторинга безопасности и иные технические подрядчики. Они получают только тот объём данных, который необходим для соответствующей функции, и обрабатывают данные в рамках договорных и технических ограничений.','FlowPay не продаёт персональные данные рекламодателям. Данные могут быть раскрыты государственным органам только при наличии действительного юридического требования или иной обязанности по закону.']},
      {id:'transfers',title:'6. Международная передача данных',paragraphs:['Поскольку инфраструктурные поставщики могут работать в разных странах, данные могут обрабатываться за пределами страны пользователя. Оператор FlowPay должен применять предусмотренные применимым законодательством механизмы защиты международной передачи данных, когда они требуются.']},
      {id:'retention',title:'7. Сроки хранения',paragraphs:['Данные аккаунта и рабочего пространства хранятся, пока аккаунт активен и пока они нужны для предоставления сервиса. Журналы безопасности, платёжные записи и иные данные могут храниться дольше, если это необходимо для защиты от злоупотреблений, расследования инцидентов, разрешения споров, бухгалтерских или иных обязательных требований.','Когда данные больше не нужны и отсутствует законное основание для хранения, они удаляются или обезличиваются.']},
      {id:'security',title:'8. Безопасность',paragraphs:['FlowPay применяет контроль доступа, разграничение данных пользователей, защищённое соединение, ограничения API, журналирование событий безопасности и другие технические меры. Пользователь отвечает за сохранность пароля, API-ключей и устройств, с которых выполняется вход.','Ни одна интернет-система не может гарантировать абсолютную безопасность. При подозрении на компрометацию пользователь должен немедленно сменить пароль, отозвать затронутые API-ключи и обратиться в поддержку.']},
      {id:'rights',title:'9. Права пользователя',paragraphs:['В зависимости от применимого законодательства пользователь может иметь право запросить доступ к своим персональным данным, их исправление, удаление, ограничение обработки, переносимость, возражение против определённых видов обработки и подачу жалобы в компетентный надзорный орган.','Если обработка в конкретном случае основана на согласии, такое согласие можно отозвать на будущее. Отзыв не делает незаконной обработку, выполненную до отзыва.']},
      {id:'business',title:'10. Данные других лиц, загружаемые компанией',paragraphs:['Пользователь или его компания могут добавлять сведения о сотрудниках, контрагентах и получателях платежей. Компания обязана иметь законное основание для передачи таких данных FlowPay и предоставлять необходимые уведомления этим лицам. FlowPay обрабатывает такие сведения для выполнения функций сервиса.']},
      {id:'changes',title:'11. Изменения Политики',paragraphs:['Политика может обновляться при изменении продукта, законодательства или инфраструктуры. Для существенных изменений FlowPay должен предоставить заметное уведомление. Если новое использование данных требует отдельного согласия, оно будет запрошено отдельно.']},
    ],
  },
  en: {
    title: 'FlowPay Privacy Policy', shortTitle:'Privacy Policy', updated:'Version dated 17 August 2026',
    intro:'This Policy explains what personal data is processed when FlowPay is used, why it is needed, who may receive it and what rights users may have. FlowPay is designed for business workflows involving international payments, counterparties, invoices, analytics and API access.',
    sections:[
      {id:'controller',title:'1. Data controller',paragraphs:['The controller is the operator of the FlowPay service. Before commercial launch, the operator must publish its full legal name, registration details, registered address and working privacy contact on this page. Where FlowPay is supplied under a separate business agreement, controller details may also be stated in that agreement.','Privacy, access, correction and deletion requests can be submitted through FlowPay’s official support channel.']},
      {id:'data',title:'2. Data we process',paragraphs:['We process information necessary to operate the product, secure it and fulfil user requests.'],bullets:['account data, including email, user identifier, sign-in and security information;','company profile and workspace settings;','counterparty contact and bank details entered by users;','invoice and payment workflow information, amounts, currencies, dates, statuses, routes and notes;','API usage data such as key name/prefix, endpoint, response status, request duration and timestamps;','technical and security information such as IP/geographic region, timezone, user-agent, request IDs and security diagnostics when required.']},
      {id:'purposes',title:'3. Purposes and legal bases',paragraphs:['Data is used to provide requested FlowPay functions, perform contracts with users or their organisations, secure the service, prevent abuse, provide support, maintain technical logs and comply with mandatory law.','Processing required to provide an account or requested function is not treated as optional marketing consent. Separate consent is requested only where consent is actually required.']},
      {id:'geo',title:'4. Country and timezone detection',paragraphs:['During initial setup FlowPay may use hosting geolocation headers to suggest a country and timezone. This is only an initial suggestion; the user can change country and reporting currency before saving.']},
      {id:'providers',title:'5. Service providers and recipients',paragraphs:['FlowPay may use cloud hosting, database, authentication, delivery, security monitoring and other technical providers. They receive only information necessary for their function and are subject to contractual and technical restrictions.','FlowPay does not sell personal data to advertisers. Data may be disclosed to public authorities where a valid legal requirement applies.']},
      {id:'transfers',title:'6. International transfers',paragraphs:['Infrastructure providers may process data in different countries. Where applicable law requires safeguards for international transfers, the FlowPay operator must implement the appropriate transfer mechanism.']},
      {id:'retention',title:'7. Retention',paragraphs:['Account and workspace data is retained while the account is active and as needed to provide the service. Security logs, payment records and other information may be retained longer where needed for abuse prevention, incident investigation, disputes, accounting or mandatory legal obligations.','Data is deleted or anonymised when no longer needed and no lawful retention basis remains.']},
      {id:'security',title:'8. Security',paragraphs:['FlowPay uses access controls, user data isolation, encrypted transport, API restrictions, security logging and other technical measures. Users are responsible for protecting passwords, API keys and signed-in devices.','No internet service can guarantee absolute security. Suspected compromise should be reported promptly and affected credentials revoked.']},
      {id:'rights',title:'9. Individual rights',paragraphs:['Depending on applicable law, individuals may have rights of access, correction, deletion, restriction, portability, objection and complaint to a competent supervisory authority.','Where a particular processing activity is based on consent, consent can be withdrawn for future processing.']},
      {id:'business',title:'10. Personal data uploaded by organisations',paragraphs:['Users and their organisations may enter information about employees, counterparties and beneficiaries. The organisation must have a lawful basis to provide that information and must give required notices to those individuals.']},
      {id:'changes',title:'11. Changes',paragraphs:['This Policy may be updated when the product, law or infrastructure changes. Material changes should be clearly notified. New processing that requires consent will be presented separately.']},
    ],
  },
}

export const termsDocuments: Record<'ru'|'en', LegalDocument> = {
  ru:{
    title:'Условия использования FlowPay',shortTitle:'Условия использования',updated:'Версия от 17 августа 2026 года',
    intro:'Эти Условия регулируют использование веб-сервиса FlowPay и связанных API. Создавая аккаунт, пользователь подтверждает, что действует от своего имени либо имеет полномочия действовать от имени соответствующей организации.',
    sections:[
      {id:'service',title:'1. Сервис FlowPay',paragraphs:['FlowPay предоставляет программные инструменты для организации международных платёжных процессов, ведения контрагентов и счетов, сравнения доступных платёжных маршрутов, аналитики и API-интеграций.','Если прямо не указано иное в отдельном договоре, FlowPay не является банком, платёжной организацией, кастодианом или финансовым советником и не принимает средства пользователей на хранение.']},
      {id:'eligibility',title:'2. Право на использование и полномочия',paragraphs:['Пользователь должен иметь право заключать договоры согласно применимому законодательству и, если аккаунт создаётся для компании, иметь необходимые полномочия связывать эту компанию настоящими Условиями. Пользователь обязан предоставлять точные данные и поддерживать их актуальность.']},
      {id:'account',title:'3. Аккаунт и безопасность',paragraphs:['Аккаунт является персональным для конкретного пользователя. Нельзя передавать пароль другим лицам. Доступ коллег должен предоставляться через предусмотренные FlowPay роли и приглашения.','Пользователь отвечает за действия, выполненные с использованием его учётных данных, если иное не следует из обязательного закона. О подозрительной активности необходимо сообщать без неоправданной задержки.']},
      {id:'payments',title:'4. Платёжные данные и расчёты',paragraphs:['FlowPay может отображать комиссии, сроки, валютные курсы, прогнозы и рейтинги маршрутов. Такие данные являются информационными и зависят от доступности и актуальности источников. Окончательные условия платежа определяет фактический платёжный провайдер или банк.','До отправки средств пользователь обязан самостоятельно проверить получателя, реквизиты, сумму, валюту, комиссии, санкционные/регуляторные ограничения и финальные условия провайдера.']},
      {id:'api',title:'5. API и ключи доступа',paragraphs:['API-ключи должны храниться как секреты и использоваться только авторизованными системами пользователя. Запрещено публиковать ключи в открытом коде, передавать посторонним лицам или обходить ограничения API. FlowPay может применять rate limits и временно блокировать ключ при подозрительной активности.']},
      {id:'acceptable',title:'6. Допустимое использование',paragraphs:['Запрещено использовать FlowPay для мошенничества, незаконных операций, обхода санкций или обязательных ограничений, отмывания денежных средств, нарушения прав третьих лиц, вредоносного сканирования, вмешательства в работу сервиса, массового извлечения данных или обхода технических ограничений.','FlowPay может ограничить или приостановить доступ, если это разумно необходимо для безопасности, предотвращения злоупотреблений, соблюдения закона или защиты других пользователей.']},
      {id:'data',title:'7. Данные пользователя',paragraphs:['Пользователь сохраняет права на законно загруженные им данные. Он предоставляет FlowPay право обрабатывать эти данные в объёме, необходимом для работы сервиса, безопасности, резервирования, поддержки и выполнения инструкций пользователя.','Пользователь гарантирует, что имеет право передавать FlowPay данные контрагентов, сотрудников и иных лиц.']},
      {id:'availability',title:'8. Доступность и изменения',paragraphs:['FlowPay развивается и может изменять интерфейс, API, лимиты и функции. Мы стремимся избегать необоснованных перерывов, но не гарантируем абсолютную непрерывность работы. Внешние поставщики, банки, интернет-инфраструктура и форс-мажорные события могут влиять на доступность.']},
      {id:'fees',title:'9. Тарифы и оплата',paragraphs:['Если вводятся платные тарифы, их цена, период оплаты, включённые лимиты и правила отмены должны быть показаны до оформления заказа. Дополнительные условия конкретного платного плана могут быть частью заказа или отдельного договора.']},
      {id:'ip',title:'10. Интеллектуальная собственность',paragraphs:['FlowPay, интерфейс, программный код, дизайн, документация и товарные обозначения защищаются применимым законодательством. Пользователю предоставляется ограниченное неисключительное право использовать сервис в рамках настоящих Условий.']},
      {id:'liability',title:'11. Ограничение ответственности',paragraphs:['В пределах, допускаемых применимым законодательством, FlowPay не отвечает за решения, принятые исключительно на основании ориентировочных расчётов, за действия внешних банков и провайдеров, а также за косвенные убытки, вызванные недоступностью внешней инфраструктуры.','Ничто в настоящих Условиях не исключает ответственность, которую нельзя исключить или ограничить по обязательному закону. Конкретный денежный предел ответственности должен быть закреплён в коммерческом договоре или тарифных условиях до платного запуска.']},
      {id:'termination',title:'12. Прекращение использования',paragraphs:['Пользователь может прекратить использование сервиса и удалить аккаунт через доступные настройки, если это не противоречит обязательному хранению отдельных записей. FlowPay может прекратить или ограничить доступ при существенном нарушении Условий, угрозе безопасности или юридической необходимости.']},
      {id:'law',title:'13. Применимое право и споры',paragraphs:['До коммерческого запуска оператор FlowPay обязан указать применимое право, юрисдикцию/порядок разрешения споров и свои полные юридические реквизиты. Обязательные права, которые нельзя исключить соглашением, сохраняются независимо от выбранного права.']},
      {id:'changes',title:'14. Изменения Условий',paragraphs:['FlowPay может обновлять Условия. Существенные изменения должны быть доведены до пользователя до их вступления в силу. Если изменения требуют нового принятия, доступ к соответствующим функциям может быть приостановлен до подтверждения новой версии.']},
    ],
  },
  en:{
    title:'FlowPay Terms of Service',shortTitle:'Terms of Service',updated:'Version dated 17 August 2026',
    intro:'These Terms govern use of the FlowPay web service and related APIs. By creating an account, a user confirms that they act for themselves or have authority to act for the relevant organisation.',
    sections:[
      {id:'service',title:'1. The FlowPay service',paragraphs:['FlowPay provides software tools for international payment operations, counterparties and invoices, payment route comparison, analytics and API integrations.','Unless a separate agreement expressly says otherwise, FlowPay is not a bank, payment institution, custodian or financial adviser and does not hold customer funds.']},
      {id:'eligibility',title:'2. Eligibility and authority',paragraphs:['Users must have legal capacity to enter into contracts under applicable law and, where an account is created for an organisation, authority to bind that organisation. Information supplied must be accurate and kept current.']},
      {id:'account',title:'3. Account security',paragraphs:['Credentials must not be shared. Colleague access should be granted through FlowPay roles and invitations. Users are responsible for activity performed with their credentials to the extent permitted by mandatory law and should report suspicious activity promptly.']},
      {id:'payments',title:'4. Payment information and estimates',paragraphs:['FlowPay may show fees, timings, FX rates, forecasts and route scores. Such information is informational and depends on source availability and freshness. Final payment terms are set by the actual bank or payment provider.','Users must verify beneficiary details, amount, currency, fees, regulatory restrictions and final provider terms before sending funds.']},
      {id:'api',title:'5. API access',paragraphs:['API keys must be stored as secrets and used only by authorised user systems. Publishing keys, sharing them with unauthorised parties or bypassing API restrictions is prohibited. FlowPay may apply rate limits or disable a key when suspicious activity is detected.']},
      {id:'acceptable',title:'6. Acceptable use',paragraphs:['FlowPay must not be used for fraud, unlawful activity, sanctions or regulatory evasion, money laundering, infringement of third-party rights, malicious scanning, service interference, mass scraping or circumvention of technical restrictions.','Access may be restricted where reasonably necessary for security, abuse prevention, legal compliance or protection of other users.']},
      {id:'data',title:'7. User data',paragraphs:['Users retain rights in data they lawfully upload and grant FlowPay permission to process it as needed to operate, secure, back up and support the service and follow user instructions. Users represent that they may lawfully provide information about counterparties, employees and other individuals.']},
      {id:'availability',title:'8. Availability and changes',paragraphs:['FlowPay may change interfaces, APIs, limits and features as the product develops. Absolute uninterrupted availability is not guaranteed. External providers, banks, internet infrastructure and force-majeure events may affect availability.']},
      {id:'fees',title:'9. Paid plans',paragraphs:['If paid plans are offered, price, billing period, included limits and cancellation terms must be disclosed before purchase. Additional plan terms may form part of the order or a separate business agreement.']},
      {id:'ip',title:'10. Intellectual property',paragraphs:['FlowPay software, interface, design, documentation and branding are protected by applicable law. Users receive a limited, non-exclusive right to use the service in accordance with these Terms.']},
      {id:'liability',title:'11. Liability',paragraphs:['To the extent permitted by applicable law, FlowPay is not responsible for decisions based solely on indicative estimates, acts of external banks/providers or indirect loss caused by external infrastructure outages. Nothing excludes liability that cannot legally be excluded. A commercial liability cap should be specified before paid launch.']},
      {id:'termination',title:'12. Termination',paragraphs:['Users may stop using the service and delete their account subject to mandatory record-retention requirements. FlowPay may restrict or terminate access for material breach, security threats or legal necessity.']},
      {id:'law',title:'13. Governing law and disputes',paragraphs:['Before commercial launch, the FlowPay operator must specify its full legal details, governing law and dispute-resolution forum. Mandatory non-waivable rights remain unaffected.']},
      {id:'changes',title:'14. Changes to these Terms',paragraphs:['Material changes should be notified before they take effect. Where a change requires renewed acceptance, access to affected functions may be paused until the new version is accepted.']},
    ],
  },
}

export function legalDocument(kind:'privacy'|'terms',lang:string){
  const source=kind==='privacy'?privacyDocuments:termsDocuments
  return source[lang==='ru'?'ru':'en']
}
