import type { Language, PaymentDraft } from './types'

export function locale(lang:Language){return lang==='ru'?'ru-RU':lang==='fr'?'fr-FR':lang==='de'?'de-DE':lang==='es'?'es-ES':'en-US'}
export function money(value:number|null|undefined,currency:string,lang:Language,compact=false){if(value==null||!Number.isFinite(Number(value)))return '—';return new Intl.NumberFormat(locale(lang),{style:'currency',currency,notation:compact?'compact':'standard',maximumFractionDigits:compact?1:2}).format(Number(value))}
export function number(value:number|null|undefined,lang:Language,maximumFractionDigits=1){if(value==null||!Number.isFinite(Number(value)))return '—';return new Intl.NumberFormat(locale(lang),{maximumFractionDigits}).format(Number(value))}
export function dateLabel(value:string|null|undefined,lang:Language,withYear=true){if(!value)return '—';return new Intl.DateTimeFormat(locale(lang),{day:'numeric',month:'short',...(withYear?{year:'numeric'}:{})}).format(new Date(value))}
export function relativeDate(value:string|null|undefined,lang:Language){if(!value)return '—';const diff=Math.round((new Date(value).getTime()-Date.now())/86400000);const rtf=new Intl.RelativeTimeFormat(locale(lang),{numeric:'auto'});if(Math.abs(diff)<30)return rtf.format(diff,'day');return dateLabel(value,lang)}
export function speedLabel(minutes:number|null|undefined,lang:Language){if(minutes==null)return '—';if(minutes<60)return `${Math.round(minutes)} min`;if(minutes<1440)return `${Math.round(minutes/60*10)/10} h`;const d=Math.max(1,Math.round(minutes/1440));return lang==='ru'?`${d} дн.`:lang==='fr'?`${d} j`:lang==='de'?`${d} T`:lang==='es'?`${d} d`:`${d} days`}
export function normalize(value:number,currency:string,base:string|null,rates:Record<string,number>){if(!base)return null;if(currency===base)return value;const rate=rates[currency];return typeof rate==='number'&&Number.isFinite(rate)?value*rate:null}
export function paymentEventDate(p:PaymentDraft){return p.received_at||p.paid_at||p.updated_at||p.created_at}
export function isSettled(p:PaymentDraft){return p.status==='paid'||p.status==='received'}
export function isOutstanding(p:PaymentDraft){return p.status==='draft'||p.status==='ready'||p.status==='failed'}
export function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
export function dayDiff(value:string|null|undefined){if(!value)return null;return Math.round((startOfDay(new Date(value)).getTime()-startOfDay().getTime())/86400000)}
export function healthScore(payments:PaymentDraft[],avgFeePct:number|null){const relevant=payments.filter(p=>p.status!=='cancelled');if(relevant.length<2)return null;const settled=relevant.filter(isSettled);const success=relevant.length?settled.length/relevant.length:0;const dueWithCompletion=settled.filter(p=>p.due_date&&(p.paid_at||p.received_at));const onTime=dueWithCompletion.length?dueWithCompletion.filter(p=>{const completed=p.paid_at||p.received_at;return completed!=null&&new Date(completed)<=new Date(`${p.due_date}T23:59:59`)}).length/dueWithCompletion.length:1;if(avgFeePct==null)return null;const fee=Math.max(0,Math.min(1,1-avgFeePct/3));return Math.round((success*.35+onTime*.35+fee*.30)*100)}
export function monthLabel(date:Date,lang:Language){return new Intl.DateTimeFormat(locale(lang),{month:'short'}).format(date)}
export function providerLabel(code:string){return code.replaceAll('_',' ').replaceAll('-',' ').trim().replace(/\b\w/g,(c)=>c.toUpperCase())}
export function csvEscape(value:unknown){const text=value==null?'':String(value);return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}
export function downloadCsv(filename:string,headers:string[],rows:unknown[][]){const content='\uFEFF'+[headers,...rows].map(row=>row.map(csvEscape).join(',')).join('\n');const blob=new Blob([content],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
