import type { Language } from './types'

const en = {
  nav:{overview:'Overview',payments:'Payments',counterparties:'Counterparties',routes:'Routes',analytics:'Analytics',reports:'Reports',invoices:'Invoices',team:'Team',api:'API',settings:'Settings'},
  common:{search:'Search payments, counterparties, routes…',newPayment:'Create payment',save:'Save changes',cancel:'Cancel',edit:'Edit',delete:'Delete',close:'Close',add:'Add',import:'Import',export:'Export',filters:'Filters',all:'All',loading:'Loading…',noData:'No data yet',viewAll:'View all',viewDetails:'View details',amount:'Amount',currency:'Currency',country:'Country',status:'Status',dueDate:'Due date',provider:'Provider',fee:'Fee',speed:'Speed',score:'Score',date:'Date',reference:'Reference',actions:'Actions',from:'From',to:'To',thisMonth:'This month',refresh:'Refresh',realData:'Account activity'},
  shell:{setupRequired:'FlowPay is temporarily unavailable',setupText:'We could not load your account data. Refresh the page in a moment. If the problem continues, contact FlowPay support.',help:'Need help?',helpText:'Manage your company details, payment preferences and connected services in Settings.',command:'Search or jump to…',signOut:'Sign out',notifications:'Activity',noNotifications:'No recent activity'},
  overview:{title:'Overview',subtitle:'Your international payment operations at a glance.',volume:'Payment volume',savings:'Estimated savings',counterparties:'Active counterparties',efficiency:'Payment efficiency',routes:'Route explorer',compare:'Compare routes',upcoming:'Upcoming payments',topCounterparties:'Top counterparties',activity:'Recent activity',fx:'Market rates',health:'Health score',configureBase:'Choose a reporting currency to see totals in one currency.',noPayments:'Create your first payment to start tracking payment activity and performance.',noRoutes:'No payment routes are available yet. Run a comparison or connect a payment provider to get started.'},
  payments:{title:'Payments',subtitle:'Plan, review and track supplier payments.',dueWeek:'Due this week',scheduled:'Scheduled amount',overdue:'Overdue payments',volume:'Total monthly volume',create:'Create payment',search:'Search by invoice, counterparty or route…',draft:'Draft',ready:'Ready to pay',paid:'Paid',received:'Received',invoice:'Invoice',counterparty:'Counterparty',route:'Route',recipientGets:'Recipient gets',reviewSend:'Review',markPaid:'Mark paid',markReceived:'Mark received',empty:'No payments match these filters.'},
  counterparties:{title:'Counterparties',subtitle:'Manage saved suppliers and recipients.',create:'Add counterparty',search:'Search counterparties…',allCountries:'All countries',allCurrencies:'All currencies',allVerification:'All payment details',company:'Counterparty',lastPayment:'Last payment',totalSent:'Total sent',payments:'Payments',verification:'Payment details',bankDetails:'Bank details',bankName:'Bank name',account:'IBAN / account',bic:'SWIFT / BIC',accountHolder:'Account holder',lastInvoices:'Last invoices',recentActivity:'Recent payment activity',verificationStatus:'Verification status',empty:'No counterparties yet.'},
  routes:{title:'Routes',subtitle:'Compare available international payment routes by cost, speed and reliability.',source:'Source country',destination:'Destination country',sending:'Sending amount',recipientCurrency:'Recipient currency',explore:'Explore routes',selected:'Selected route',best:'Best overall',totalCost:'Total cost',youSave:'You save',fxSpread:'FX spread',intermediaries:'Intermediary banks',reliability:'Reliability',routeFlow:'Route flow',why:'Why this route?',options:'Route options',compare:'Compare routes',noRoutes:'No route is available for this corridor and amount yet. Try another currency or amount.',estimate:'Route costs and delivery times are estimates and may change before payment execution.'},
  analytics:{title:'Analytics',subtitle:'Measure performance, trends and international payment efficiency.',totalVolume:'Total volume',totalSavings:'Total savings',averageFee:'Average fee',settlement:'Average settlement time',volumeTime:'Payment volume over time',savingsBreakdown:'Savings breakdown',currency:'Volume by currency',country:'Volume by country',route:'Volume by route',provider:'Volume by provider',health:'Payment health score',distribution:'Settlement time distribution',partial:'Some currencies could not be converted into your reporting currency for this period.'},
  reports:{title:'Reports',subtitle:'Export current payment, savings, counterparty and integration data for reconciliation and analysis.',payments:'Payments report',savings:'Savings report',counterparties:'Counterparties report',api:'API usage report',download:'Download CSV',empty:'There is no data to export for this report yet.'},
  invoices:{title:'Invoices',subtitle:'Track supplier invoices and link them to payments.',create:'Add invoice',open:'Open',scheduled:'Scheduled',paid:'Paid',cancelled:'Cancelled',empty:'No invoices yet.',linkPayment:'Linked payment'},
  team:{title:'Team',subtitle:'Invite teammates and manage access to your FlowPay account.',invite:'Invite member',email:'Email',role:'Role',pending:'Pending invitations',owner:'Account owner',empty:'No invitations yet.'},
  api:{title:'API',subtitle:'Connect your systems to FlowPay and monitor API activity.',create:'Create API key',keys:'API keys',usage:'Request activity',lastUsed:'Last used',revoke:'Revoke',secretOnce:'Copy this secret now. For security, it will only be shown once.',noKeys:'No API keys yet.',noUsage:'No API requests recorded yet.'},
  settings:{title:'Settings',subtitle:'Manage organization preferences and payment defaults.',company:'Company profile',companyHint:'Company information shown across your FlowPay account.',base:'Base currency',baseHint:'Used as the reporting currency for dashboards, analytics and exports.',notifications:'Notification preferences',security:'Security',payout:'Payment defaults',providers:'Payment partners',language:'Language',registration:'Registration number',address:'Business address',country:'Company country',save:'Save changes',noProviders:'No payment partners are available yet.'}
}

type WorkspaceDictionary=typeof en
function merge<T extends Record<string,any>>(base:T, patch:Partial<T>):T { const out:any={...base}; for(const [k,v] of Object.entries(patch)){out[k]=v&&typeof v==='object'&&!Array.isArray(v)?{...(base as any)[k],...v}:v} return out }

const ru=merge(en,{
  nav:{...en.nav,overview:'Обзор',payments:'Платежи',counterparties:'Контрагенты',routes:'Маршруты',analytics:'Аналитика',reports:'Отчёты',invoices:'Счета',team:'Команда',settings:'Настройки'},
  common:{...en.common,search:'Поиск платежей, контрагентов, маршрутов…',newPayment:'Создать платёж',save:'Сохранить',cancel:'Отмена',edit:'Изменить',delete:'Удалить',import:'Импорт',export:'Экспорт',filters:'Фильтры',all:'Все',loading:'Загрузка…',noData:'Пока нет данных',viewAll:'Показать все',viewDetails:'Подробнее',amount:'Сумма',currency:'Валюта',country:'Страна',status:'Статус',dueDate:'Срок',provider:'Провайдер',fee:'Комиссия',speed:'Скорость',score:'Оценка',date:'Дата',reference:'Референс',actions:'Действия',from:'Откуда',to:'Куда',thisMonth:'Этот месяц',refresh:'Обновить',realData:'Активность аккаунта'},
  shell:{...en.shell,setupRequired:'FlowPay временно недоступен',setupText:'Не удалось загрузить данные аккаунта. Обновите страницу через минуту. Если проблема повторится, обратитесь в поддержку FlowPay.',help:'Нужна помощь?',helpText:'Управляйте реквизитами компании, платежными настройками и подключениями в разделе «Настройки».',command:'Поиск или быстрый переход…',signOut:'Выйти',notifications:'Активность',noNotifications:'Новой активности нет'},
  overview:{...en.overview,title:'Обзор',subtitle:'Международные платежи и эффективность в одном экране.',volume:'Объём платежей',savings:'Расчётная экономия',counterparties:'Активные контрагенты',efficiency:'Эффективность платежей',routes:'Маршруты',compare:'Сравнить маршруты',upcoming:'Ближайшие платежи',topCounterparties:'Основные контрагенты',activity:'Последняя активность',fx:'Рыночные курсы',health:'Оценка эффективности',configureBase:'Выберите валюту отчётности, чтобы видеть общие показатели в одной валюте.',noPayments:'Создайте первый платёж — здесь появятся история операций и показатели эффективности.',noRoutes:'Пока нет доступных маршрутов. Выполните сравнение или подключите платежного партнёра.'},
  payments:{...en.payments,title:'Платежи',subtitle:'Планирование, проверка и отслеживание платежей поставщикам.',dueWeek:'К оплате на неделе',scheduled:'Запланировано',overdue:'Просрочено',volume:'Объём за месяц',create:'Создать платёж',search:'Поиск по счёту, контрагенту или маршруту…',draft:'Черновик',ready:'Готов к оплате',paid:'Оплачен',received:'Получен',invoice:'Счёт',counterparty:'Контрагент',route:'Маршрут',recipientGets:'Получатель получит',reviewSend:'Проверить',markPaid:'Отметить оплаченным',markReceived:'Отметить полученным',empty:'Под эти фильтры платежей нет.'},
  counterparties:{...en.counterparties,title:'Контрагенты',subtitle:'Поставщики, получатели и платёжные реквизиты.',create:'Добавить контрагента',search:'Поиск контрагентов…',allCountries:'Все страны',allCurrencies:'Все валюты',allVerification:'Все реквизиты',company:'Контрагент',lastPayment:'Последний платёж',totalSent:'Всего отправлено',payments:'Платежи',verification:'Реквизиты',bankDetails:'Банковские реквизиты',bankName:'Банк',account:'IBAN / счёт',bic:'SWIFT / BIC',accountHolder:'Владелец счёта',lastInvoices:'Последние счета',recentActivity:'Последние платежи',verificationStatus:'Статус проверки',empty:'Контрагентов пока нет.'},
  routes:{...en.routes,title:'Маршруты',subtitle:'Сравнивайте международные маршруты по стоимости, скорости и надёжности.',source:'Страна отправителя',destination:'Страна получателя',sending:'Сумма отправки',recipientCurrency:'Валюта получателя',explore:'Найти маршруты',selected:'Выбранный маршрут',best:'Лучший вариант',totalCost:'Полная стоимость',youSave:'Экономия',fxSpread:'FX-наценка',intermediaries:'Банки-посредники',reliability:'Надёжность',routeFlow:'Путь платежа',why:'Почему этот маршрут?',options:'Варианты',compare:'Сравнение маршрутов',noRoutes:'Для этого направления и суммы пока нет доступных маршрутов. Попробуйте другую валюту или сумму.',estimate:'Стоимость и сроки являются предварительной оценкой и могут измениться до исполнения платежа.'},
  analytics:{...en.analytics,title:'Аналитика',subtitle:'Реальные показатели международных платежей и расходов.',totalVolume:'Общий объём',totalSavings:'Экономия',averageFee:'Средняя комиссия',settlement:'Среднее зачисление',volumeTime:'Объём платежей во времени',savingsBreakdown:'Структура экономии',currency:'Объём по валютам',country:'Объём по странам',route:'Объём по направлениям',provider:'Объём по провайдерам',health:'Эффективность платежей',distribution:'Распределение по сроку зачисления',partial:'Некоторые валюты не удалось перевести в базовую валюту отчётности за выбранный период.'},
  reports:{...en.reports,title:'Отчёты',subtitle:'Выгружайте актуальные данные по платежам, экономии, контрагентам и интеграциям для сверки и анализа.',payments:'Отчёт по платежам',savings:'Отчёт по экономии',counterparties:'Отчёт по контрагентам',api:'Отчёт по API',download:'Скачать CSV',empty:'Для этого отчёта пока нет данных.'},
  invoices:{...en.invoices,title:'Счета',subtitle:'Учёт счетов поставщиков и привязка к платежам.',create:'Добавить счёт',open:'Открыт',scheduled:'Запланирован',paid:'Оплачен',cancelled:'Отменён',empty:'Счетов пока нет.',linkPayment:'Связанный платёж'},
  team:{...en.team,title:'Команда',subtitle:'Приглашайте сотрудников финансовой команды и назначайте роли.',invite:'Пригласить',email:'Email',role:'Роль',pending:'Ожидают приглашения',owner:'Владелец аккаунта',empty:'Приглашений пока нет.'},
  api:{...en.api,title:'API',subtitle:'Подключайте свои системы к FlowPay и отслеживайте использование API.',create:'Создать API-ключ',keys:'API-ключи',usage:'Запросы API',lastUsed:'Последнее использование',revoke:'Отозвать',secretOnce:'Скопируйте ключ сейчас — в целях безопасности он показывается только один раз.',noKeys:'API-ключей пока нет.',noUsage:'Запросов к API пока не было.'},
  settings:{...en.settings,title:'Настройки',subtitle:'Параметры организации и платежей.',company:'Профиль компании',companyHint:'Данные компании, которые используются в FlowPay.',base:'Базовая валюта',baseHint:'Основная валюта для дашборда, аналитики и отчётов.',notifications:'Уведомления',security:'Безопасность',payout:'Платёжные настройки',providers:'Платёжные партнёры',language:'Язык',registration:'Регистрационный номер',address:'Адрес компании',country:'Страна компании',save:'Сохранить',noProviders:'Платёжные партнёры пока не доступны для вашей компании.'}
})

const fr=merge(en,{
  nav:{...en.nav,overview:'Aperçu',payments:'Paiements',counterparties:'Contreparties',routes:'Routes',analytics:'Analytique',reports:'Rapports',invoices:'Factures',team:'Équipe',api:'API',settings:'Paramètres'},
  common:{...en.common,search:'Rechercher des paiements, contreparties, routes…',newPayment:'Créer un paiement',save:'Enregistrer',cancel:'Annuler',edit:'Modifier',delete:'Supprimer',close:'Fermer',add:'Ajouter',import:'Importer',export:'Exporter',filters:'Filtres',all:'Tous',loading:'Chargement…',noData:'Aucune donnée',viewAll:'Voir tout',viewDetails:'Voir les détails',amount:'Montant',currency:'Devise',country:'Pays',status:'Statut',dueDate:'Échéance',provider:'Partenaire',fee:'Frais',speed:'Délai',score:'Score',date:'Date',reference:'Référence',actions:'Actions',from:'Depuis',to:'Vers',thisMonth:'Ce mois-ci',refresh:'Actualiser',realData:'Activité du compte'},
  shell:{...en.shell,setupRequired:'FlowPay est temporairement indisponible',setupText:'Impossible de charger les données de votre compte. Réessayez dans un instant. Si le problème persiste, contactez le support FlowPay.',help:'Besoin d’aide ?',helpText:'Gérez les informations de l’entreprise, les préférences de paiement et les connexions dans Paramètres.',command:'Rechercher ou accéder à…',signOut:'Se déconnecter',notifications:'Activité',noNotifications:'Aucune activité récente'},
  overview:{...en.overview,title:'Aperçu',subtitle:'Vos opérations de paiement international en un coup d’œil.',volume:'Volume de paiements',savings:'Économies estimées',counterparties:'Contreparties actives',efficiency:'Efficacité des paiements',routes:'Routes',compare:'Comparer les routes',upcoming:'Paiements à venir',topCounterparties:'Principales contreparties',activity:'Activité récente',fx:'Taux de marché',health:'Score d’efficacité',configureBase:'Choisissez une devise de reporting pour afficher les totaux dans une seule devise.',noPayments:'Créez votre premier paiement pour commencer à suivre l’activité et la performance.',noRoutes:'Aucune route de paiement n’est disponible pour le moment. Lancez une comparaison ou activez un partenaire de paiement.'},
  payments:{...en.payments,title:'Paiements',subtitle:'Planifiez, contrôlez et suivez les paiements fournisseurs.',dueWeek:'À payer cette semaine',scheduled:'Montant planifié',overdue:'Paiements en retard',volume:'Volume mensuel',create:'Créer un paiement',search:'Rechercher par facture, contrepartie ou route…',draft:'Brouillon',ready:'Prêt à payer',paid:'Payé',received:'Reçu',invoice:'Facture',counterparty:'Contrepartie',route:'Route',recipientGets:'Le bénéficiaire reçoit',reviewSend:'Vérifier',markPaid:'Marquer payé',markReceived:'Marquer reçu',empty:'Aucun paiement ne correspond à ces filtres.'},
  counterparties:{...en.counterparties,title:'Contreparties',subtitle:'Gérez fournisseurs, bénéficiaires et coordonnées de paiement.',create:'Ajouter une contrepartie',search:'Rechercher des contreparties…',allCountries:'Tous les pays',allCurrencies:'Toutes les devises',allVerification:'Toutes les coordonnées',company:'Contrepartie',lastPayment:'Dernier paiement',totalSent:'Total envoyé',payments:'Paiements',verification:'Coordonnées',bankDetails:'Coordonnées bancaires',bankName:'Banque',account:'IBAN / compte',bic:'SWIFT / BIC',accountHolder:'Titulaire du compte',lastInvoices:'Dernières factures',recentActivity:'Paiements récents',verificationStatus:'État des coordonnées',empty:'Aucune contrepartie pour le moment.'},
  routes:{...en.routes,title:'Routes',subtitle:'Comparez les options de paiement internationales par coût, délai et fiabilité.',source:'Pays d’envoi',destination:'Pays de réception',sending:'Montant envoyé',recipientCurrency:'Devise reçue',explore:'Rechercher des routes',selected:'Route sélectionnée',best:'Meilleur choix',totalCost:'Coût total',youSave:'Économie',fxSpread:'Marge FX',intermediaries:'Banques intermédiaires',reliability:'Fiabilité',routeFlow:'Parcours du paiement',why:'Pourquoi cette route ?',options:'Options',compare:'Comparer les routes',noRoutes:'Aucune route n’est disponible pour ce corridor et ce montant. Essayez une autre devise ou un autre montant.',estimate:'Les coûts et délais sont estimatifs et peuvent évoluer avant l’exécution du paiement.'},
  analytics:{...en.analytics,title:'Analytique',subtitle:'Mesurez la performance, les tendances et les coûts de vos paiements internationaux.',totalVolume:'Volume total',totalSavings:'Économies totales',averageFee:'Frais moyens',settlement:'Délai moyen',volumeTime:'Volume des paiements dans le temps',savingsBreakdown:'Répartition des économies',currency:'Volume par devise',country:'Volume par pays',route:'Volume par route',provider:'Volume par partenaire',health:'Efficacité des paiements',distribution:'Répartition des délais',partial:'Certaines devises n’ont pas pu être converties dans votre devise de reporting pour cette période.'},
  reports:{...en.reports,title:'Rapports',subtitle:'Exportez les données actuelles de paiement, d’économies, de contreparties et d’API pour le rapprochement et l’analyse.',payments:'Rapport des paiements',savings:'Rapport des économies',counterparties:'Rapport des contreparties',api:'Rapport d’utilisation API',download:'Télécharger le CSV',empty:'Aucune donnée à exporter pour ce rapport.'},
  invoices:{...en.invoices,title:'Factures',subtitle:'Suivez les factures fournisseurs et reliez-les aux paiements.',create:'Ajouter une facture',open:'Ouverte',scheduled:'Planifiée',paid:'Payée',cancelled:'Annulée',empty:'Aucune facture pour le moment.',linkPayment:'Paiement lié'},
  api:{...en.api,title:'API',subtitle:'Connectez vos systèmes à FlowPay et suivez l’activité API.',create:'Créer une clé API',keys:'Clés API',usage:'Activité des requêtes',lastUsed:'Dernière utilisation',revoke:'Révoquer',secretOnce:'Copiez ce secret maintenant. Pour votre sécurité, il ne sera affiché qu’une seule fois.',noKeys:'Aucune clé API.',noUsage:'Aucune requête API enregistrée.'},
  settings:{...en.settings,title:'Paramètres',subtitle:'Gérez les préférences de l’entreprise et les valeurs par défaut des paiements.',company:'Profil de l’entreprise',companyHint:'Informations de l’entreprise utilisées dans FlowPay.',base:'Devise de reporting',baseHint:'Devise utilisée pour les tableaux de bord, analyses et exports.',notifications:'Préférences d’activité',security:'Sécurité',payout:'Paramètres de paiement',providers:'Connexions de paiement',language:'Langue',registration:'Numéro d’immatriculation',address:'Adresse de l’entreprise',country:'Pays de l’entreprise',save:'Enregistrer',noProviders:'Aucun partenaire de paiement n’est disponible pour le moment.'}
})
const de=merge(en,{
  nav:{...en.nav,overview:'Übersicht',payments:'Zahlungen',counterparties:'Geschäftspartner',routes:'Routen',analytics:'Analyse',reports:'Berichte',invoices:'Rechnungen',team:'Team',api:'API',settings:'Einstellungen'},
  common:{...en.common,search:'Zahlungen, Geschäftspartner und Routen suchen…',newPayment:'Zahlung erstellen',save:'Speichern',cancel:'Abbrechen',edit:'Bearbeiten',delete:'Löschen',close:'Schließen',add:'Hinzufügen',import:'Importieren',export:'Exportieren',filters:'Filter',all:'Alle',loading:'Laden…',noData:'Noch keine Daten',viewAll:'Alle anzeigen',viewDetails:'Details anzeigen',amount:'Betrag',currency:'Währung',country:'Land',status:'Status',dueDate:'Fällig am',provider:'Partner',fee:'Gebühr',speed:'Dauer',score:'Score',date:'Datum',reference:'Referenz',actions:'Aktionen',from:'Von',to:'Nach',thisMonth:'Diesen Monat',refresh:'Aktualisieren',realData:'Kontoaktivität'},
  shell:{...en.shell,setupRequired:'FlowPay ist vorübergehend nicht verfügbar',setupText:'Ihre Kontodaten konnten nicht geladen werden. Versuchen Sie es in Kürze erneut. Wenn das Problem bleibt, wenden Sie sich an den FlowPay-Support.',help:'Hilfe benötigt?',helpText:'Unter Einstellungen verwalten Sie Firmendaten, Zahlungsvorgaben und Verbindungen.',command:'Suchen oder direkt öffnen…',signOut:'Abmelden',notifications:'Aktivität',noNotifications:'Keine neue Aktivität'},
  overview:{...en.overview,title:'Übersicht',subtitle:'Ihre internationalen Zahlungsvorgänge auf einen Blick.',volume:'Zahlungsvolumen',savings:'Geschätzte Einsparungen',counterparties:'Aktive Geschäftspartner',efficiency:'Zahlungseffizienz',routes:'Routen',compare:'Routen vergleichen',upcoming:'Anstehende Zahlungen',topCounterparties:'Wichtigste Geschäftspartner',activity:'Letzte Aktivität',fx:'Marktkurse',health:'Effizienz-Score',configureBase:'Wählen Sie eine Berichtswährung, um Summen in einer Währung anzuzeigen.',noPayments:'Erstellen Sie Ihre erste Zahlung, um Aktivität und Performance zu verfolgen.',noRoutes:'Noch keine Zahlungsroute verfügbar. Starten Sie einen Vergleich oder aktivieren Sie einen Zahlungspartner.'},
  payments:{...en.payments,title:'Zahlungen',subtitle:'Lieferantenzahlungen planen, prüfen und verfolgen.',dueWeek:'Diese Woche fällig',scheduled:'Geplanter Betrag',overdue:'Überfällige Zahlungen',volume:'Monatsvolumen',create:'Zahlung erstellen',search:'Nach Rechnung, Geschäftspartner oder Route suchen…',draft:'Entwurf',ready:'Zahlungsbereit',paid:'Bezahlt',received:'Empfangen',invoice:'Rechnung',counterparty:'Geschäftspartner',route:'Route',recipientGets:'Empfänger erhält',reviewSend:'Prüfen',markPaid:'Als bezahlt markieren',markReceived:'Als empfangen markieren',empty:'Keine Zahlungen entsprechen diesen Filtern.'},
  counterparties:{...en.counterparties,title:'Geschäftspartner',subtitle:'Lieferanten, Empfänger und Zahlungsdaten verwalten.',create:'Geschäftspartner hinzufügen',search:'Geschäftspartner suchen…',allCountries:'Alle Länder',allCurrencies:'Alle Währungen',allVerification:'Alle Zahlungsdaten',company:'Geschäftspartner',lastPayment:'Letzte Zahlung',totalSent:'Gesamt gesendet',payments:'Zahlungen',verification:'Zahlungsdaten',bankDetails:'Bankdaten',bankName:'Bank',account:'IBAN / Konto',bic:'SWIFT / BIC',accountHolder:'Kontoinhaber',lastInvoices:'Letzte Rechnungen',recentActivity:'Letzte Zahlungen',verificationStatus:'Status der Zahlungsdaten',empty:'Noch keine Geschäftspartner.'},
  routes:{...en.routes,title:'Routen',subtitle:'Internationale Zahlungsoptionen nach Kosten, Dauer und Zuverlässigkeit vergleichen.',source:'Absenderland',destination:'Empfängerland',sending:'Sendebetrag',recipientCurrency:'Empfangswährung',explore:'Routen suchen',selected:'Ausgewählte Route',best:'Beste Option',totalCost:'Gesamtkosten',youSave:'Ersparnis',fxSpread:'FX-Aufschlag',intermediaries:'Zwischenbanken',reliability:'Zuverlässigkeit',routeFlow:'Zahlungsweg',why:'Warum diese Route?',options:'Optionen',compare:'Routenvergleich',noRoutes:'Für diesen Korridor und Betrag ist noch keine Route verfügbar. Versuchen Sie eine andere Währung oder einen anderen Betrag.',estimate:'Kosten und Laufzeiten sind Schätzwerte und können sich vor der Zahlung ändern.'},
  analytics:{...en.analytics,title:'Analyse',subtitle:'Performance, Trends und Kosten internationaler Zahlungen messen.',totalVolume:'Gesamtvolumen',totalSavings:'Gesamtersparnis',averageFee:'Durchschnittsgebühr',settlement:'Durchschnittliche Laufzeit',volumeTime:'Zahlungsvolumen im Zeitverlauf',savingsBreakdown:'Einsparungen',currency:'Volumen nach Währung',country:'Volumen nach Land',route:'Volumen nach Route',provider:'Volumen nach Partner',health:'Zahlungseffizienz',distribution:'Verteilung der Laufzeiten',partial:'Einige Währungen konnten für diesen Zeitraum nicht in Ihre Berichtswährung umgerechnet werden.'},
  reports:{...en.reports,title:'Berichte',subtitle:'Aktuelle Zahlungs-, Einsparungs-, Geschäftspartner- und API-Daten für Abstimmung und Analyse exportieren.',payments:'Zahlungsbericht',savings:'Einsparungsbericht',counterparties:'Geschäftspartnerbericht',api:'API-Nutzungsbericht',download:'CSV herunterladen',empty:'Für diesen Bericht sind noch keine Daten vorhanden.'},
  invoices:{...en.invoices,title:'Rechnungen',subtitle:'Lieferantenrechnungen verfolgen und mit Zahlungen verknüpfen.',create:'Rechnung hinzufügen',open:'Offen',scheduled:'Geplant',paid:'Bezahlt',cancelled:'Storniert',empty:'Noch keine Rechnungen.',linkPayment:'Verknüpfte Zahlung'},
  api:{...en.api,title:'API',subtitle:'Eigene Systeme mit FlowPay verbinden und API-Aktivität überwachen.',create:'API-Schlüssel erstellen',keys:'API-Schlüssel',usage:'Anfrageaktivität',lastUsed:'Zuletzt verwendet',revoke:'Widerrufen',secretOnce:'Kopieren Sie dieses Secret jetzt. Aus Sicherheitsgründen wird es nur einmal angezeigt.',noKeys:'Noch keine API-Schlüssel.',noUsage:'Noch keine API-Anfragen aufgezeichnet.'},
  settings:{...en.settings,title:'Einstellungen',subtitle:'Unternehmenspräferenzen und Zahlungsvorgaben verwalten.',company:'Unternehmensprofil',companyHint:'Unternehmensdaten, die in FlowPay verwendet werden.',base:'Berichtswährung',baseHint:'Währung für Dashboard, Analyse und Exporte.',notifications:'Aktivitätseinstellungen',security:'Sicherheit',payout:'Zahlungsvorgaben',providers:'Zahlungsverbindungen',language:'Sprache',registration:'Registernummer',address:'Geschäftsadresse',country:'Unternehmensland',save:'Speichern',noProviders:'Derzeit sind keine Zahlungspartner verfügbar.'}
})
const es=merge(en,{
  nav:{...en.nav,overview:'Resumen',payments:'Pagos',counterparties:'Contrapartes',routes:'Rutas',analytics:'Analítica',reports:'Informes',invoices:'Facturas',team:'Equipo',api:'API',settings:'Ajustes'},
  common:{...en.common,search:'Buscar pagos, contrapartes y rutas…',newPayment:'Crear pago',save:'Guardar',cancel:'Cancelar',edit:'Editar',delete:'Eliminar',close:'Cerrar',add:'Añadir',import:'Importar',export:'Exportar',filters:'Filtros',all:'Todos',loading:'Cargando…',noData:'Aún no hay datos',viewAll:'Ver todo',viewDetails:'Ver detalles',amount:'Importe',currency:'Moneda',country:'País',status:'Estado',dueDate:'Vencimiento',provider:'Socio',fee:'Comisión',speed:'Plazo',score:'Puntuación',date:'Fecha',reference:'Referencia',actions:'Acciones',from:'Desde',to:'Hacia',thisMonth:'Este mes',refresh:'Actualizar',realData:'Actividad de la cuenta'},
  shell:{...en.shell,setupRequired:'FlowPay no está disponible temporalmente',setupText:'No hemos podido cargar los datos de tu cuenta. Inténtalo de nuevo en un momento. Si el problema continúa, contacta con soporte de FlowPay.',help:'¿Necesitas ayuda?',helpText:'Gestiona los datos de la empresa, preferencias de pago y conexiones desde Ajustes.',command:'Buscar o ir a…',signOut:'Cerrar sesión',notifications:'Actividad',noNotifications:'Sin actividad reciente'},
  overview:{...en.overview,title:'Resumen',subtitle:'Tus operaciones de pagos internacionales de un vistazo.',volume:'Volumen de pagos',savings:'Ahorro estimado',counterparties:'Contrapartes activas',efficiency:'Eficiencia de pagos',routes:'Rutas',compare:'Comparar rutas',upcoming:'Próximos pagos',topCounterparties:'Principales contrapartes',activity:'Actividad reciente',fx:'Tipos de mercado',health:'Puntuación de eficiencia',configureBase:'Elige una moneda de informes para ver los totales en una sola moneda.',noPayments:'Crea tu primer pago para empezar a seguir la actividad y el rendimiento.',noRoutes:'Aún no hay rutas de pago disponibles. Ejecuta una comparación o activa un socio de pago.'},
  payments:{...en.payments,title:'Pagos',subtitle:'Planifica, revisa y controla pagos a proveedores.',dueWeek:'Vence esta semana',scheduled:'Importe programado',overdue:'Pagos vencidos',volume:'Volumen mensual',create:'Crear pago',search:'Buscar por factura, contraparte o ruta…',draft:'Borrador',ready:'Listo para pagar',paid:'Pagado',received:'Recibido',invoice:'Factura',counterparty:'Contraparte',route:'Ruta',recipientGets:'El beneficiario recibe',reviewSend:'Revisar',markPaid:'Marcar pagado',markReceived:'Marcar recibido',empty:'No hay pagos que coincidan con estos filtros.'},
  counterparties:{...en.counterparties,title:'Contrapartes',subtitle:'Gestiona proveedores, beneficiarios y datos de pago.',create:'Añadir contraparte',search:'Buscar contrapartes…',allCountries:'Todos los países',allCurrencies:'Todas las monedas',allVerification:'Todos los datos de pago',company:'Contraparte',lastPayment:'Último pago',totalSent:'Total enviado',payments:'Pagos',verification:'Datos de pago',bankDetails:'Datos bancarios',bankName:'Banco',account:'IBAN / cuenta',bic:'SWIFT / BIC',accountHolder:'Titular de la cuenta',lastInvoices:'Últimas facturas',recentActivity:'Pagos recientes',verificationStatus:'Estado de los datos',empty:'Aún no hay contrapartes.'},
  routes:{...en.routes,title:'Rutas',subtitle:'Compara opciones de pago internacionales por coste, plazo y fiabilidad.',source:'País de origen',destination:'País de destino',sending:'Importe enviado',recipientCurrency:'Moneda recibida',explore:'Buscar rutas',selected:'Ruta seleccionada',best:'Mejor opción',totalCost:'Coste total',youSave:'Ahorro',fxSpread:'Margen FX',intermediaries:'Bancos intermediarios',reliability:'Fiabilidad',routeFlow:'Recorrido del pago',why:'¿Por qué esta ruta?',options:'Opciones',compare:'Comparar rutas',noRoutes:'Aún no hay una ruta disponible para este corredor e importe. Prueba otra moneda o importe.',estimate:'Los costes y plazos son estimaciones y pueden cambiar antes de ejecutar el pago.'},
  analytics:{...en.analytics,title:'Analítica',subtitle:'Mide rendimiento, tendencias y costes de pagos internacionales.',totalVolume:'Volumen total',totalSavings:'Ahorro total',averageFee:'Comisión media',settlement:'Plazo medio',volumeTime:'Volumen de pagos en el tiempo',savingsBreakdown:'Desglose del ahorro',currency:'Volumen por moneda',country:'Volumen por país',route:'Volumen por ruta',provider:'Volumen por socio',health:'Eficiencia de pagos',distribution:'Distribución de plazos',partial:'Algunas monedas no se pudieron convertir a tu moneda de informes durante este periodo.'},
  reports:{...en.reports,title:'Informes',subtitle:'Exporta datos actuales de pagos, ahorro, contrapartes y API para conciliación y análisis.',payments:'Informe de pagos',savings:'Informe de ahorro',counterparties:'Informe de contrapartes',api:'Informe de uso de API',download:'Descargar CSV',empty:'Aún no hay datos para exportar en este informe.'},
  invoices:{...en.invoices,title:'Facturas',subtitle:'Controla facturas de proveedores y vincúlalas a pagos.',create:'Añadir factura',open:'Abierta',scheduled:'Programada',paid:'Pagada',cancelled:'Cancelada',empty:'Aún no hay facturas.',linkPayment:'Pago vinculado'},
  api:{...en.api,title:'API',subtitle:'Conecta tus sistemas con FlowPay y supervisa la actividad de la API.',create:'Crear clave API',keys:'Claves API',usage:'Actividad de solicitudes',lastUsed:'Último uso',revoke:'Revocar',secretOnce:'Copia este secreto ahora. Por seguridad, solo se mostrará una vez.',noKeys:'Aún no hay claves API.',noUsage:'Aún no se han registrado solicitudes API.'},
  settings:{...en.settings,title:'Ajustes',subtitle:'Gestiona preferencias de la empresa y valores predeterminados de pago.',company:'Perfil de la empresa',companyHint:'Datos de la empresa utilizados en FlowPay.',base:'Moneda de informes',baseHint:'Moneda utilizada en paneles, analítica y exportaciones.',notifications:'Preferencias de actividad',security:'Seguridad',payout:'Valores de pago',providers:'Conexiones de pago',language:'Idioma',registration:'Número de registro',address:'Dirección comercial',country:'País de la empresa',save:'Guardar',noProviders:'No hay socios de pago disponibles por ahora.'}
})

export const workspaceDictionaries:Record<Language,WorkspaceDictionary>={en,ru,fr,de,es}
export type { WorkspaceDictionary }
