import type { Language } from './types'

type Copy = {
  common: Record<string,string>
  payment: Record<string,string>
  counterparty: Record<string,string>
  invoice: Record<string,string>
  route: Record<string,string>
  analytics: Record<string,string>
  team: Record<string,string>
  api: Record<string,string>
  settings: Record<string,string>
}

const en: Copy = {
  common:{more:'More',close:'Close',selectCountry:'Select country',selectCurrency:'Select currency',receiveCurrency:'Receive currency',noMatches:'No matches',partialFx:'partial FX',verified:'verified',payments:'Payments',quotes:'Quotes',invoices:'Invoices',providerRules:'Payment routes',excellent:'Excellent',good:'Good',attention:'Needs attention',noData:'No data',owner:'Owner',pending:'Pending',active:'Active',yes:'Yes',no:'No'},
  payment:{title:'Create payment',description:'Create a supplier payment, compare available routes and keep every step in one place.',counterparty:'Counterparty',supplier:'Supplier name',supplierPlaceholder:'Company legal name',invoice:'Invoice',reference:'Reference',amount:'Amount',currency:'Currency',due:'Due date',source:'Source country',destination:'Destination country',findRoutes:'Find routes',bestScore:'Best score',noRouteBefore:'Run a quote to select a route. You can save the payment without one.',notes:'Notes',notesPlaceholder:'Internal notes',create:'Create payment',selectCounterparty:'Select saved counterparty',markReady:'Mark ready',markPaid:'Mark paid',markReceived:'Mark received',selectPayment:'Select a payment'},
  counterparty:{title:'Add counterparty',description:'Save supplier and beneficiary details for faster, more accurate payments.',company:'Company name',companyCountry:'Company country',preferredCurrency:'Preferred currency',email:'Email',taxId:'Tax ID',bankDetails:'Bank details',bankCountry:'Bank country',bankName:'Bank name',account:'IBAN / account number',accountHolder:'Account holder',bic:'SWIFT / BIC',create:'Add counterparty',clear:'Clear all',unverified:'Unverified',review:'In review',verified:'Verified',rejected:'Rejected',select:'Select a counterparty',detailsFilter:'All payment details',detailsReady:'Ready',detailsMissing:'Needs details',detailsInvalid:'Check details'},
  invoice:{title:'Add invoice',description:'Add a supplier invoice and keep its payment status, due date and reference together.',counterparty:'Counterparty',supplier:'Supplier',number:'Invoice number',reference:'Reference',issue:'Issue date',due:'Due date',amount:'Amount',currency:'Currency',notes:'Notes',create:'Add invoice',optional:'Optional',search:'Search invoices…',allStatuses:'All statuses',supplierColumn:'Supplier',issueColumn:'Issue',dueColumn:'Due'},
  route:{run:'Run a route quote',runDesc:'FlowPay checks the payment routes currently available for this corridor and amount.',ecb:'Market reference rate',lowestCost:'Lowest estimated cost',fastest:'Fastest settlement estimate',lowFx:'Lowest FX markup',strongScore:'Strong overall FlowScore',bestScore:'Best balance of cost, speed and reliability among available routes.',route:'Route',source:'Sender',recipient:'Recipient',swap:'Swap countries',matching:'matching route(s)',sourceCurrency:'Source amount currency'},
  analytics:{last30:'Last 30 days',last90:'Last 90 days',last12:'Last 12 months',allTime:'All time',routeComparison:'Route comparison',auditIdentified:'Audit identified',settled:'Settled payments',feeEfficiency:'Fee efficiency',timelineCoverage:'Timeline coverage',markTimeline:'Mark payments as paid and received to calculate actual settlement time.',sameDay:'Same day',oneDay:'1 day',twoDays:'2 days',threeDays:'3 days',fourFive:'4–5 days',sixPlus:'6+ days'},
  team:{ownerText:'You are the account owner and can manage billing, security and team access.',deliveryText:'Invitations are sent by email and remain pending until the recipient accepts.',viewer:'Viewer',analyst:'Analyst',manager:'Finance manager',admin:'Admin',create:'Create invitation',dialog:'Invite a teammate to FlowPay and assign their access level.'},
  api:{activeKeys:'Active keys',requests:'API requests',success:'Successful requests',endpoint:'Endpoint',status:'Status',duration:'Duration',date:'Date',auth:'Authenticate with',description:'The endpoint returns available FlowPay routes and a reference exchange rate when available.',done:'Done',keyName:'Key name',create:'Create key'},
  settings:{normalized:'All dashboard totals and analytics are converted into this reporting currency when a reference rate is available.',team:'Team members',teamSub:'Manage team access and outstanding invitations.',security:'Security',securitySub:'Review your sign-in details and account security.',email:'Email',emailConfirmed:'Email confirmed',lastSignIn:'Last sign in',api:'API keys',apiSub:'Secure API access for payment route calculations.',activeKeys:'Active keys',manageApi:'Manage API keys →',manageTeam:'Manage team →',preferences:'Choose which product and payment events you want FlowPay to notify you about.',defaults:'Default values used when you create a new outgoing payment.',bankTransfer:'Bank transfer',swift:'SWIFT',localTransfer:'Local transfer',shared:'SHA — shared',sender:'OUR — sender',recipient:'BEN — recipient',appearance:'Appearance & language',appearanceSub:'Choose the interface language used across FlowPay.',light:'Light · FlowPay',providerInfo:'Payment partners and corridors currently available for your company.',companyName:'Company name',defaultMethod:'Default method',chargeType:'Charge type',beneficiaryNotifications:'Beneficiary notifications',paymentConfirmations:'Payment confirmations',paymentFailures:'Payment failures',securityAlerts:'Security alerts',weeklyReports:'Weekly reports',rules:'rules',manual:'manual',updated:'Updated'},
}

const ru: Copy = {
  common:{more:'Ещё',close:'Закрыть',selectCountry:'Выберите страну',selectCurrency:'Выберите валюту',receiveCurrency:'Валюта получения',noMatches:'Ничего не найдено',partialFx:'частичный FX',verified:'проверено',payments:'Платежи',quotes:'Расчёты',invoices:'Счета',providerRules:'Платёжные маршруты',excellent:'Отлично',good:'Хорошо',attention:'Требует внимания',noData:'Нет данных',owner:'Владелец',pending:'Ожидает',active:'Активен',yes:'Да',no:'Нет'},
  payment:{title:'Создать платёж',description:'Создайте платёж поставщику, сравните доступные маршруты и контролируйте весь процесс в одном месте.',counterparty:'Контрагент',supplier:'Название поставщика',supplierPlaceholder:'Юридическое название компании',invoice:'Счёт',reference:'Референс',amount:'Сумма',currency:'Валюта',due:'Срок оплаты',source:'Страна отправителя',destination:'Страна получателя',findRoutes:'Найти маршруты',bestScore:'Лучший результат',noRouteBefore:'Запустите расчёт, чтобы выбрать маршрут. Платёж можно сохранить и без маршрута.',notes:'Заметки',notesPlaceholder:'Внутренние заметки',create:'Создать платёж',selectCounterparty:'Выберите сохранённого контрагента',markReady:'На проверку',markPaid:'Отметить оплаченным',markReceived:'Отметить полученным',selectPayment:'Выберите платёж'},
  counterparty:{title:'Добавить контрагента',description:'Сохраните реквизиты поставщика или получателя, чтобы быстрее создавать платежи без повторного ввода данных.',company:'Название компании',companyCountry:'Страна компании',preferredCurrency:'Основная валюта',email:'Email',taxId:'Налоговый номер',bankDetails:'Банковские реквизиты',bankCountry:'Страна банка',bankName:'Название банка',account:'IBAN / номер счёта',accountHolder:'Владелец счёта',bic:'SWIFT / BIC',create:'Добавить контрагента',clear:'Сбросить',unverified:'Не проверен',review:'На проверке',verified:'Проверен',rejected:'Отклонён',select:'Выберите контрагента',detailsFilter:'Все реквизиты',detailsReady:'Готовы',detailsMissing:'Нужны реквизиты',detailsInvalid:'Проверьте данные'},
  invoice:{title:'Добавить счёт',description:'Добавьте счёт поставщика и отслеживайте сумму, срок и статус оплаты в одном месте.',counterparty:'Контрагент',supplier:'Поставщик',number:'Номер счёта',reference:'Референс',issue:'Дата выставления',due:'Срок оплаты',amount:'Сумма',currency:'Валюта',notes:'Заметки',create:'Добавить счёт',optional:'Необязательно',search:'Поиск счетов…',allStatuses:'Все статусы',supplierColumn:'Поставщик',issueColumn:'Выставлен',dueColumn:'Срок'},
  route:{run:'Рассчитать маршрут',runDesc:'FlowPay проверит доступные платёжные маршруты для выбранного направления и суммы.',ecb:'Рыночный ориентир',lowestCost:'Минимальная расчётная стоимость',fastest:'Самый быстрый расчётный срок',lowFx:'Минимальная FX-наценка',strongScore:'Высокий итоговый FlowScore',bestScore:'Лучший баланс стоимости, скорости и надёжности среди доступных маршрутов.',route:'Маршрут',source:'Отправитель',recipient:'Получатель',swap:'Поменять страны',matching:'подходящих маршрутов',sourceCurrency:'Валюта исходной суммы'},
  analytics:{last30:'Последние 30 дней',last90:'Последние 90 дней',last12:'Последние 12 месяцев',allTime:'За всё время',routeComparison:'Сравнение маршрутов',auditIdentified:'Найдено аудитом',settled:'Завершённые платежи',feeEfficiency:'Эффективность комиссий',timelineCoverage:'Покрытие сроков',markTimeline:'Отмечайте платежи оплаченными и полученными, чтобы считать фактическое время зачисления.',sameDay:'В тот же день',oneDay:'1 день',twoDays:'2 дня',threeDays:'3 дня',fourFive:'4–5 дней',sixPlus:'6+ дней'},
  team:{ownerText:'Вы владелец аккаунта и можете управлять безопасностью, настройками и доступом команды.',deliveryText:'Приглашение отправляется на email и остаётся в ожидании до принятия.',viewer:'Наблюдатель',analyst:'Аналитик',manager:'Финансовый менеджер',admin:'Администратор',create:'Создать приглашение',dialog:'Пригласите сотрудника в FlowPay и назначьте ему уровень доступа.'},
  api:{activeKeys:'Активные ключи',requests:'Запросы API',success:'Успешные запросы',endpoint:'Эндпоинт',status:'Статус',duration:'Время',date:'Дата',auth:'Авторизация',description:'Эндпоинт возвращает доступные маршруты FlowPay и ориентировочный валютный курс, если он доступен.',done:'Готово',keyName:'Название ключа',create:'Создать ключ'},
  settings:{normalized:'Все показатели дашборда и аналитики пересчитываются в эту валюту, когда доступен ориентировочный курс.',team:'Команда',teamSub:'Управление доступом команды и приглашениями.',security:'Безопасность',securitySub:'Данные входа и основные параметры безопасности аккаунта.',email:'Email',emailConfirmed:'Email подтверждён',lastSignIn:'Последний вход',api:'API-ключи',apiSub:'Безопасный API-доступ к расчёту платёжных маршрутов.',activeKeys:'Активные ключи',manageApi:'Управлять API-ключами →',manageTeam:'Управлять командой →',preferences:'Выберите, какие события показывать в центре активности FlowPay.',defaults:'Значения, которые FlowPay будет использовать при создании новых платежей.',bankTransfer:'Банковский перевод',swift:'SWIFT',localTransfer:'Локальный перевод',shared:'SHA — комиссия делится',sender:'OUR — платит отправитель',recipient:'BEN — платит получатель',appearance:'Интерфейс и язык',appearanceSub:'Выберите язык интерфейса FlowPay.',light:'Светлая · FlowPay',providerInfo:'Платёжные партнёры и направления, доступные вашей компании.',companyName:'Название компании',defaultMethod:'Способ платежа по умолчанию',chargeType:'Тип комиссии',beneficiaryNotifications:'Уведомлять получателя',paymentConfirmations:'Подтверждения платежей',paymentFailures:'Ошибки платежей',securityAlerts:'События безопасности',weeklyReports:'Еженедельные отчёты',rules:'правил',manual:'вручную',updated:'Обновлено'},
}

const fr: Copy = {
  ...en,
  common:{...en.common,more:'Plus',close:'Fermer',selectCountry:'Choisir un pays',selectCurrency:'Choisir une devise',receiveCurrency:'Devise reçue',noMatches:'Aucun résultat'},
  payment:{...en.payment,title:'Créer un paiement',counterparty:'Contrepartie',supplier:'Nom du fournisseur',invoice:'Facture',reference:'Référence',amount:'Montant',currency:'Devise',due:'Échéance',source:'Pays source',destination:'Pays destinataire',findRoutes:'Trouver des routes',notes:'Notes',create:'Créer le paiement'},
  counterparty:{...en.counterparty,title:'Ajouter une contrepartie',company:'Nom de la société',companyCountry:'Pays',preferredCurrency:'Devise principale',bankDetails:'Coordonnées bancaires',create:'Ajouter',detailsFilter:'Toutes les coordonnées',detailsReady:'Prêtes',detailsMissing:'À compléter',detailsInvalid:'À vérifier'},
  invoice:{...en.invoice,title:'Ajouter une facture',supplier:'Fournisseur',number:'Numéro de facture',issue:'Date d’émission',due:'Échéance',amount:'Montant',currency:'Devise',create:'Ajouter la facture'},
  route:{...en.route,run:'Calculer une route',ecb:'Référence marché',swap:'Inverser les pays'},
  analytics:{...en.analytics,last30:'30 derniers jours',last90:'90 derniers jours',last12:'12 derniers mois',allTime:'Toute la période'},
  team:{...en.team,viewer:'Lecture',analyst:'Analyste',manager:'Responsable finance',admin:'Administrateur',create:'Créer l’invitation'},
  api:{...en.api,activeKeys:'Clés actives',requests:'Requêtes API',success:'Requêtes réussies',status:'Statut',duration:'Durée',date:'Date',done:'Terminé',keyName:'Nom de la clé',create:'Créer la clé'},
  settings:{...en.settings,team:'Membres',security:'Sécurité',emailConfirmed:'Email confirmé',lastSignIn:'Dernière connexion',appearance:'Apparence et langue',bankTransfer:'Virement bancaire',localTransfer:'Virement local',companyName:'Nom de la société',defaultMethod:'Mode de paiement par défaut',chargeType:'Type de frais',beneficiaryNotifications:'Notifications au bénéficiaire',paymentConfirmations:'Confirmations de paiement',paymentFailures:'Échecs de paiement',securityAlerts:'Alertes de sécurité',weeklyReports:'Rapports hebdomadaires',rules:'règles',manual:'manuel',updated:'Mis à jour'},
}
const de: Copy = {
  ...en,
  common:{...en.common,more:'Mehr',close:'Schließen',selectCountry:'Land wählen',selectCurrency:'Währung wählen',receiveCurrency:'Empfangswährung',noMatches:'Keine Treffer'},
  payment:{...en.payment,title:'Zahlung erstellen',counterparty:'Geschäftspartner',supplier:'Lieferant',invoice:'Rechnung',reference:'Referenz',amount:'Betrag',currency:'Währung',due:'Fällig am',source:'Ausgangsland',destination:'Zielland',findRoutes:'Routen finden',notes:'Notizen',create:'Zahlung erstellen'},
  counterparty:{...en.counterparty,title:'Geschäftspartner hinzufügen',company:'Firmenname',companyCountry:'Land',preferredCurrency:'Hauptwährung',bankDetails:'Bankdaten',create:'Hinzufügen',detailsFilter:'Alle Zahlungsdaten',detailsReady:'Bereit',detailsMissing:'Daten fehlen',detailsInvalid:'Daten prüfen'},
  invoice:{...en.invoice,title:'Rechnung hinzufügen',supplier:'Lieferant',number:'Rechnungsnummer',issue:'Rechnungsdatum',due:'Fällig am',amount:'Betrag',currency:'Währung',create:'Rechnung hinzufügen'},
  route:{...en.route,run:'Route berechnen',ecb:'Marktreferenz',swap:'Länder tauschen'},
  analytics:{...en.analytics,last30:'Letzte 30 Tage',last90:'Letzte 90 Tage',last12:'Letzte 12 Monate',allTime:'Gesamter Zeitraum'},
  team:{...en.team,viewer:'Betrachter',analyst:'Analyst',manager:'Finance Manager',admin:'Administrator',create:'Einladung erstellen'},
  api:{...en.api,activeKeys:'Aktive Schlüssel',requests:'API-Anfragen',success:'Erfolgreiche Anfragen',status:'Status',duration:'Dauer',date:'Datum',done:'Fertig',keyName:'Schlüsselname',create:'Schlüssel erstellen'},
  settings:{...en.settings,team:'Teammitglieder',security:'Sicherheit',emailConfirmed:'E-Mail bestätigt',lastSignIn:'Letzte Anmeldung',appearance:'Darstellung & Sprache',bankTransfer:'Banküberweisung',localTransfer:'Lokale Überweisung',companyName:'Firmenname',defaultMethod:'Standard-Zahlungsart',chargeType:'Gebührentyp',beneficiaryNotifications:'Empfänger benachrichtigen',paymentConfirmations:'Zahlungsbestätigungen',paymentFailures:'Fehlgeschlagene Zahlungen',securityAlerts:'Sicherheitswarnungen',weeklyReports:'Wöchentliche Berichte',rules:'Regeln',manual:'manuell',updated:'Aktualisiert'},
}
const es: Copy = {
  ...en,
  common:{...en.common,more:'Más',close:'Cerrar',selectCountry:'Elegir país',selectCurrency:'Elegir moneda',receiveCurrency:'Moneda de recepción',noMatches:'Sin resultados'},
  payment:{...en.payment,title:'Crear pago',counterparty:'Contraparte',supplier:'Proveedor',invoice:'Factura',reference:'Referencia',amount:'Importe',currency:'Moneda',due:'Vencimiento',source:'País de origen',destination:'País de destino',findRoutes:'Buscar rutas',notes:'Notas',create:'Crear pago'},
  counterparty:{...en.counterparty,title:'Añadir contraparte',company:'Empresa',companyCountry:'País',preferredCurrency:'Moneda principal',bankDetails:'Datos bancarios',create:'Añadir',detailsFilter:'Todos los datos',detailsReady:'Listos',detailsMissing:'Faltan datos',detailsInvalid:'Revisar datos'},
  invoice:{...en.invoice,title:'Añadir factura',supplier:'Proveedor',number:'Número de factura',issue:'Fecha de emisión',due:'Vencimiento',amount:'Importe',currency:'Moneda',create:'Añadir factura'},
  route:{...en.route,run:'Calcular ruta',ecb:'Referencia de mercado',swap:'Intercambiar países'},
  analytics:{...en.analytics,last30:'Últimos 30 días',last90:'Últimos 90 días',last12:'Últimos 12 meses',allTime:'Todo el período'},
  team:{...en.team,viewer:'Lector',analyst:'Analista',manager:'Responsable financiero',admin:'Administrador',create:'Crear invitación'},
  api:{...en.api,activeKeys:'Claves activas',requests:'Solicitudes API',success:'Solicitudes correctas',status:'Estado',duration:'Duración',date:'Fecha',done:'Listo',keyName:'Nombre de clave',create:'Crear clave'},
  settings:{...en.settings,team:'Miembros',security:'Seguridad',emailConfirmed:'Email confirmado',lastSignIn:'Último acceso',appearance:'Apariencia e idioma',bankTransfer:'Transferencia bancaria',localTransfer:'Transferencia local',companyName:'Nombre de la empresa',defaultMethod:'Método de pago predeterminado',chargeType:'Tipo de comisión',beneficiaryNotifications:'Notificaciones al beneficiario',paymentConfirmations:'Confirmaciones de pago',paymentFailures:'Pagos fallidos',securityAlerts:'Alertas de seguridad',weeklyReports:'Informes semanales',rules:'reglas',manual:'manual',updated:'Actualizado'},
}

export const workspaceCopy: Record<Language,Copy> = { en, ru, fr, de, es }
