'use client'

import { useMemo, useState } from 'react'
import { BarChart3, Clock3, Percent, PiggyBank } from 'lucide-react'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { workspaceDictionaries } from '@/lib/workspace-i18n'
import { workspaceCopy } from '@/lib/workspace-copy'
import { useFxMap } from '@/hooks/use-fx-map'
import { healthScore, isSettled, money, monthLabel, normalize, number, providerLabel } from '@/lib/metrics'
import { PageHeader, MetricCard, EmptyState, SectionTitle } from '@/components/workspace/primitives'
import { Card } from '@/components/ui/card'
import { SelectMenu } from '@/components/ui/select-menu'
import { DistributionBars, SavingsDonut, VolumeAreaChart } from '@/components/workspace/LazyCharts'
import { CountryFlag } from '@/components/brand/CountryFlag'
import type { Language, PaymentDraft } from '@/lib/types'

type Range='30d'|'90d'|'12m'|'all'

export default function AnalyticsPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const t=workspaceDictionaries[lang];const copy=workspaceCopy[lang].analytics;const [range,setRange]=useState<Range>('12m')
  const providerNames=useMemo(()=>new Map(ws.providerRules.map(r=>[r.provider_code,r.display_name||providerLabel(r.provider_code)])),[ws.providerRules]);const base=ws.profile?.preferred_currency||null;const currencies=useMemo(()=>Array.from(new Set([...ws.payments.map(p=>p.currency),...ws.calculations.map(c=>c.currency),...ws.audits.map(a=>a.currency)])),[ws.payments,ws.calculations,ws.audits]);const fx=useFxMap(base,currencies)
  const since=useMemo(()=>{if(range==='all')return null;const d=new Date();if(range==='30d')d.setDate(d.getDate()-30);if(range==='90d')d.setDate(d.getDate()-90);if(range==='12m')d.setMonth(d.getMonth()-12);return d},[range]);const inRange=(value:string)=>!since||new Date(value)>=since
  const payments=ws.payments.filter(p=>isSettled(p)&&inRange(p.received_at||p.paid_at||p.updated_at));const calcs=ws.calculations.filter(c=>inRange(c.created_at));const audits=ws.audits.filter(a=>inRange(a.created_at))
  const totalVolume=base?payments.reduce((sum,p)=>sum+(normalize(Number(p.amount),p.currency,base,fx.rates)||0),0):null
  const totalSavings=base?calcs.reduce((sum,c)=>sum+(normalize(Number(c.estimated_saving),c.currency,base,fx.rates)||0),0)+audits.reduce((sum,a)=>sum+(normalize(Number(a.potential_saving),a.currency,base,fx.rates)||0),0):null
  const avgFee=calcs.length?calcs.reduce((sum,c)=>sum+Number(c.best_fee)/Math.max(1,Number(c.amount))*100,0)/calcs.length:null
  const settlementRows=payments.filter(p=>p.paid_at&&p.received_at).map(p=>(new Date(p.received_at!).getTime()-new Date(p.paid_at!).getTime())/86400000).filter(value=>Number.isFinite(value)&&value>=0)
  const avgSettlement=settlementRows.length?settlementRows.reduce((a,b)=>a+b,0)/settlementRows.length:null;const score=healthScore(ws.payments,avgFee)
  const volumeSeries=useMemo(()=>buildTimeSeries(payments,range,base,fx.rates,lang),[payments,range,base,fx.rates,lang])
  const currencyRows=useMemo(()=>aggregate(payments,p=>p.currency,p=>base?normalize(Number(p.amount),p.currency,base,fx.rates):1),[payments,base,fx.rates])
  const countryRows=useMemo(()=>aggregate(payments,p=>p.route_to_country||ws.counterparties.find(c=>c.id===p.counterparty_id)?.country||'',p=>base?normalize(Number(p.amount),p.currency,base,fx.rates):1),[payments,base,fx.rates,ws.counterparties])
  const routeRows=useMemo(()=>aggregate(payments,p=>p.route_from_country&&p.route_to_country?`${p.route_from_country} → ${p.route_to_country}`:(lang==='ru'?'Без маршрута':'Unrouted'),p=>base?normalize(Number(p.amount),p.currency,base,fx.rates):1),[payments,base,fx.rates,lang])
  const providerRows=useMemo(()=>aggregate(payments,p=>p.route_provider_code?(providerNames.get(p.route_provider_code)||providerLabel(p.route_provider_code)):(lang==='ru'?'Без маршрута':'Unrouted'),p=>base?normalize(Number(p.amount),p.currency,base,fx.rates):1),[payments,base,fx.rates,lang,providerNames])
  const settleDist=useMemo(()=>{const bins=[{label:copy.sameDay,min:0,max:1},{label:copy.oneDay,min:1,max:2},{label:copy.twoDays,min:2,max:3},{label:copy.threeDays,min:3,max:4},{label:copy.fourFive,min:4,max:6},{label:copy.sixPlus,min:6,max:Infinity}];return bins.map(bin=>({label:bin.label,value:settlementRows.filter(value=>value>=bin.min&&value<bin.max).length}))},[settlementRows,copy])
  const routeSavings=base?calcs.reduce((sum,c)=>sum+(normalize(Number(c.estimated_saving),c.currency,base,fx.rates)||0),0):calcs.length;const auditSavings=base?audits.reduce((sum,a)=>sum+(normalize(Number(a.potential_saving),a.currency,base,fx.rates)||0),0):audits.length
  const valueFormatter=(value:number)=>base?money(value,base,lang,true):number(value,lang,0)

  return <div className="fp-enter"><PageHeader title={t.analytics.title} subtitle={t.analytics.subtitle} actions={<SelectMenu value={range} onChange={v=>setRange(v as Range)} ariaLabel={t.common.date} className="w-[170px]" options={[{value:'30d',label:copy.last30},{value:'90d',label:copy.last90},{value:'12m',label:copy.last12},{value:'all',label:copy.allTime}]}/>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={base?t.analytics.totalVolume:(lang==='ru'?'Завершённые платежи':'Settled payments')} value={base?money(totalVolume,base,lang,true):String(payments.length)} meta={base||((lang==='ru'?'за выбранный период':'in selected period'))} icon={<BarChart3 size={16}/>}/><MetricCard label={base?t.analytics.totalSavings:(lang==='ru'?'Проанализировано':'Optimisation checks')} value={base?money(totalSavings,base,lang,true):String(calcs.length+audits.length)} meta={`${calcs.length} ${copy.routeComparison.toLowerCase()} · ${audits.length} ${copy.auditIdentified.toLowerCase()}`} icon={<PiggyBank size={16}/>}/><MetricCard label={t.analytics.averageFee} value={avgFee==null?'0':`${number(avgFee,lang,2)}%`} meta={`${calcs.length} ${copy.routeComparison.toLowerCase()}`} icon={<Percent size={16}/>}/><MetricCard label={t.analytics.settlement} value={avgSettlement==null?'0':`${number(avgSettlement,lang,1)} ${lang==='ru'?'дн.':'days'}`} meta={`${settlementRows.length} ${copy.settled.toLowerCase()}`} icon={<Clock3 size={16}/>}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card className="p-5 sm:p-6"><SectionTitle title={base?t.analytics.volumeTime:(lang==='ru'?'Динамика платежей':'Payment activity')} subtitle={base?(lang==='ru'?'Завершённый объём по выбранному периоду':'Settled volume for the selected period'):(lang==='ru'?'Количество завершённых операций':'Number of settled transactions')}/>{payments.length?<VolumeAreaChart data={volumeSeries} height={275} className="mt-3" valueFormatter={valueFormatter}/>:<div className="mt-4"><EmptyState title={t.common.noData} description={lang==='ru'?'После завершения первого платежа здесь появится динамика.':'Activity will appear after your first settled payment.'}/></div>}</Card><Card className="p-5 sm:p-6"><SectionTitle title={base?t.analytics.savingsBreakdown:(lang==='ru'?'Источники оптимизации':'Optimisation activity')}/>{routeSavings>0||auditSavings>0?<><SavingsDonut totalLabel={base||(lang==='ru'?'анализов':'checks')} valueFormatter={valueFormatter} data={[{name:copy.routeComparison,value:routeSavings,color:'#187a45'},{name:copy.auditIdentified,value:auditSavings,color:'#8fc59c'}]}/><div className="space-y-2 text-[14px]"><div className="flex justify-between"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#187a45]"/>{copy.routeComparison}</span><strong>{base?money(routeSavings,base,lang):number(routeSavings,lang,0)}</strong></div><div className="flex justify-between"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#8fc59c]"/>{copy.auditIdentified}</span><strong>{base?money(auditSavings,base,lang):number(auditSavings,lang,0)}</strong></div></div></>:<div className="mt-4"><EmptyState compact title={t.common.noData}/></div>}</Card></div>
    {fx.missing.length>0&&<p className="mt-3 rounded-[10px] bg-[var(--fp-amber-soft)] px-3 py-2 text-[14px] text-[var(--fp-amber)]">{t.analytics.partial} {fx.missing.join(', ')}</p>}
    <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Breakdown title={t.analytics.currency} rows={currencyRows} base={base} lang={lang}/><Breakdown title={t.analytics.country} rows={countryRows} base={base} lang={lang} country/><Breakdown title={t.analytics.route} rows={routeRows} base={base} lang={lang}/><Breakdown title={t.analytics.provider} rows={providerRows} base={base} lang={lang}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><Card className="p-5 sm:p-6"><SectionTitle title={t.analytics.health}/>{score==null?<div className="mt-4"><EmptyState compact title={t.common.noData}/></div>:<div className="mt-6 flex flex-col items-center gap-6 sm:flex-row"><div className="relative grid size-32 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(var(--fp-green) ${score}%, #e8ede8 0)`}}><div className="grid size-24 place-items-center rounded-full bg-white text-center"><div><strong className="block text-[30px] tracking-[-.05em]">{score}</strong><span className="text-[14px] text-[var(--fp-muted)]">/100</span></div></div></div><div className="w-full flex-1 space-y-3 text-[14px]"><ScoreRow label={copy.settled} value={payments.length?Math.round(payments.length/Math.max(1,ws.payments.length)*100):0}/><ScoreRow label={copy.feeEfficiency} value={avgFee==null?0:Math.max(0,Math.round(100-avgFee*30))}/><ScoreRow label={copy.timelineCoverage} value={Math.round(settlementRows.length/Math.max(1,payments.length)*100)}/></div></div>}</Card><Card className="p-5 sm:p-6"><SectionTitle title={t.analytics.distribution}/>{settlementRows.length?<DistributionBars data={settleDist} height={220}/>:<div className="mt-4"><EmptyState compact title={t.common.noData} description={copy.markTimeline}/></div>}</Card></div>
  </div>
}

function buildTimeSeries(payments:PaymentDraft[],range:Range,base:string|null,rates:Record<string,number>,lang:Language){
  const now=new Date();const locale=lang==='ru'?'ru-RU':lang==='fr'?'fr-FR':lang==='de'?'de-DE':lang==='es'?'es-ES':'en-US'
  if(range==='30d'||range==='90d'){
    const days=range==='30d'?30:91;const bucket=range==='30d'?3:7;const count=Math.ceil(days/bucket);const start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-(count*bucket-1))
    return Array.from({length:count},(_,index)=>{const a=new Date(start);a.setDate(a.getDate()+index*bucket);const b=new Date(a);b.setDate(b.getDate()+bucket);const value=payments.filter(p=>{const d=new Date(p.received_at||p.paid_at||p.updated_at);return d>=a&&d<b}).reduce((sum,p)=>sum+(base?(normalize(Number(p.amount),p.currency,base,rates)||0):1),0);return{label:new Intl.DateTimeFormat(locale,{month:'short',day:'numeric'}).format(a),value}})
  }
  let months=12
  if(range==='all'&&payments.length){const earliest=Math.min(...payments.map(p=>new Date(p.received_at||p.paid_at||p.updated_at).getTime()));const first=new Date(earliest);months=Math.max(1,Math.min(24,(now.getFullYear()-first.getFullYear())*12+now.getMonth()-first.getMonth()+1))}
  const list=Array.from({length:months},(_,index)=>new Date(now.getFullYear(),now.getMonth()-months+1+index,1))
  return list.map(a=>{const b=new Date(a.getFullYear(),a.getMonth()+1,1);const value=payments.filter(p=>{const d=new Date(p.received_at||p.paid_at||p.updated_at);return d>=a&&d<b}).reduce((sum,p)=>sum+(base?(normalize(Number(p.amount),p.currency,base,rates)||0):1),0);return{label:monthLabel(a,lang),value}})
}

function aggregate<T>(items:T[],key:(item:T)=>string,value:(item:T)=>number|null){const map=new Map<string,number>();for(const item of items){const k=key(item);const v=value(item);if(!k||v==null)continue;map.set(k,(map.get(k)||0)+v)}return [...map.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,5)}
function Breakdown({title,rows,base,lang,country=false}:{title:string;rows:{label:string;value:number}[];base:string|null;lang:Language;country?:boolean}){const total=rows.reduce((s,r)=>s+r.value,0);return <Card className="p-5"><SectionTitle title={title}/><div className="mt-4 space-y-3">{rows.length?rows.map(r=><div key={r.label}><div className="flex items-center justify-between gap-3 text-[14px]"><span className="flex min-w-0 items-center gap-2 font-medium">{country&&r.label.length===2&&<CountryFlag code={r.label}/>}<span className="truncate">{r.label}</span></span><span className="shrink-0 text-[var(--fp-muted)]">{base?money(r.value,base,lang,true):number(r.value,lang,0)} · {total?Math.round(r.value/total*100):0}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#eff1ee]"><i className="block h-full rounded-full bg-[var(--fp-green)]" style={{width:`${total?r.value/total*100:0}%`}}/></div></div>):<p className="py-8 text-center text-[14px] text-[var(--fp-muted)]">{workspaceCopy[lang].common.noData}</p>}</div></Card>}
function ScoreRow({label,value}:{label:string;value:number}){return <div><div className="flex justify-between"><span className="text-[var(--fp-muted)]">{label}</span><strong>{value}/100</strong></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-[#eef0ec]"><i className="block h-full rounded-full bg-[var(--fp-green)] transition-[width] duration-700" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
