'use client'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { CheckCircle2, Loader2 } from 'lucide-react'
import { FlowPayLogo } from '@/components/brand/FlowPayLogo'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { createClient } from '@/lib/supabase/client'
import { useLanguage } from '@/components/LanguageContext'

export default function ResetPasswordPage(){const {lang}=useLanguage();const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [loading,setLoading]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState('');const ru=lang==='ru';async function submit(e:FormEvent){e.preventDefault();setError('');if(password.length<8){setError(ru?'Минимум 8 символов.':'Use at least 8 characters.');return}if(password!==confirm){setError(ru?'Пароли не совпадают.':'Passwords do not match.');return}setLoading(true);try{const {error}=await createClient().auth.updateUser({password});if(error)throw error;setDone(true)}catch{setError(ru?'Ссылка недействительна или устарела. Запросите восстановление ещё раз.':'This recovery link is invalid or expired. Request a new one.')}finally{setLoading(false)}}return <main className="grid min-h-screen place-items-center bg-[#fafaf7] p-5"><section className="w-full max-w-[460px] rounded-[22px] border border-[var(--fp-border)] bg-white p-6 shadow-[0_24px_80px_rgba(31,52,38,.08)] sm:p-8"><FlowPayLogo/>{done?<div className="py-8 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-[var(--fp-green-soft)] text-[var(--fp-green)]"><CheckCircle2 size={22}/></span><h1 className="mt-5 text-[26px] font-semibold tracking-[-.04em]">{ru?'Пароль обновлён':'Password updated'}</h1><p className="mt-2 text-[14px] text-[var(--fp-muted)]">{ru?'Теперь можно войти с новым паролем.':'You can now sign in with your new password.'}</p><Link href="/login"><Button className="mt-6 w-full">{ru?'Войти':'Sign in'}</Button></Link></div>:<><h1 className="mt-8 text-[30px] font-semibold tracking-[-.05em]">{ru?'Новый пароль':'Choose a new password'}</h1><p className="mt-2 text-[14px] leading-5 text-[var(--fp-muted)]">{ru?'Укажите новый пароль для аккаунта FlowPay.':'Set a new password for your FlowPay account.'}</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{ru?'Новый пароль':'New password'}</span><Input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label className="block space-y-2 text-[14px] font-medium text-[var(--fp-muted)]"><span>{ru?'Повторите пароль':'Confirm password'}</span><Input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<div className="rounded-[11px] bg-[var(--fp-red-soft)] p-3 text-[14px] text-[var(--fp-red)]">{error}</div>}<Button className="w-full" disabled={loading}>{loading&&<Loader2 size={15} className="animate-spin"/>}{ru?'Обновить пароль':'Update password'}</Button></form></>}</section></main>}
