'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, CircleAlert, Loader2, RefreshCw } from 'lucide-react'
import { FlowPayLogo } from '@/components/brand/FlowPayLogo'
import { Button } from '@/components/ui/button'

type Health={ok:boolean;status:string;version:string;checks:{configuration:boolean;database:boolean};routing:{configuredRules:number};timestamp:string;responseTimeMs:number}
export default function StatusPage(){const [data,setData]=useState<Health|null>(null);const [loading,setLoading]=useState(true);async function load(){setLoading(true);try{const response=await fetch('/api/health',{cache:'no-store'});setData(await response.json())}catch{setData(null)}finally{setLoading(false)}}useEffect(()=>{void load()},[]);const ok=Boolean(data?.ok);return <main className="min-h-screen bg-[#fafaf7]"><header className="border-b border-[var(--fp-border)] bg-white"><div className="mx-auto flex h-[68px] max-w-[1040px] items-center justify-between px-5"><FlowPayLogo/><Link href="/" className="text-[14px] font-medium text-[var(--fp-muted)]">Back to FlowPay</Link></div></header><section className="mx-auto max-w-[820px] px-5 py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[12px] font-semibold uppercase tracking-[.13em] text-[var(--fp-green)]">System status</span><h1 className="mt-3 text-[38px] font-semibold tracking-[-.055em]">FlowPay status</h1><p className="mt-2 text-[15px] text-[var(--fp-muted)]">Live health of the FlowPay application and core data services.</p></div><Button variant="secondary" onClick={load} disabled={loading}>{loading?<Loader2 size={15} className="animate-spin"/>:<RefreshCw size={15}/>}Refresh</Button></div><div className={`mt-8 flex items-center gap-4 rounded-[18px] border p-5 ${ok?'border-[#cfe3d5] bg-[#f1f7f2]':'border-[#efd6c9] bg-[#fff6f1]'}`}><span className={`grid size-11 place-items-center rounded-full bg-white ${ok?'text-[var(--fp-green)]':'text-[var(--fp-amber)]'}`}>{ok?<CheckCircle2 size={22}/>:<CircleAlert size={22}/>}</span><div><strong className="text-[18px]">{loading?'Checking services…':ok?'All core systems operational':'Some services are degraded'}</strong><p className="mt-1 text-[14px] text-[var(--fp-muted)]">Version {data?.version||'—'} · response {data?.responseTimeMs??'—'} ms</p></div></div><div className="mt-4 overflow-hidden rounded-[18px] border border-[var(--fp-border)] bg-white"><StatusRow name="Application configuration" ok={data?.checks.configuration}/><StatusRow name="Primary database" ok={data?.checks.database}/><StatusRow name="Payment options" ok={(data?.routing.configuredRules||0)>0} detail={data?(data.routing.configuredRules>0?'Available':'Configuration in progress'):'—'}/></div><p className="mt-5 text-[13px] leading-5 text-[var(--fp-subtle)]">Payment availability depends on the countries, currencies and payment partners enabled for each corridor.</p></section></main>}
function StatusRow({name,ok,detail}:{name:string;ok?:boolean;detail?:string}){return <div className="flex items-center justify-between gap-4 border-b border-[var(--fp-border)] px-5 py-4 last:border-b-0"><span className="text-[15px] font-medium">{name}</span><span className="flex items-center gap-2 text-[13px] text-[var(--fp-muted)]">{detail&&<span>{detail}</span>}<i className={`size-2.5 rounded-full ${ok?'bg-[#4ca56a]':'bg-[#d9a05b]'}`}/></span></div>}
