'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, CircleAlert, Loader2, RefreshCw } from 'lucide-react'
import { FlowPayLogo } from '@/components/brand/FlowPayLogo'
import { Button } from '@/components/ui/button'
import { useLanguage } from '@/components/LanguageContext'

type Health={ok:boolean;status:string;checks:{application:boolean;database:boolean;routing:boolean};timestamp:string}

const copy={
  ru:{back:'На главную',eyebrow:'Состояние сервиса',title:'Статус FlowPay',sub:'Актуальное состояние основных систем FlowPay.',refresh:'Обновить',checking:'Проверяем системы…',ok:'Все основные системы работают',degraded:'Часть систем временно недоступна',application:'Приложение',database:'Основные данные',routing:'Платёжные маршруты',available:'Доступны',configuring:'Настройка',foot:'Доступность способов оплаты зависит от стран, валют и подключённых платёжных партнёров.'},
  en:{back:'Back to FlowPay',eyebrow:'System status',title:'FlowPay status',sub:'Current health of FlowPay core services.',refresh:'Refresh',checking:'Checking services…',ok:'All core systems operational',degraded:'Some services are degraded',application:'Application',database:'Core data',routing:'Payment routes',available:'Available',configuring:'Configuration in progress',foot:'Payment availability depends on the countries, currencies and payment partners enabled for each corridor.'},
  fr:{back:'Retour à FlowPay',eyebrow:'État du service',title:'Statut FlowPay',sub:'État actuel des services essentiels de FlowPay.',refresh:'Actualiser',checking:'Vérification…',ok:'Tous les systèmes principaux fonctionnent',degraded:'Certains services sont dégradés',application:'Application',database:'Données principales',routing:'Routes de paiement',available:'Disponibles',configuring:'Configuration en cours',foot:'La disponibilité des paiements dépend des pays, devises et partenaires activés.'},
  de:{back:'Zurück zu FlowPay',eyebrow:'Systemstatus',title:'FlowPay Status',sub:'Aktueller Zustand der wichtigsten FlowPay-Dienste.',refresh:'Aktualisieren',checking:'Systeme werden geprüft…',ok:'Alle Kernsysteme funktionieren',degraded:'Einige Dienste sind eingeschränkt',application:'Anwendung',database:'Kerndaten',routing:'Zahlungsrouten',available:'Verfügbar',configuring:'Wird eingerichtet',foot:'Die Zahlungsabdeckung hängt von Ländern, Währungen und aktivierten Zahlungspartnern ab.'},
  es:{back:'Volver a FlowPay',eyebrow:'Estado del servicio',title:'Estado de FlowPay',sub:'Estado actual de los servicios principales de FlowPay.',refresh:'Actualizar',checking:'Comprobando sistemas…',ok:'Todos los sistemas principales funcionan',degraded:'Algunos servicios están degradados',application:'Aplicación',database:'Datos principales',routing:'Rutas de pago',available:'Disponibles',configuring:'Configuración en curso',foot:'La disponibilidad de pagos depende de los países, divisas y socios de pago habilitados.'},
}

export default function StatusPage(){const {lang}=useLanguage();const c=copy[lang];const [data,setData]=useState<Health|null>(null);const [loading,setLoading]=useState(true);async function load(){setLoading(true);try{const response=await fetch('/api/health',{cache:'no-store'});const body=await response.json() as Health;setData(body)}catch{setData(null)}finally{setLoading(false)}}useEffect(()=>{void load()},[]);const ok=Boolean(data?.ok);const checkedAt=useMemo(()=>data?.timestamp?new Intl.DateTimeFormat(lang,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(data.timestamp)):'—',[data?.timestamp,lang]);return <main className="min-h-screen bg-[#fafaf7]"><header className="border-b border-[var(--fp-border)] bg-white"><div className="mx-auto flex h-[68px] max-w-[1040px] items-center justify-between px-5"><FlowPayLogo/><Link href="/" className="text-[14px] font-medium text-[var(--fp-muted)]">{c.back}</Link></div></header><section className="mx-auto max-w-[820px] px-5 py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[12px] font-semibold uppercase tracking-[.13em] text-[var(--fp-green)]">{c.eyebrow}</span><h1 className="mt-3 text-[38px] font-semibold tracking-[-.055em]">{c.title}</h1><p className="mt-2 text-[15px] text-[var(--fp-muted)]">{c.sub}</p></div><Button variant="secondary" onClick={load} disabled={loading}>{loading?<Loader2 size={15} className="animate-spin"/>:<RefreshCw size={15}/>} {c.refresh}</Button></div><div className={`mt-8 flex items-center gap-4 rounded-[18px] border p-5 ${ok?'border-[#cfe3d5] bg-[#f1f7f2]':'border-[#efd6c9] bg-[#fff6f1]'}`}><span className={`grid size-11 place-items-center rounded-full bg-white ${ok?'text-[var(--fp-green)]':'text-[var(--fp-amber)]'}`}>{ok?<CheckCircle2 size={22}/>:<CircleAlert size={22}/>}</span><div><strong className="text-[18px]">{loading?c.checking:ok?c.ok:c.degraded}</strong><p className="mt-1 text-[14px] text-[var(--fp-muted)]">{checkedAt}</p></div></div><div className="mt-4 overflow-hidden rounded-[18px] border border-[var(--fp-border)] bg-white"><StatusRow name={c.application} ok={data?.checks.application}/><StatusRow name={c.database} ok={data?.checks.database}/><StatusRow name={c.routing} ok={data?.checks.routing} detail={data?(data.checks.routing?c.available:c.configuring):'—'}/></div><p className="mt-5 text-[13px] leading-5 text-[var(--fp-subtle)]">{c.foot}</p></section></main>}
function StatusRow({name,ok,detail}:{name:string;ok?:boolean;detail?:string}){return <div className="flex items-center justify-between gap-4 border-b border-[var(--fp-border)] px-5 py-4 last:border-b-0"><span className="text-[15px] font-medium">{name}</span><span className="flex items-center gap-2 text-[13px] text-[var(--fp-muted)]">{detail&&<span>{detail}</span>}<i className={`size-2.5 rounded-full ${ok?'bg-[#4ca56a]':'bg-[#d9a05b]'}`}/></span></div>}
