'use client'

import { BarChart3, Download, FileSpreadsheet, History, PiggyBank, Printer, ShieldCheck, Users } from 'lucide-react'
import { useWorkspace } from '@/components/workspace/WorkspaceProvider'
import { useLanguage } from '@/components/LanguageContext'
import { workspaceDictionaries } from '@/lib/workspace-i18n'
import { workspaceCopy } from '@/lib/workspace-copy'
import { downloadCsv, relativeDate } from '@/lib/metrics'
import { PageHeader, EmptyState } from '@/components/workspace/primitives'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { bankDetailsState } from '@/lib/payment-validation'

export default function ReportsPage(){
  const ws=useWorkspace();const {lang}=useLanguage();const t=workspaceDictionaries[lang];const copy=workspaceCopy[lang]
  const reports=[
    {key:'payments',title:t.reports.payments,desc:lang==='ru'?'Статусы, суммы, сроки и способы оплаты по всем платежам.':'Statuses, amounts, due dates and methods across all payments.',icon:FileSpreadsheet,count:ws.payments.length,download:()=>downloadCsv('flowpay-payments.csv',['payment_id','invoice','supplier','amount','source_currency','recipient_amount','recipient_currency','status','due_date','route','payment_method','charge_type','created_at'],ws.payments.map(p=>[p.id,p.invoice_number,p.supplier_name,p.amount,p.currency,p.recipient_amount??'',p.recipient_currency||'',p.status,p.due_date||'',p.route_provider_code||'',p.payment_method,p.charge_type,p.created_at]))},
    {key:'savings',title:t.reports.savings,desc:lang==='ru'?'История сравнений маршрутов и рассчитанной экономии.':'Route comparison history and calculated savings.',icon:PiggyBank,count:ws.calculations.length,download:()=>downloadCsv('flowpay-savings.csv',['quote_id','from','to','amount','source_currency','recipient_currency','best_provider','best_fee','estimated_saving','created_at'],ws.calculations.map(c=>[c.quote_id,c.from_country,c.to_country,c.amount,c.currency,c.recipient_currency||'',c.best_provider_code,c.best_fee,c.estimated_saving,c.created_at]))},
    {key:'counterparties',title:t.reports.counterparties,desc:lang==='ru'?'Контрагенты, страны, валюты и готовность банковских реквизитов.':'Counterparties, countries, currencies and payment-detail readiness.',icon:Users,count:ws.counterparties.length,download:()=>downloadCsv('flowpay-counterparties.csv',['name','country','currency','bank_country','bank_name','bic','payment_details','created_at'],ws.counterparties.map(c=>[c.name,c.country,c.currency,c.bank_country,c.bank_name,c.bic,bankDetailsState(c.bank_country,c.account_number,c.bic),c.created_at]))},
    {key:'api',title:t.reports.api,desc:lang==='ru'?'История запросов к FlowPay API и технические статусы ответов.':'FlowPay API request history and response status.',icon:BarChart3,count:ws.apiLogs.length,download:()=>downloadCsv('flowpay-api-usage.csv',['endpoint','status_code','duration_ms','created_at'],ws.apiLogs.map(l=>[l.endpoint,l.status_code,l.duration_ms??'',l.created_at]))},
    {key:'audit',title:lang==='ru'?'Журнал действий':lang==='fr'?'Journal d’audit':lang==='de'?'Audit-Protokoll':lang==='es'?'Registro de auditoría':'Audit log',desc:lang==='ru'?'Хронология ключевых изменений в аккаунте и финансовых данных.':'Chronology of important account and financial-data changes.',icon:ShieldCheck,count:ws.auditLogs.length,download:()=>downloadCsv('flowpay-audit-log.csv',['entity_type','entity_id','action','created_at'],ws.auditLogs.map(l=>[l.entity_type,l.entity_id||'',l.action,l.created_at]))},
  ]
  return <div className="fp-enter"><PageHeader title={t.reports.title} subtitle={t.reports.subtitle} actions={<Button className="fp-print-hide" variant="secondary" onClick={()=>window.print()}><Printer size={14}/>{lang==='ru'?'Печать / PDF':lang==='fr'?'Imprimer / PDF':lang==='de'?'Drucken / PDF':lang==='es'?'Imprimir / PDF':'Print / PDF'}</Button>}/>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map(r=><Card key={r.key} className="flex min-h-[205px] flex-col p-6"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-[11px] bg-[var(--fp-green-soft)] text-[var(--fp-green)]"><r.icon size={18}/></span><Badge tone="neutral">{r.count.toLocaleString()}</Badge></div><h2 className="mt-5 text-[16px] font-semibold tracking-[-.02em]">{r.title}</h2><p className="mt-1.5 text-[14px] leading-5 text-[var(--fp-muted)]">{r.desc}</p><Button variant="secondary" size="sm" className="fp-print-hide mt-auto w-full" disabled={!r.count} onClick={r.download}><Download size={14}/>{r.count?t.reports.download:t.reports.empty}</Button></Card>)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--fp-border)] px-5 py-4"><div><h2 className="flex items-center gap-2 text-[14px] font-semibold"><History size={15} className="text-[var(--fp-green)]"/>{lang==='ru'?'Последние изменения':lang==='fr'?'Modifications récentes':lang==='de'?'Letzte Änderungen':lang==='es'?'Cambios recientes':'Recent changes'}</h2><p className="mt-1 text-[14px] text-[var(--fp-muted)]">{lang==='ru'?'История ключевых изменений в аккаунте FlowPay.':'History of important changes across your FlowPay account.'}</p></div><Badge tone="neutral">{ws.auditLogs.length}</Badge></div>{ws.auditLogs.length?<div className="divide-y divide-[var(--fp-border)]">{ws.auditLogs.slice(0,14).map(row=><div key={row.id} className="grid grid-cols-[1fr_auto] gap-3 px-5 py-3 text-[14px] sm:grid-cols-[1fr_130px_120px]"><span className="min-w-0 truncate"><strong className="font-medium">{auditEntityLabel(row.entity_type,lang)}</strong></span><Badge tone={row.action==='delete'?'danger':row.action==='insert'?'success':'neutral'}>{auditActionLabel(row.action,lang)}</Badge><span className="hidden text-right text-[14px] text-[var(--fp-muted)] sm:block">{relativeDate(row.created_at,lang)}</span></div>)}</div>:<div className="p-6"><EmptyState compact title={t.common.noData}/></div>}</Card>
      <Card className="p-6"><h2 className="text-[14px] font-semibold">{lang==='ru'?'Данные и выгрузки':lang==='fr'?'Données et exports':lang==='de'?'Daten und Exporte':lang==='es'?'Datos y exportaciones':'Data & exports'}</h2><p className="mt-2 text-[14px] leading-5 text-[var(--fp-muted)]">{lang==='ru'?'В выгрузку попадают только данные вашего аккаунта FlowPay за выбранные разделы. Печатная версия использует те же актуальные показатели.':'Exports include only data from your FlowPay account. The print view uses the same current figures.'}</p><div className="mt-5 rounded-[11px] bg-[#f5f8f5] p-3 text-[14px] leading-5 text-[var(--fp-muted)]"><strong className="block text-[14px] text-[var(--fp-text)]">{lang==='ru'?'Данные в отчётах':'Report coverage'}</strong>{copy.common.payments}: {ws.payments.length.toLocaleString()} · {copy.common.invoices}: {ws.invoices.length.toLocaleString()} · {lang==='ru'?'Контрагенты':'Counterparties'}: {ws.counterparties.length.toLocaleString()}</div></Card>
    </div>
  </div>
}

function auditEntityLabel(value:string,lang:string){const ru:Record<string,string>={payment_drafts:'Платёж',counterparties:'Контрагент',invoices:'Счёт',calculations:'Расчёт маршрута',api_keys:'API-ключ',workspace_invitations:'Приглашение',company_profiles:'Профиль компании'};const en:Record<string,string>={payment_drafts:'Payment',counterparties:'Counterparty',invoices:'Invoice',calculations:'Route quote',api_keys:'API key',workspace_invitations:'Invitation',company_profiles:'Company profile'};return (lang==='ru'?ru:en)[value]||(lang==='ru'?'Активность':'Activity')}
function auditActionLabel(value:string,lang:string){if(lang==='ru')return value==='insert'?'Создано':value==='update'?'Изменено':value==='delete'?'Удалено':value;return value==='insert'?'Created':value==='update'?'Updated':value==='delete'?'Deleted':value}
